//! The `rt` target: the native tiny-skia rasterizer (`ulottie-rt`).
//!
//! Same display list as `skia-aot`, different consumer — instead of a JS
//! descriptor walked by a worklet, the restructured markup lowers to **RTDL**
//! (`ulottie_rt::rtdl`), a renderer-agnostic binary scene: numbers only, paths
//! as verb+point arrays, colours as float RGBA. The per-frame side flips from
//! runtime programs to compile-time baking: `scene::plan_sampled` runs the
//! binding bake at every integer frame, and the samples compress into numeric
//! keyframe tracks the native player interpolates. The emitted module carries
//! the blob as base64 plus a numeric `meta`; per-frame JS work on device is a
//! single `renderFrame(id, frame)` JSI call.
//!
//! The compiler links the very structs the device decodes (`ulottie-rt` with
//! `default-features = false`), and drives the same track `Player` for its
//! mandatory bbox pass: every group that forces an offscreen layer (opacity,
//! blend, mask, matte filter, effects) gets the union of its subtree's
//! animated bounds stamped on, because an unbounded native saveLayer measured
//! 13× slower.
//!
//! Refusals match `skia-aot` exactly (`support::scan_skia`, the same caps
//! whitelist, named bail on any unlowerable construct). One softer edge: a
//! scene whose node count is past the tiny-skia 60 fps budget compiles with a
//! named WARNING (stderr + module comment), not a refusal.

use std::collections::{BTreeMap, BTreeSet};

use anyhow::{Context, Result, bail, ensure};
use base64::Engine;
use ulottie_rt::anim::Player;
use ulottie_rt::rtdl::{
    Animation, Blend, Channel, Clip, Dash, FxPass, FxStage, Geom, Gradient, Group, Image, ImageRef,
    Keys, Mask, MatteInvert, Node as RtNode, Paint, PaintSource, PathData, Shape, Stop, Track,
    VERB_CLOSE, VERB_CUBIC, VERB_LINE, VERB_MOVE,
};
use ulottie_rt::{bounds, rtdl};

use crate::scene::{Caps, SampleFrame, op};
use crate::{CompileOptions, data, ir, scene};

use super::rn::{self, Node};
use super::{Report, emit};

/// Same whitelist as skia-aot: the rt rasterizer draws the same display list.
fn supported() -> Caps {
    rn::supported() | Caps::GRADIENT | Caps::RAMP | Caps::FX
}

/// Past this many display-list nodes, tiny-skia at 512² cannot hold 60 fps on
/// a phone (measured in the Phase-0 spike; ~2000 nodes is infeasible). The
/// scene still compiles — budget is a warning, correctness is a refusal.
const NODE_BUDGET: usize = 500;

pub fn report(module: &ir::Module, _options: &CompileOptions) -> Result<Option<Report>> {
    if !data::can_encode(module) {
        return Ok(None);
    }
    ensure!(
        module.expressions.is_empty(),
        "the rt target does not support expressions"
    );
    let payload = data::encode(module)?;
    // Integer-frame bake grid: eases are folded into the per-frame samples,
    // and the native player lerps between neighbouring integers.
    let frames: Vec<f64> = {
        let lo = payload.c.ip.ceil() as i64;
        let hi = payload.c.op.floor() as i64;
        (lo..=hi).map(|f| f as f64).collect()
    };
    let (scene, samples) = scene::plan_sampled(&payload, &[], &frames)?;
    let missing = scene.caps - supported();
    ensure!(
        missing.is_empty(),
        "the rt target does not support: {}",
        emit::caps_list(missing)
    );

    let (mut anim, elements) = animation_from_markup(&scene)?;
    anim.tracks = build_tracks(&samples, &frames)?;
    stamp_bboxes(&mut anim, &frames);

    let node_count = anim.nodes.len();
    let warning = (node_count > NODE_BUDGET).then(|| {
        format!(
            "WARNING: {node_count} display-list nodes exceed the rt target's ~{NODE_BUDGET}-node \
             60 fps budget (tiny-skia @512²); expect dropped frames on device"
        )
    });
    if let Some(w) = &warning {
        eprintln!("{w}");
    }

    let blob = rtdl::encode(&anim).context("RTDL encode")?;
    let b64 = base64::engine::general_purpose::STANDARD.encode(&blob);

    let n = |v: f64| crate::scene::svg::n(v);
    let meta = format!(
        "{{ fr: {}, ip: {}, op: {}, width: {}, height: {} }}",
        n(scene.data.fr),
        n(scene.data.ip),
        n(scene.data.op),
        n(anim.width as f64),
        n(anim.height as f64),
    );
    let mut js = format!(
        "// Generated by ulottie — rt target (native tiny-skia rasterizer via ulottie-rt).\n\
         // The scene ships as RTDL: a binary display list + numeric keyframe tracks,\n\
         // decoded and played natively; per-frame JS work is one renderFrame() call.\n\
         // caps: {}\n",
        emit::caps_list(scene.caps),
    );
    if let Some(w) = &warning {
        js.push_str(&format!("// {w}\n"));
    }
    js.push_str(&format!(
        "\nexport const rtdl = '{b64}';\n\nexport const meta = {meta};\n\n\
         export const init = () => ({meta});\n"
    ));

    let mut caps: Vec<String> = scene
        .caps
        .iter_names()
        .map(|(n, _)| n.to_string())
        .collect();
    caps.sort_unstable();
    Ok(Some(Report {
        js,
        caps,
        modules: Vec::new(),
        runtime_slice: 0,
        is_static: scene.is_static(),
        instanced: false,
        templated: false,
        elements,
        bindings: scene.data.b.len(),
        records: 0,
        generated: false,
        instance_clocks: false,
        assets: Vec::new(),
    }))
}

// ---------------------------------------------------------------------------
// Numeric parsers — the compiler's own baked output grammar, parsed back.
// ---------------------------------------------------------------------------

fn fnum(v: &str, what: &str) -> Result<f32> {
    v.parse::<f64>()
        .map(|f| f as f32)
        .map_err(|_| anyhow::anyhow!("non-numeric `{what}` value `{v}` in the rt target"))
}

/// The two transform spellings the compiler writes (see `scene::svg`), as
/// SVG-order `[a, b, c, d, e, f]`.
fn transform6(v: &str) -> Result<[f32; 6]> {
    if let Some(args) = v.strip_prefix("matrix(").and_then(|r| r.strip_suffix(')')) {
        let p: Vec<&str> = args.split(',').collect();
        ensure!(p.len() == 6, "matrix() with {} arguments", p.len());
        let mut m = [0.0f32; 6];
        for (i, s) in p.iter().enumerate() {
            m[i] = fnum(s, "matrix")?;
        }
        Ok(m)
    } else if let Some(args) = v
        .strip_prefix("translate(")
        .and_then(|r| r.strip_suffix(')'))
    {
        let p: Vec<&str> = args.split(',').collect();
        ensure!(p.len() == 2, "translate() with {} arguments", p.len());
        Ok([
            1.0,
            0.0,
            0.0,
            1.0,
            fnum(p[0], "translate")?,
            fnum(p[1], "translate")?,
        ])
    } else {
        bail!("unsupported transform `{v}` in the rt target")
    }
}

/// `#rgb` / `#rrggbb` / `rgb(r,g,b)` / `rgba(r,g,b,a)` → straight RGBA 0..=1.
fn color4(v: &str) -> Result<[f32; 4]> {
    if let Some(hex) = v.strip_prefix('#') {
        let d = |c: u8| -> Result<u32> {
            (c as char)
                .to_digit(16)
                .ok_or_else(|| anyhow::anyhow!("bad hex colour `{v}`"))
        };
        let b = hex.as_bytes();
        let (r, g, bl) = match b.len() {
            3 => (d(b[0])? * 17, d(b[1])? * 17, d(b[2])? * 17),
            6 => (
                d(b[0])? * 16 + d(b[1])?,
                d(b[2])? * 16 + d(b[3])?,
                d(b[4])? * 16 + d(b[5])?,
            ),
            _ => bail!("bad hex colour `{v}`"),
        };
        return Ok([r as f32 / 255.0, g as f32 / 255.0, bl as f32 / 255.0, 1.0]);
    }
    let (body, has_alpha) = if let Some(r) = v.strip_prefix("rgba(") {
        (r, true)
    } else if let Some(r) = v.strip_prefix("rgb(") {
        (r, false)
    } else {
        bail!("unsupported colour `{v}` in the rt target")
    };
    let body = body
        .strip_suffix(')')
        .ok_or_else(|| anyhow::anyhow!("unterminated colour `{v}`"))?;
    let p: Vec<&str> = body.split(',').map(str::trim).collect();
    ensure!(p.len() == if has_alpha { 4 } else { 3 }, "bad colour `{v}`");
    let ch = |s: &str| -> Result<f32> { Ok(fnum(s, "colour")? / 255.0) };
    Ok([
        ch(p[0])?,
        ch(p[1])?,
        ch(p[2])?,
        if has_alpha { fnum(p[3], "alpha")? } else { 1.0 },
    ])
}

/// The compiler's own `d` grammar (`scene::svg::FlatPath::to_d`): absolute
/// `M`/`L`/`C`/`Z` only, numbers quantized, comma elided before negatives.
fn parse_path(d: &str) -> Result<PathData> {
    let mut out = PathData::default();
    let b = d.as_bytes();
    let mut i = 0usize;
    let read_num = |i: &mut usize| -> Result<f32> {
        while *i < b.len() && matches!(b[*i], b' ' | b',') {
            *i += 1;
        }
        let start = *i;
        if *i < b.len() && matches!(b[*i], b'-' | b'+') {
            *i += 1;
        }
        while *i < b.len() && matches!(b[*i], b'0'..=b'9' | b'.') {
            *i += 1;
        }
        ensure!(*i > start, "expected a number at byte {start} of `d`");
        fnum(&d[start..*i], "d")
    };
    while i < b.len() {
        match b[i] {
            b' ' | b',' => i += 1,
            b'M' | b'L' => {
                let verb = if b[i] == b'M' { VERB_MOVE } else { VERB_LINE };
                i += 1;
                out.verbs.push(verb);
                out.points.push(read_num(&mut i)?);
                out.points.push(read_num(&mut i)?);
            }
            b'C' => {
                i += 1;
                out.verbs.push(VERB_CUBIC);
                for _ in 0..6 {
                    out.points.push(read_num(&mut i)?);
                }
            }
            b'Z' => {
                i += 1;
                out.verbs.push(VERB_CLOSE);
            }
            other => bail!(
                "unsupported path command `{}` in the rt target",
                other as char
            ),
        }
    }
    Ok(out)
}

fn blend_of(kw: &str) -> Result<Blend> {
    Ok(match kw {
        "multiply" => Blend::Multiply,
        "screen" => Blend::Screen,
        "overlay" => Blend::Overlay,
        "darken" => Blend::Darken,
        "lighten" => Blend::Lighten,
        "color-dodge" => Blend::ColorDodge,
        "color-burn" => Blend::ColorBurn,
        "hard-light" => Blend::HardLight,
        "soft-light" => Blend::SoftLight,
        "difference" => Blend::Difference,
        "exclusion" => Blend::Exclusion,
        "hue" => Blend::Hue,
        "saturation" => Blend::Saturation,
        "color" => Blend::Color,
        "luminosity" => Blend::Luminosity,
        other => bail!("unsupported mix-blend-mode `{other}`"),
    })
}

fn fill_rule_eo(v: &str) -> Result<bool> {
    match v {
        "evenodd" => Ok(true),
        "nonzero" => Ok(false),
        other => bail!("unsupported fill rule `{other}`"),
    }
}

// ---------------------------------------------------------------------------
// Markup → RTDL static scene.
// ---------------------------------------------------------------------------

const DEF_TAGS: &[&str] = &[
    "defs",
    "clipPath",
    "mask",
    "linearGradient",
    "radialGradient",
    "filter",
];

fn index_defs<'a>(n: &'a Node, map: &mut BTreeMap<&'a str, &'a Node>) {
    if let Some((_, id)) = n.attrs.iter().find(|(k, _)| k == "id")
        && DEF_TAGS.contains(&n.tag.as_str())
    {
        map.insert(id, n);
    }
    for c in &n.children {
        index_defs(c, map);
    }
}

fn attr<'n>(n: &'n Node, key: &str) -> Option<&'n str> {
    n.attrs
        .iter()
        .find(|(k, _)| k == key)
        .map(|(_, v)| v.as_str())
}

struct Build<'a> {
    defs: &'a BTreeMap<&'a str, &'a Node>,
    bound: &'a BTreeSet<usize>,
    /// Every slot stamped on an emitted node — checked against `bound` so a
    /// binding into a defs subtree fails loudly, same as skia-aot.
    slots: BTreeSet<usize>,
    nodes: Vec<RtNode>,
    gradients: Vec<Gradient>,
    /// Gradient defs pooled by id: a def shared by two paints resolves to one
    /// pool entry, so a bound gradient has exactly one track target.
    grad_ids: BTreeMap<String, u32>,
    images: Vec<Image>,
}

impl<'a> Build<'a> {
    /// A node's slot: registered always, carried only when a track binds it.
    fn take_slot(&mut self, s: Option<usize>) -> Option<u32> {
        let s = s?;
        self.slots.insert(s);
        self.bound.contains(&s).then_some(s as u32)
    }

    fn lookup(&self, v: &str, what: &str) -> Result<&'a Node> {
        let id = v
            .strip_prefix("url(#")
            .and_then(|r| r.strip_suffix(')'))
            .ok_or_else(|| anyhow::anyhow!("unsupported {what} value `{v}`"))?;
        self.defs
            .get(id)
            .copied()
            .ok_or_else(|| anyhow::anyhow!("unresolved reference `{v}`"))
    }

    /// Drawable children (defs skipped) → arena indices.
    fn lower_list(&mut self, children: &[Node]) -> Result<Vec<u32>> {
        let mut out = Vec::new();
        for c in children {
            if DEF_TAGS.contains(&c.tag.as_str()) {
                continue;
            }
            out.push(self.lower_node(c)?);
        }
        Ok(out)
    }

    fn lower_node(&mut self, n: &Node) -> Result<u32> {
        let node = match n.tag.as_str() {
            "g" => RtNode::Group(self.lower_group(n)?),
            "path" | "rect" | "ellipse" => RtNode::Shape(self.lower_shape(n)?),
            "image" => RtNode::Image(self.lower_image(n)?),
            other => bail!("the rt target cannot lower <{other}>"),
        };
        self.nodes.push(node);
        Ok((self.nodes.len() - 1) as u32)
    }

    fn lower_group(&mut self, n: &Node) -> Result<Group> {
        let mut g = Group {
            slot: self.take_slot(n.slot),
            opacity: 1.0,
            ..Group::default()
        };
        for (k, v) in &n.attrs {
            match k.as_str() {
                "transform" => g.matrix = Some(transform6(v)?),
                "opacity" => g.opacity = fnum(v, "opacity")?,
                "display" if v == "none" => g.hidden = true,
                "style" => {
                    for decl in v.split(';').filter(|d| !d.is_empty()) {
                        match decl {
                            // The viewport clip already rides the flattened
                            // group's clip-path.
                            "overflow:hidden" => {}
                            "display:none" => g.hidden = true,
                            other => match other.strip_prefix("mix-blend-mode:") {
                                Some(kw) => g.blend = Some(blend_of(kw)?),
                                None => bail!("unsupported style `{other}` in the rt target"),
                            },
                        }
                    }
                }
                "clip-path" => g.clip = Some(self.lower_clip(v)?),
                "mask" => g.mask = Some(self.lower_mask(v)?),
                "filter" => self.lower_filter(v, &mut g)?,
                other => bail!("the rt target cannot lower <g {other}>"),
            }
        }
        g.children = self.lower_list(&n.children)?;
        Ok(g)
    }

    fn lower_clip(&mut self, v: &str) -> Result<Clip> {
        let def = self.lookup(v, "clip-path")?;
        ensure!(def.tag == "clipPath", "`{v}` does not name a <clipPath>");
        for (k, val) in &def.attrs {
            match k.as_str() {
                "id" => {}
                "clipPathUnits" if val == "userSpaceOnUse" => {}
                other => bail!("the rt target cannot lower <clipPath {other}>"),
            }
        }
        ensure!(
            def.children.len() == 1,
            "the rt target only lowers single-shape clip paths"
        );
        let c = &def.children[0];
        match c.tag.as_str() {
            "rect" => {
                let (mut x, mut y, mut w, mut h) = (0.0, 0.0, None, None);
                for (k, val) in &c.attrs {
                    match k.as_str() {
                        "x" => x = fnum(val, "x")?,
                        "y" => y = fnum(val, "y")?,
                        "width" => w = Some(fnum(val, "width")?),
                        "height" => h = Some(fnum(val, "height")?),
                        other => bail!("the rt target cannot lower a clip <rect {other}>"),
                    }
                }
                let (Some(w), Some(h)) = (w, h) else {
                    bail!("clip <rect> without width/height");
                };
                Ok(Clip::Rect([x, y, w, h]))
            }
            "path" => {
                let slot = self.take_slot(c.slot);
                let mut path = None;
                let mut eo = false;
                for (k, val) in &c.attrs {
                    match k.as_str() {
                        "d" => path = Some(parse_path(val)?),
                        "clip-rule" | "fill-rule" => eo = fill_rule_eo(val)?,
                        other => bail!("the rt target cannot lower a clip <path {other}>"),
                    }
                }
                // An animated-from-`ip` clip has no baked `d`: empty verbs
                // clip everything away until the first track key writes it.
                ensure!(path.is_some() || slot.is_some(), "clip <path> without d");
                Ok(Clip::Path {
                    slot,
                    path: path.unwrap_or_default(),
                    even_odd: eo,
                })
            }
            other => bail!("the rt target cannot lower a <{other}> clip shape"),
        }
    }

    fn lower_gradient(&mut self, v: &str) -> Result<u32> {
        let def = self.lookup(v, "paint")?;
        let radial = match def.tag.as_str() {
            "radialGradient" => true,
            "linearGradient" => false,
            other => bail!("`{v}` names a <{other}>, not a gradient"),
        };
        let id = attr(def, "id").unwrap_or("").to_string();
        if let Some(&gi) = self.grad_ids.get(&id) {
            return Ok(gi);
        }
        let slot = self.take_slot(def.slot);
        let bound_self = slot.is_some();
        let mut coords: BTreeMap<&str, f32> = BTreeMap::new();
        let mut gt = None;
        let mut units = false;
        for (k, val) in &def.attrs {
            match k.as_str() {
                "id" => {}
                "gradientUnits" if val == "userSpaceOnUse" => units = true,
                "gradientTransform" => gt = Some(transform6(val)?),
                "cx" | "cy" | "r" if radial => {
                    coords.insert(k, fnum(val, k)?);
                }
                "x1" | "y1" | "x2" | "y2" if !radial => {
                    coords.insert(k, fnum(val, k)?);
                }
                other => bail!("the rt target cannot lower <{} {other}>", def.tag),
            }
        }
        ensure!(
            units,
            "<{}> without gradientUnits=\"userSpaceOnUse\"",
            def.tag
        );
        let at = |k: &str| -> Result<f32> {
            match coords.get(k) {
                Some(v) => Ok(*v),
                // The Gradient track writes every coordinate at its first key.
                None if bound_self => Ok(0.0),
                None => bail!("<{}> without `{k}`", def.tag),
            }
        };
        let coords = if radial {
            [at("cx")?, at("cy")?, at("r")?, 0.0]
        } else {
            [at("x1")?, at("y1")?, at("x2")?, at("y2")?]
        };
        let mut stops = Vec::new();
        for s in &def.children {
            ensure!(s.tag == "stop", "unexpected <{}> inside a gradient", s.tag);
            let stop_slot = self.take_slot(s.slot);
            let (mut off, mut color) = (None, None);
            for (k, val) in &s.attrs {
                match k.as_str() {
                    "offset" => off = Some(fnum(val, "offset")?),
                    "stop-color" => color = Some(color4(val)?),
                    other => bail!("the rt target cannot lower <stop {other}>"),
                }
            }
            // A bound stop defaults until its first RAMP key writes it.
            let (off, color) = if stop_slot.is_some() {
                (off.unwrap_or(0.0), color.unwrap_or([0.0, 0.0, 0.0, 1.0]))
            } else {
                match (off, color) {
                    (Some(o), Some(c)) => (o, c),
                    _ => bail!("<stop> without offset/stop-color"),
                }
            };
            stops.push(Stop {
                slot: stop_slot,
                offset: off,
                color,
            });
        }
        self.gradients.push(Gradient {
            slot,
            radial,
            coords,
            stops,
            transform: gt,
        });
        let gi = (self.gradients.len() - 1) as u32;
        self.grad_ids.insert(id, gi);
        Ok(gi)
    }

    fn lower_mask(&mut self, v: &str) -> Result<Mask> {
        let def = self.lookup(v, "mask")?;
        ensure!(def.tag == "mask", "`{v}` does not name a <mask>");
        let mut luma = true;
        for (k, val) in &def.attrs {
            match (k.as_str(), val.as_str()) {
                ("id", _) => {}
                ("mask-type" | "maskType", "alpha") => luma = false,
                ("mask-type" | "maskType", "luminance") => luma = true,
                ("maskUnits", "userSpaceOnUse") => {}
                ("x", "0") | ("y", "0") => {}
                ("width" | "height", val) => {
                    fnum(val, k)?;
                }
                (other, val) => bail!("the rt target cannot lower <mask {other}=\"{val}\">"),
            }
        }
        let children = self.lower_list(&def.children)?;
        Ok(Mask { luma, children })
    }

    fn lower_filter(&mut self, v: &str, g: &mut Group) -> Result<()> {
        let def = self.lookup(v, "filter")?;
        ensure!(def.tag == "filter", "`{v}` does not name a <filter>");
        if let Some(s) = def.slot {
            self.slots.insert(s);
        }
        if attr(def, "filterUnits") == Some("userSpaceOnUse") {
            g.cf = Some(self.lower_invert(def)?);
            return Ok(());
        }
        g.fx = self.lower_fx(def)?;
        Ok(())
    }

    fn lower_invert(&mut self, def: &'a Node) -> Result<MatteInvert> {
        let mut r: BTreeMap<&str, f32> = BTreeMap::new();
        for (k, val) in &def.attrs {
            match k.as_str() {
                "id" => {}
                "filterUnits" if val == "userSpaceOnUse" => {}
                "x" | "y" | "width" | "height" => {
                    r.insert(k, fnum(val, k)?);
                }
                other => bail!("the rt target cannot lower <filter {other}>"),
            }
        }
        let at = |k: &str| -> Result<f32> {
            r.get(k)
                .copied()
                .ok_or_else(|| anyhow::anyhow!("<filter> without `{k}`"))
        };
        ensure!(
            def.children.len() == 1 && def.children[0].tag == "feColorMatrix",
            "the rt target only lowers a single <feColorMatrix> filter"
        );
        let (m, cif) = self.fe_matrix(&def.children[0])?;
        ensure!(
            cif.is_none(),
            "unexpected color-interpolation-filters on a matte inversion"
        );
        let (x, y) = (at("x")?, at("y")?);
        Ok(MatteInvert {
            matrix: m,
            rect: [x, y, x + at("width")?, y + at("height")?],
        })
    }

    /// The layer-effect primitive chains `scene::build::emit_effects` writes,
    /// as sequential fx stages — the same recognition as skia-aot, including
    /// its documented divergence: percentage filter regions are dropped, so a
    /// drop shadow escapes lottie-web's default `0%/100%` region instead of
    /// clipping to the element's own box. (The tint pair keeps its declared
    /// spaces — the rasterizer runs the luminance matrix in linearRGB.)
    fn lower_fx(&mut self, def: &'a Node) -> Result<Vec<FxStage>> {
        for (k, val) in &def.attrs {
            match k.as_str() {
                "id" => {}
                "x" | "y" | "width" | "height" if val.ends_with('%') => {}
                other => bail!("the rt target cannot lower <filter {other}>"),
            }
        }
        let c = &def.children;
        let mut stages = Vec::new();
        let mut i = 0;
        while i < c.len() {
            match c[i].tag.as_str() {
                "feColorMatrix" => {
                    let (m, cif) = self.fe_matrix(&c[i])?;
                    if cif.as_deref() == Some("linearRGB") {
                        // Tint: source, luma (t1), ramp∘luma (t2), merged.
                        ensure!(i + 2 < c.len(), "truncated tint chain in the rt target");
                        let (m2, cif2) = self.fe_matrix(&c[i + 1])?;
                        ensure!(
                            cif2.as_deref() == Some("sRGB"),
                            "tint ramp matrix without sRGB interpolation"
                        );
                        self.fe_merge(&c[i + 2], 3)?;
                        stages.push(FxStage {
                            passes: vec![
                                FxPass::Source,
                                FxPass::ColorMatrix(m),
                                FxPass::ColorMatrix2 {
                                    outer: m2,
                                    inner: m,
                                },
                            ],
                        });
                        i += 3;
                    } else {
                        ensure!(
                            cif.as_deref() == Some("sRGB"),
                            "effect colour matrix without sRGB interpolation"
                        );
                        stages.push(FxStage {
                            passes: vec![FxPass::ColorMatrix(m)],
                        });
                        i += 1;
                    }
                }
                "feGaussianBlur" if attr(&c[i], "in") == Some("SourceAlpha") => {
                    ensure!(
                        i + 4 < c.len(),
                        "truncated drop-shadow chain in the rt target"
                    );
                    let pass = self.fe_shadow(&c[i], &c[i + 1], &c[i + 2], &c[i + 3], &c[i + 4])?;
                    stages.push(FxStage { passes: vec![pass] });
                    i += 5;
                }
                "feGaussianBlur" => {
                    let pass = self.fe_blur(&c[i])?;
                    stages.push(FxStage { passes: vec![pass] });
                    i += 1;
                }
                other => bail!("the rt target cannot lower <{other}>"),
            }
        }
        ensure!(!stages.is_empty(), "<filter> with no primitives");
        Ok(stages)
    }

    fn fe_matrix(&mut self, fe: &'a Node) -> Result<([f32; 20], Option<String>)> {
        ensure!(
            fe.tag == "feColorMatrix",
            "expected <feColorMatrix>, found <{}>",
            fe.tag
        );
        if let Some(s) = fe.slot {
            self.slots.insert(s);
        }
        let mut values = None;
        let mut cif = None;
        for (k, val) in &fe.attrs {
            match k.as_str() {
                "type" if val == "matrix" => {}
                "color-interpolation-filters" => cif = Some(val.clone()),
                "values" => values = Some(val),
                "result" => {}
                other => bail!("the rt target cannot lower <feColorMatrix {other}>"),
            }
        }
        let Some(values) = values else {
            bail!("<feColorMatrix> without values")
        };
        let parts: Vec<&str> = values.split_ascii_whitespace().collect();
        ensure!(
            parts.len() == 20,
            "color matrix with {} values",
            parts.len()
        );
        let mut m = [0.0f32; 20];
        for (i, p) in parts.iter().enumerate() {
            m[i] = fnum(p, "values")?;
        }
        Ok((m, cif))
    }

    fn fe_merge(&mut self, fe: &'a Node, n: usize) -> Result<()> {
        ensure!(
            fe.tag == "feMerge",
            "expected <feMerge>, found <{}>",
            fe.tag
        );
        if let Some(s) = fe.slot {
            self.slots.insert(s);
        }
        ensure!(
            fe.children.len() == n,
            "<feMerge> with {} inputs where {n} were expected",
            fe.children.len()
        );
        for c in &fe.children {
            ensure!(
                c.tag == "feMergeNode",
                "unexpected <{}> in <feMerge>",
                c.tag
            );
            if let Some(s) = c.slot {
                self.slots.insert(s);
            }
        }
        Ok(())
    }

    fn fe_shadow(
        &mut self,
        blur: &'a Node,
        off: &'a Node,
        flood: &'a Node,
        comp: &'a Node,
        merge: &'a Node,
    ) -> Result<FxPass> {
        let blur_slot = self.take_slot(blur.slot);
        let mut std_dev = 0.0;
        for (k, val) in &blur.attrs {
            match k.as_str() {
                "in" | "result" => {}
                "stdDeviation" => std_dev = fnum(val, k)?,
                other => bail!("the rt target cannot lower <feGaussianBlur {other}>"),
            }
        }
        ensure!(
            off.tag == "feOffset",
            "expected <feOffset>, found <{}>",
            off.tag
        );
        let offset_slot = self.take_slot(off.slot);
        let (mut dx, mut dy) = (0.0, 0.0);
        for (k, val) in &off.attrs {
            match k.as_str() {
                "in" | "result" => {}
                "dx" => dx = fnum(val, k)?,
                "dy" => dy = fnum(val, k)?,
                other => bail!("the rt target cannot lower <feOffset {other}>"),
            }
        }
        ensure!(
            flood.tag == "feFlood",
            "expected <feFlood>, found <{}>",
            flood.tag
        );
        let flood_slot = self.take_slot(flood.slot);
        let mut color = None;
        let mut fo = 1.0;
        for (k, val) in &flood.attrs {
            match k.as_str() {
                "result" => {}
                "flood-color" => color = Some(color4(val)?),
                "flood-opacity" => fo = fnum(val, k)?,
                other => bail!("the rt target cannot lower <feFlood {other}>"),
            }
        }
        let Some(color) = color else {
            bail!("<feFlood> without flood-color")
        };
        ensure!(
            comp.tag == "feComposite",
            "expected <feComposite>, found <{}>",
            comp.tag
        );
        if let Some(s) = comp.slot {
            self.slots.insert(s);
        }
        for (k, val) in &comp.attrs {
            match k.as_str() {
                "in" | "in2" | "result" => {}
                "operator" if val == "in" => {}
                other => bail!("the rt target cannot lower <feComposite {other}>"),
            }
        }
        self.fe_merge(merge, 2)?;
        Ok(FxPass::Shadow {
            blur_slot,
            offset_slot,
            flood_slot,
            std_dev,
            dx,
            dy,
            color,
            flood_opacity: fo,
        })
    }

    fn fe_blur(&mut self, fe: &'a Node) -> Result<FxPass> {
        let slot = self.take_slot(fe.slot);
        let (mut sx, mut sy) = (0.0, 0.0);
        let mut wrap = None;
        for (k, val) in &fe.attrs {
            match k.as_str() {
                "result" => {}
                "stdDeviation" => {
                    let p: Vec<&str> = val.split(' ').collect();
                    ensure!(p.len() == 2, "stdDeviation `{val}` is not an x/y pair");
                    sx = fnum(p[0], k)?;
                    sy = fnum(p[1], k)?;
                }
                "edgeMode" => {
                    wrap = Some(match val.as_str() {
                        "wrap" => true,
                        "duplicate" => false,
                        other => bail!("unsupported edgeMode `{other}`"),
                    });
                }
                other => bail!("the rt target cannot lower <feGaussianBlur {other}>"),
            }
        }
        let Some(wrap) = wrap else {
            bail!("<feGaussianBlur> without edgeMode")
        };
        Ok(FxPass::Blur { slot, sx, sy, wrap })
    }

    fn lower_image(&mut self, n: &Node) -> Result<ImageRef> {
        ensure!(n.children.is_empty(), "unexpected children inside <image>");
        let (mut w, mut h, mut data) = (None, None, None);
        for (key, v) in &n.attrs {
            match key.as_str() {
                "width" => w = Some(fnum(v, "width")?),
                "height" => h = Some(fnum(v, "height")?),
                "preserveAspectRatio" => {
                    ensure!(
                        v == "xMidYMid slice",
                        "unsupported preserveAspectRatio `{v}` in the rt target"
                    );
                }
                "href" => {
                    let b64 = v
                        .strip_prefix("data:")
                        .and_then(|rest| rest.split_once(";base64,"))
                        .map(|(_, b)| b);
                    let Some(b64) = b64 else {
                        bail!("the rt target cannot draw a non-embedded image source")
                    };
                    data = Some(
                        base64::engine::general_purpose::STANDARD
                            .decode(b64)
                            .context("embedded image base64")?,
                    );
                }
                other => bail!("the rt target cannot lower <image {other}>"),
            }
        }
        let (Some(w), Some(h), Some(data)) = (w, h, data) else {
            bail!("<image> without width/height/href");
        };
        self.images.push(decode_png(&data)?);
        Ok(ImageRef {
            image: (self.images.len() - 1) as u32,
            w,
            h,
        })
    }

    fn lower_shape(&mut self, n: &Node) -> Result<Shape> {
        ensure!(
            n.children.is_empty(),
            "unexpected children inside <{}>",
            n.tag
        );
        let kind = n.tag.as_str();
        let mut s = Shape {
            slot: self.take_slot(n.slot),
            matrix: None,
            opacity: 1.0,
            hidden: false,
            geom: match kind {
                // A geometry attribute animated from frame `ip` is not baked
                // and SVG defaults are 0 — a zero-extent shape draws nothing
                // until the first track key, matching the web behaviour.
                "path" => Geom::Path(PathData::default()),
                "rect" => Geom::Rect {
                    x: 0.0,
                    y: 0.0,
                    w: 0.0,
                    h: 0.0,
                    rx: 0.0,
                    ry: 0.0,
                },
                _ => Geom::Ellipse {
                    cx: 0.0,
                    cy: 0.0,
                    rx: 0.0,
                    ry: 0.0,
                },
            },
            even_odd: false,
            paint: Paint::default(),
        };
        // SVG paints black when `fill` is absent; `fill="none"` clears it.
        s.paint.fill = Some(PaintSource::Color([0.0, 0.0, 0.0, 1.0]));
        for (key, v) in &n.attrs {
            match key.as_str() {
                "transform" => s.matrix = Some(transform6(v)?),
                "opacity" => s.opacity = fnum(v, "opacity")?,
                "display" if v == "none" => s.hidden = true,
                "style" => {
                    for decl in v.split(';').filter(|d| !d.is_empty()) {
                        match decl {
                            "display:none" => s.hidden = true,
                            other => bail!("unsupported style `{other}` in the rt target"),
                        }
                    }
                }
                "d" if kind == "path" => s.geom = Geom::Path(parse_path(v)?),
                "fill-rule" | "clip-rule" => s.even_odd = fill_rule_eo(v)?,
                "x" | "y" | "width" | "height" | "rx" | "ry" if kind == "rect" => {
                    let Geom::Rect { x, y, w, h, rx, ry } = &mut s.geom else {
                        unreachable!()
                    };
                    let f = fnum(v, key)?;
                    match key.as_str() {
                        "x" => *x = f,
                        "y" => *y = f,
                        "width" => *w = f,
                        "height" => *h = f,
                        "rx" => *rx = f,
                        _ => *ry = f,
                    }
                }
                "cx" | "cy" | "rx" | "ry" if kind == "ellipse" => {
                    let Geom::Ellipse { cx, cy, rx, ry } = &mut s.geom else {
                        unreachable!()
                    };
                    let f = fnum(v, key)?;
                    match key.as_str() {
                        "cx" => *cx = f,
                        "cy" => *cy = f,
                        "rx" => *rx = f,
                        _ => *ry = f,
                    }
                }
                "fill" => {
                    s.paint.fill = if v == "none" {
                        None
                    } else if v.starts_with("url(") {
                        Some(PaintSource::Gradient(self.lower_gradient(v)?))
                    } else {
                        Some(PaintSource::Color(color4(v)?))
                    };
                }
                "fill-opacity" => s.paint.fill_opacity = fnum(v, key)?,
                "stroke" => {
                    if v != "none" {
                        s.paint.stroke = Some(if v.starts_with("url(") {
                            PaintSource::Gradient(self.lower_gradient(v)?)
                        } else {
                            PaintSource::Color(color4(v)?)
                        });
                    }
                }
                "stroke-opacity" => s.paint.stroke_opacity = fnum(v, key)?,
                "stroke-width" => s.paint.stroke_width = fnum(v, key)?,
                "stroke-linecap" => {
                    s.paint.cap = match v.as_str() {
                        "butt" => 0,
                        "round" => 1,
                        "square" => 2,
                        other => bail!("unsupported stroke-linecap `{other}`"),
                    };
                }
                "stroke-linejoin" => {
                    s.paint.join = match v.as_str() {
                        "miter" => 0,
                        "round" => 1,
                        "bevel" => 2,
                        other => bail!("unsupported stroke-linejoin `{other}`"),
                    };
                }
                "stroke-miterlimit" => s.paint.miter_limit = fnum(v, key)?,
                "stroke-dasharray" => {
                    let nums: Result<Vec<f32>> =
                        v.split(' ').map(|p| fnum(p, "stroke-dasharray")).collect();
                    s.paint
                        .dash
                        .get_or_insert(Dash {
                            array: Vec::new(),
                            offset: 0.0,
                        })
                        .array = nums?;
                }
                "stroke-dashoffset" => {
                    s.paint
                        .dash
                        .get_or_insert(Dash {
                            array: Vec::new(),
                            offset: 0.0,
                        })
                        .offset = fnum(v, key)?;
                }
                "paint-order" => {
                    ensure!(v == "stroke", "unsupported paint-order `{v}`");
                    s.paint.stroke_first = true;
                }
                other => bail!("the rt target cannot lower <{} {other}>", n.tag),
            }
        }
        Ok(s)
    }
}

/// An embedded PNG → straight (unpremultiplied) RGBA8. The one format the
/// bodymovin exporters embed; anything else refuses by name.
fn decode_png(bytes: &[u8]) -> Result<Image> {
    ensure!(
        bytes.starts_with(&[0x89, b'P', b'N', b'G']),
        "the rt target only decodes embedded PNG images"
    );
    let mut decoder = png::Decoder::new(std::io::Cursor::new(bytes));
    decoder.set_transformations(
        png::Transformations::ALPHA | png::Transformations::EXPAND | png::Transformations::STRIP_16,
    );
    let mut reader = decoder.read_info().context("PNG header")?;
    let mut buf = vec![0u8; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).context("PNG frame")?;
    buf.truncate(info.buffer_size());
    let rgba = match info.color_type {
        png::ColorType::Rgba => buf,
        png::ColorType::GrayscaleAlpha => buf
            .chunks_exact(2)
            .flat_map(|ga| [ga[0], ga[0], ga[0], ga[1]])
            .collect(),
        other => bail!("unexpected decoded PNG colour type {other:?}"),
    };
    Ok(Image {
        width: info.width,
        height: info.height,
        rgba,
    })
}

/// The restructured markup → the static RTDL scene plus the element count.
fn animation_from_markup(scene: &scene::Scene) -> Result<(Animation, usize)> {
    let mut root = rn::parse_markup(&scene.markup)?;
    ensure!(root.tag == "svg", "the document root is <{}>", root.tag);
    let mut count = 0usize;
    rn::assign_slots(&mut root, true, &mut count);
    rn::lower_invert_filters(&mut root)?;
    rn::flatten_nested_svgs(&mut root)?;

    // Root sanity: the rasterizer assumes the design space starts at the
    // origin (the fit transform and the viewport clips do too).
    for (k, v) in &root.attrs {
        match k.as_str() {
            "viewBox" => ensure!(
                v.starts_with("0 0 "),
                "viewBox `{v}` does not start at the origin"
            ),
            "width" | "height" => {}
            "preserveAspectRatio" => ensure!(
                v == "xMidYMid meet",
                "unsupported preserveAspectRatio `{v}` (the player fits xMidYMid meet)"
            ),
            "xmlns" => {}
            "style" => {
                for decl in v.split(';').filter(|d| !d.is_empty()) {
                    ensure!(decl == "overflow:hidden", "unsupported root style `{decl}`");
                }
            }
            other => bail!("the rt target cannot lower <svg {other}>"),
        }
    }

    // Design size: numeric width/height, else the viewBox extent.
    let view: Vec<&str> = attr(&root, "viewBox").unwrap_or("").split(' ').collect();
    let dim = |name: &str, vb: usize| -> f32 {
        attr(&root, name)
            .and_then(|v| v.parse::<f32>().ok())
            .or_else(|| view.get(vb).and_then(|v| v.parse().ok()))
            .unwrap_or(0.0)
    };

    let bound: BTreeSet<usize> = scene.data.b.iter().map(|b| b.el_index as usize).collect();
    let mut defs = BTreeMap::new();
    index_defs(&root, &mut defs);
    let mut build = Build {
        defs: &defs,
        bound: &bound,
        slots: BTreeSet::new(),
        nodes: vec![RtNode::Group(Group::default())], // reserve the root
        gradients: Vec::new(),
        grad_ids: BTreeMap::new(),
        images: Vec::new(),
    };
    let children = build.lower_list(&root.children)?;
    build.nodes[0] = RtNode::Group(Group {
        opacity: 1.0,
        children,
        ..Group::default()
    });
    for b in &bound {
        ensure!(
            build.slots.contains(b),
            "binding addresses element {b}, which is not a drawable node (defs subtree or past the tree)"
        );
    }
    Ok((
        Animation {
            width: dim("width", 2),
            height: dim("height", 3),
            fr: scene.data.fr as f32,
            ip: scene.data.ip as f32,
            op: scene.data.op as f32,
            nodes: build.nodes,
            gradients: build.gradients,
            images: build.images,
            tracks: Vec::new(),
        },
        count,
    ))
}

// ---------------------------------------------------------------------------
// Frame samples → compressed numeric tracks.
// ---------------------------------------------------------------------------

/// One channel's parsed per-frame value, comparable for change-point
/// compression.
#[derive(Clone, Debug, PartialEq)]
enum Val {
    F(f32),
    F2([f32; 2]),
    F4([f32; 4]),
    F6([f32; 6]),
    Path(PathData),
    Dash(Dash),
}

/// Channel discriminants, ordered so tracks emit deterministically.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum Kind {
    Matrix,
    Opacity,
    Hidden,
    Path,
    Rect,
    Ellipse,
    Fill,
    FillOpacity,
    Stroke,
    StrokeOpacity,
    StrokeWidth,
    Dash,
    Gradient,
    Stop,
    BlurStd,
    ShadowStd,
    FloodOpacity,
    ShadowOffset,
}

/// One live binding sample → its channel writes. The op code disambiguates
/// where attribute names alone cannot (`style:display:none` hides an element
/// under DISPLAY but empties its path under a trimmed SHAPE; `stdDeviation`
/// is an x/y pair under FX_BLUR and a scalar under FX_STD).
fn channel_writes(opc: u8, attrs: &[(String, String)]) -> Result<Vec<(Kind, Val)>> {
    let get = |k: &str| attrs.iter().find(|(a, _)| a == k).map(|(_, v)| v.as_str());
    let hidden = attrs
        .iter()
        .any(|(k, v)| k == "style" && v == "display:none");
    let mut out = Vec::new();
    match opc {
        op::TRANSFORM | op::TRANSLATE | op::TRANSFORM_SKEW | op::LAYER_TX => {
            if let Some(v) = get("transform") {
                out.push((Kind::Matrix, Val::F6(transform6(v)?)));
            }
        }
        op::OPACITY | op::LAYER_OP => {
            if let Some(v) = get("opacity") {
                out.push((Kind::Opacity, Val::F(fnum(v, "opacity")?)));
            }
        }
        op::DISPLAY => {
            // A live DISPLAY write is the value even when it writes nothing:
            // the runtime clears the attribute on a visible frame.
            out.push((Kind::Hidden, Val::F(if hidden { 1.0 } else { 0.0 })));
        }
        op::SHAPE | op::SHAPE_RECT | op::SHAPE_ELLIPSE | op::SHAPE_STAR | op::SHAPE_MULTI => {
            // A SHAPE write is authoritative for visibility: a trim that
            // empties hides the element (the skia runtime sets `hd` from the
            // frame's attrs), and a `d` write shows it — the static markup may
            // carry `display:none` when the shape is empty at frame `ip`.
            out.push((Kind::Hidden, Val::F(if hidden { 1.0 } else { 0.0 })));
            if let Some(d) = get("d")
                && !hidden
            {
                out.push((Kind::Path, Val::Path(parse_path(d)?)));
            }
        }
        op::RECT => {
            let f = |k: &str, def: f32| -> Result<f32> {
                get(k)
                    .map(|v| fnum(v, k))
                    .transpose()
                    .map(|o| o.unwrap_or(def))
            };
            out.push((
                Kind::Rect,
                Val::F6([
                    f("x", 0.0)?,
                    f("y", 0.0)?,
                    f("width", 0.0)?,
                    f("height", 0.0)?,
                    f("rx", 0.0)?,
                    f("ry", 0.0)?,
                ]),
            ));
        }
        op::ELLIPSE => {
            let f = |k: &str| -> Result<f32> { fnum(get(k).unwrap_or("0"), k) };
            out.push((
                Kind::Ellipse,
                Val::F4([f("cx")?, f("cy")?, f("rx")?, f("ry")?]),
            ));
        }
        op::FILL => {
            if let Some(v) = get("fill") {
                out.push((Kind::Fill, Val::F4(color4(v)?)));
            }
            if let Some(v) = get("fill-opacity") {
                out.push((Kind::FillOpacity, Val::F(fnum(v, "fill-opacity")?)));
            }
        }
        op::STROKE => {
            if let Some(v) = get("stroke") {
                out.push((Kind::Stroke, Val::F4(color4(v)?)));
            }
            if let Some(v) = get("stroke-opacity") {
                out.push((Kind::StrokeOpacity, Val::F(fnum(v, "stroke-opacity")?)));
            }
            if let Some(v) = get("stroke-width") {
                out.push((Kind::StrokeWidth, Val::F(fnum(v, "stroke-width")?)));
            }
        }
        op::GRADIENT => {
            if get("cx").is_some() {
                out.push((
                    Kind::Gradient,
                    Val::F4([
                        fnum(get("cx").unwrap_or("0"), "cx")?,
                        fnum(get("cy").unwrap_or("0"), "cy")?,
                        fnum(get("r").unwrap_or("0"), "r")?,
                        0.0,
                    ]),
                ));
            } else {
                out.push((
                    Kind::Gradient,
                    Val::F4([
                        fnum(get("x1").unwrap_or("0"), "x1")?,
                        fnum(get("y1").unwrap_or("0"), "y1")?,
                        fnum(get("x2").unwrap_or("0"), "x2")?,
                        fnum(get("y2").unwrap_or("0"), "y2")?,
                    ]),
                ));
            }
        }
        op::RAMP => {
            let o = fnum(get("offset").unwrap_or("0"), "offset")?;
            let c = color4(get("stop-color").unwrap_or("rgb(0,0,0)"))?;
            out.push((Kind::Stop, Val::F4([o, c[0], c[1], c[2]])));
        }
        op::DASH => {
            let array: Result<Vec<f32>> = get("stroke-dasharray")
                .unwrap_or("")
                .split(' ')
                .filter(|p| !p.is_empty())
                .map(|p| fnum(p, "stroke-dasharray"))
                .collect();
            out.push((
                Kind::Dash,
                Val::Dash(Dash {
                    array: array?,
                    offset: fnum(get("stroke-dashoffset").unwrap_or("0"), "stroke-dashoffset")?,
                }),
            ));
        }
        op::FX_BLUR => {
            if let Some(v) = get("stdDeviation") {
                let p: Vec<&str> = v.split(' ').collect();
                ensure!(
                    p.len() == 2,
                    "FX_BLUR stdDeviation `{v}` is not an x/y pair"
                );
                out.push((
                    Kind::BlurStd,
                    Val::F2([fnum(p[0], "stdDeviation")?, fnum(p[1], "stdDeviation")?]),
                ));
            }
        }
        op::FX_STD => {
            if let Some(v) = get("stdDeviation") {
                out.push((Kind::ShadowStd, Val::F(fnum(v, "stdDeviation")?)));
            }
        }
        op::FX_FLOOD_O => {
            if let Some(v) = get("flood-opacity") {
                out.push((Kind::FloodOpacity, Val::F(fnum(v, "flood-opacity")?)));
            }
        }
        op::FX_OFFSET => {
            out.push((
                Kind::ShadowOffset,
                Val::F2([
                    fnum(get("dx").unwrap_or("0"), "dx")?,
                    fnum(get("dy").unwrap_or("0"), "dy")?,
                ]),
            ));
        }
        other => bail!("the rt target cannot bake binding op {other}"),
    }
    Ok(out)
}

/// Dense integer-frame samples → change-point tracks. A gated-off frame
/// holds the previous value (the runtime would not have written); frames
/// before a channel's first live write emit no key (the static scene value
/// stands). Compression keeps an anchor key on the frame *before* each
/// change, so piecewise-linear interpolation between the kept keys
/// reproduces the dense bake exactly at every integer frame.
fn build_tracks(samples: &[SampleFrame], frames: &[f64]) -> Result<Vec<Track>> {
    let mut dense: BTreeMap<(u32, Kind), Vec<Option<Val>>> = BTreeMap::new();
    for (fi, frame) in samples.iter().enumerate() {
        for (el, opc, attrs) in frame {
            for (kind, val) in channel_writes(*opc, attrs)? {
                dense
                    .entry((*el, kind))
                    .or_insert_with(|| vec![None; samples.len()])[fi] = Some(val);
            }
        }
    }

    let mut per_slot: BTreeMap<u32, Vec<Channel>> = BTreeMap::new();
    for ((slot, kind), mut vals) in dense {
        // Gated-off frames hold.
        for i in 1..vals.len() {
            if vals[i].is_none() {
                vals[i] = vals[i - 1].clone();
            }
        }
        // Change points with pre-change anchors.
        let mut keys: Vec<(f32, Val)> = Vec::new();
        let mut last_kept: Option<usize> = None;
        for (i, v) in vals.iter().enumerate() {
            let Some(v) = v else { continue };
            let changed = match keys.last() {
                Some((_, prev)) => prev != v,
                None => true,
            };
            if changed {
                if let Some(lk) = last_kept
                    && lk != i - 1
                {
                    let anchor = vals[i - 1].clone().unwrap();
                    keys.push((frames[i - 1] as f32, anchor));
                }
                keys.push((frames[i] as f32, v.clone()));
                last_kept = Some(i);
            }
        }
        if keys.is_empty() {
            continue;
        }
        per_slot
            .entry(slot)
            .or_default()
            .push(channel_of(kind, keys));
    }

    Ok(per_slot
        .into_iter()
        .map(|(slot, channels)| Track { slot, channels })
        .collect())
}

fn channel_of(kind: Kind, keys: Vec<(f32, Val)>) -> Channel {
    let frames: Vec<f32> = keys.iter().map(|(f, _)| *f).collect();
    macro_rules! pull {
        ($variant:ident) => {
            Keys {
                frames,
                values: keys
                    .into_iter()
                    .map(|(_, v)| match v {
                        Val::$variant(x) => x,
                        other => unreachable!("kind/value mismatch: {other:?}"),
                    })
                    .collect(),
            }
        };
    }
    match kind {
        Kind::Matrix => Channel::Matrix(pull!(F6)),
        Kind::Opacity => Channel::Opacity(pull!(F)),
        Kind::Hidden => Channel::Hidden(pull!(F)),
        Kind::Path => Channel::Path(pull!(Path)),
        Kind::Rect => Channel::Rect(pull!(F6)),
        Kind::Ellipse => Channel::Ellipse(pull!(F4)),
        Kind::Fill => Channel::Fill(pull!(F4)),
        Kind::FillOpacity => Channel::FillOpacity(pull!(F)),
        Kind::Stroke => Channel::Stroke(pull!(F4)),
        Kind::StrokeOpacity => Channel::StrokeOpacity(pull!(F)),
        Kind::StrokeWidth => Channel::StrokeWidth(pull!(F)),
        Kind::Dash => Channel::Dash(pull!(Dash)),
        Kind::Gradient => Channel::Gradient(pull!(F4)),
        Kind::Stop => Channel::Stop(pull!(F4)),
        Kind::BlurStd => Channel::BlurStd(pull!(F2)),
        Kind::ShadowStd => Channel::ShadowStd(pull!(F)),
        Kind::FloodOpacity => Channel::FloodOpacity(pull!(F)),
        Kind::ShadowOffset => Channel::ShadowOffset(pull!(F2)),
    }
}

// ---------------------------------------------------------------------------
// The mandatory bbox pass.
// ---------------------------------------------------------------------------

/// Stamp a bbox on every group that forces an offscreen layer: the union of
/// its subtree's bounds across all sampled frames (the same `Player` the
/// device runs), padded one pixel. A layer-forcing group whose subtree never
/// draws keeps `bbox: None` — the rasterizer skips the layer entirely.
fn stamp_bboxes(anim: &mut Animation, frames: &[f64]) {
    // The same Player the device runs — its `animates_opacity` is the one
    // source of truth for "this group can dip below full opacity", so the
    // layer-forcing set here cannot drift from the rasterizer's.
    let mut player = Player::new(anim.clone());
    let forcing: Vec<usize> = anim
        .nodes
        .iter()
        .enumerate()
        .filter_map(|(i, n)| {
            let RtNode::Group(g) = n else { return None };
            let animated_opacity = g.slot.is_some_and(|s| player.animates_opacity(s));
            let needs = g.opacity < 1.0
                || animated_opacity
                || g.blend.is_some()
                || g.mask.is_some()
                || g.cf.is_some()
                || !g.fx.is_empty();
            needs.then_some(i)
        })
        .collect();
    if forcing.is_empty() {
        return;
    }

    let mut boxes: Vec<Option<bounds::Aabb>> = vec![None; anim.nodes.len()];
    let mut measure = |player: &Player| {
        for &i in &forcing {
            let RtNode::Group(g) = &player.anim.nodes[i] else {
                continue;
            };
            boxes[i] = bounds::union(boxes[i], bounds::group_inner_bounds(&player.anim, g));
        }
    };
    // The baked frame-`ip` state first, then every sampled frame.
    measure(&player);
    for &f in frames {
        player.apply(f as f32);
        measure(&player);
    }
    for &i in &forcing {
        if let RtNode::Group(g) = &mut anim.nodes[i] {
            g.bbox = boxes[i].map(|b| bounds::pad(b, 1.0, 1.0));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parsers_read_the_compilers_own_grammar() {
        assert_eq!(
            transform6("matrix(.5,0,0,.5,10,-2.5)").unwrap(),
            [0.5, 0.0, 0.0, 0.5, 10.0, -2.5]
        );
        assert_eq!(
            transform6("translate(4,-8)").unwrap(),
            [1.0, 0.0, 0.0, 1.0, 4.0, -8.0]
        );
        assert!(transform6("rotate(45)").is_err());

        let p = parse_path("M0 0L10.5-.25C1 2 3 4 5 6Z").unwrap();
        assert_eq!(p.verbs, vec![VERB_MOVE, VERB_LINE, VERB_CUBIC, VERB_CLOSE]);
        assert_eq!(
            p.points,
            vec![0.0, 0.0, 10.5, -0.25, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0]
        );

        assert_eq!(color4("#fff").unwrap(), [1.0, 1.0, 1.0, 1.0]);
        assert_eq!(color4("rgb(255,0,0)").unwrap(), [1.0, 0.0, 0.0, 1.0]);
        let c = color4("rgba(0,255,0,0.5)").unwrap();
        assert_eq!(c[1], 1.0);
        assert_eq!(c[3], 0.5);
    }

    /// The one runnable check for track compression: a hold then a ramp
    /// compresses to first key + pre-change anchor + change points, and
    /// linear interpolation reproduces every dense sample.
    #[test]
    fn tracks_compress_to_change_points_with_anchors() {
        let frames: Vec<f64> = (0..=4).map(|f| f as f64).collect();
        let sample = |o: f64| -> SampleFrame {
            vec![(7, op::OPACITY, vec![("opacity".into(), o.to_string())])]
        };
        // 1, 1, 1, 0.5, 0 — constant, then a ramp.
        let samples = vec![
            sample(1.0),
            sample(1.0),
            sample(1.0),
            sample(0.5),
            sample(0.0),
        ];
        let tracks = build_tracks(&samples, &frames).unwrap();
        assert_eq!(tracks.len(), 1);
        assert_eq!(tracks[0].slot, 7);
        let Channel::Opacity(k) = &tracks[0].channels[0] else {
            panic!("opacity channel");
        };
        // First key, anchor at 2, changes at 3 and 4.
        assert_eq!(k.frames, vec![0.0, 2.0, 3.0, 4.0]);
        assert_eq!(k.values, vec![1.0, 1.0, 0.5, 0.0]);
        assert_eq!(k.at(1.0, false), Some(1.0));
        assert_eq!(k.at(2.5, false), Some(0.75));
    }
}
