// Generated by ulottie — reanimated-aot target (react-native-svg + react-native-reanimated).
// Deliberately unminified: Metro's reanimated plugin reads the 'worklet' directives
// before its own minifier runs; a minifier here could strip them.
// caps: TRANSFORM | KEYFRAMES | EASING | SPATIAL

// runtime symbols: fmt, r5, r2, dec, H_FR, H_IP, H_OP, H_EASINGS, H_TIMELINES, H_GATES, H_PROGRAM, H_REMAPS, INV, P10, put, mtx, open, EASE, SP_SEG, spBuild, spSample, spSeg, T_SCALAR, T_VECTOR, T_EXPR, F_EASE, F_HOLD, F_SPATIAL, pseg, pease, pv, pvv, pslice, xv, xvv, bTransform, oTransform, rnNumeric, rnProp, rnMatrix, mountRn
// Shared number → string formatting for attribute values.
//
// Precision is chosen per role, because the error budgets differ by orders of
// magnitude: a matrix's linear part multiplies every coordinate beneath it
// (error ~ quantum * extent), while a translation or a path coordinate
// contributes absolute error only.
//
// Do not "optimize" this by assembling the digits from the rounded integer
// instead of handing a float to V8's dtoa. That version was written, tested
// byte-identical over 7434 real interpolated values, and measured 2.36× faster
// in isolation — and it was still reverted:
//
//   • A CDP sampling profile puts `fmt` at 3.0% of frame time on `lottie_logo_1`
//     (the most format-heavy fixture) and below the top twelve on `ripple`, so
//     2.36× caps out at a 1.7% win.
//   • End-to-end frame time, alternating four runs, showed no effect outside
//     noise.
//   • It cost +118 B gzipped on `lottie_logo_1`, +2.2% of the whole module.
//
// The profile says the time is in path-string assembly (`pathD` + `pdPair` +
// `pdSep`, 15% together) and in `setAttribute` and `evalExpr` — not here.
//
// A fraction keeps its leading zero even though SVG parses ".5" fine. The
// react-native-svg target shares this helper, and its JS prop parser rejects
// ".47" ("not a valid number or percentage string"), leaves the prop a String,
// and Fabric's generated RNSVGGroupManagerDelegate.setProperty then throws
// ClassCastException: String cannot be cast to Double — an app-killing crash on
// Android, observed on a Pixel 8 with the `mixed16` fixture.
function fmt(x, scale) { 'worklet';
  return '' + Math.round(x * scale) / scale;
}

/** Coordinates and plain attribute values: 3 decimals. */
function r5(x) { 'worklet';
  return fmt(x, 1e5);
}

/** Matrix translation: 2 decimals. */
function r2(x) { 'worklet';
  return fmt(x, 100);
}
// The payload decoder: one base36 VLQ string → one `Int32Array`.
//
// Runs once per mount. Everything downstream reads properties straight out of
// the array by offset, so this is the only place the wire format is touched.

/**
 * Decode the stream.
 *
 * Each character carries four data bits plus a continuation bit, written with
 * base36 digits — `0`–`9` are 0–15 and part of `a`–`v` the rest, which is what
 * `parseInt(c, 36)` would give. Doing the digit arithmetic on the char code
 * directly avoids a `parseInt` call per character, and there are a lot of
 * characters.
 *
 * Values are zigzagged, so a small negative costs one character just like a
 * small positive.
 */
function dec(s) { 'worklet';
  const n = s.length;
  // Every integer takes at least one character, so the string length is a
  // safe upper bound and the array is allocated exactly once.
  const out = new Int32Array(n);
  let k = 0, acc = 0, sh = 0;
  for (let i = 0; i < n; i++) {
    const c = s.charCodeAt(i);
    // '0'..'9' are 48..57, 'a'..'v' are 97..118.
    const d = c < 58 ? c - 48 : c - 87;
    acc |= (d & 15) << sh;
    if (d & 16) {
      sh += 4;
    } else {
      // Un-zigzag. `acc` is a full 32-bit pattern by now, so the shift has to
      // be unsigned or the sign bit would smear.
      out[k++] = (acc >>> 1) ^ -(acc & 1);
      acc = 0;
      sh = 0;
    }
  }
  return out.subarray(0, k);
}
// Where things live in the integer stream.
//
// The single source of truth on this side is `scene/flat.rs`; these must stay
// in step with it.
//
// One constant per slot rather than one table: a minifier will fold
// `H_PROGRAM` to `8` but cannot fold `head.PROGRAM`, so the table shipped whole
// in every self-contained module. Separate bindings also shake individually, so
// an animation without records carries none of the record bits.

// Fixed slots at the head of the stream. A zero means the section is absent.
const H_FR = 1;
const H_IP = 2;
const H_OP = 3;
const H_EASINGS = 5;
const H_TIMELINES = 6;
const H_GATES = 7;
// `[count, batchOffset × count]` — the document's own bindings, grouped by op.
const H_PROGRAM = 8;
const H_REMAPS = 12;

// One precomp asset: `[template, program, timelines, records]`.
// Descaling factors for the wire's per-column shifts.
//
// A column carries the smallest power of ten that represents it exactly, so
// reading one back is a single multiply by its reciprocal. Shared because the
// property reader, the clock table and the gate table all need it.

const INV = [1, 0.1, 0.01, 0.001];

// The other direction. A keyframe time column stays in its own scale and the
// frame is scaled up to meet it, so the hot comparisons are integer against
// integer and no time is ever descaled.
const P10 = [1, 10, 100, 1000];
// The react-native-svg write point — the RN counterpart of set.js's `put`.
//
// An element handle is not a DOM node here. `mountRn` hands the ops an array
// of plain records `{ i, p, d, q }`: the element's slot index in the emitted
// `tree`, its current dynamic props, a dirty flag, and the shared dirty
// queue. `put` keeps set.js's contract — write only on change — and adds the
// RN half: the SVG attribute name maps to the camelCased react-native-svg
// prop, a `transform` string becomes the ColumnMajorTransformMatrix array
// (a transform *string* throws on Fabric iOS: "JSON value of type NSString
// cannot be converted to a CATransform3D"), a prop the native side reads as a
// `Double` is handed a number (see `rnNumeric`), and a changed element lands
// in the dirty queue once per flush so the consumer only touches what moved.

function put(el, name, v, w, i) { 'worklet';
  if (v !== w[i]) {
    w[i] = v;
    const p = rnProp(name);
    el.p[p] = name === 'transform' ? rnMatrix(v) : rnNumeric(p) ? +v : v;
    if (!el.d) { el.d = 1; el.q.push(el); }
  }
}

/**
 * Whether react-native-svg's native side reads this prop as a raw `Double`.
 *
 * These writes bypass rn-svg's JS prop extraction — the consumer pushes `el.p`
 * straight into Fabric — so whatever the op produced is what the generated
 * `RNSVG*ManagerDelegate.setProperty` casts. For these four the generated
 * Java is `((Double) value).floatValue()`, and a `String` there throws
 * `ClassCastException: String cannot be cast to Double`, which kills the app
 * (observed on a Pixel 8 with the `mixed16` fixture; iOS tolerates it).
 *
 * Every other prop the ops write is either a `String` on the native side
 * (`d`, `display`) or goes through `DynamicFromObject`, which parses a
 * numeric string via `SVGLength` — `x`/`y`/`width`/`height`/`rx`/`ry`/
 * `cx`/`cy`/`strokeWidth`/`strokeDasharray`/`fill`/`stroke`. Those keep the
 * op's string, so the shared change detection above still compares the exact
 * bytes the web runtime would have written.
 *
 * The number is `+v` on a value the op already rounded (`r`, `r2`), so this
 * only drops the stringification — it does not change the value.
 */
// The layer matrix.
//
// `translate(p) rotate(r) scale(s) translate(-a)` is emitted as a single
// `matrix()` — one attribute, one parse, and the same CTM the browser would
// have derived from the transform list anyway. It is also the only form that
// can express skew, flattened 3D and auto-orient later on.
//
// One implementation, three callers: the transform op, the layer-record op, and
// the single-binding form generated code links against.


function mtx(p, a, s, rot) { 'worklet';
  const th = rot * Math.PI / 180;
  const cs = Math.cos(th), sn = Math.sin(th);
  const sx = s[0] / 100, sy = s[1] / 100;
  const m0 = cs * sx, m1 = sn * sx, m2 = -sn * sy, m3 = cs * sy;
  return 'matrix(' + r5(m0) + ',' + r5(m1) + ',' + r5(m2) + ',' + r5(m3) + ','
    + r2(p[0] - (m0 * a[0] + m2 * a[1])) + ','
    + r2(p[1] - (m1 * a[0] + m3 * a[1])) + ')';
}

/**
 * The layer matrix with lottie-web's `skewFromAxis(-sk, sa)` folded in
 * between scale and rotation. Separate from `mtx` so the skewless majority
 * never pays for the factor.
 */
// Opening one op's batch.
//
// The compiler groups every binding by op and writes each group as a
// struct-of-arrays batch:
//
// ```text
// [count, flags,
//  el…     count, first differences
//  gate…   count, when flags & 1
//  slot…   count, when flags & 2
//  arg0…   count
//  …
//  argK…   count]
// ```
//
// An op comes in two halves, and neither is a callback. `bXxx` binds a batch
// once and hands back a plain state record; `oXxx(x, s)` is the frame, called
// directly. The module names both, because which op a binding is was never
// anything but a compile-time fact — so nothing here closes over anything, and
// the only closure left in an animation is the one `player` is handed.
//
// Gates and clocks are materialized as dense columns even when the wire omits
// them, so the loop reads `ON[G[i]]` and `T[L[i]]` unconditionally — gate 0 is
// pinned on and slot 0 is the composition clock. A present-or-absent branch per
// binding per frame buys nothing against two loads from a small typed array.

/**
 * Resolve a batch's columns: elements, gate, clock, and `k` argument columns.
 *
 * `eb`/`sb`/`ps` position the batch within an instantiation — the element base,
 * the clock base, and the clock the instance itself runs on. All three are zero
 * for the document's own bindings, which is what lets one code path serve both.
 */
function open(x, base, eb, sb, ps, k) { 'worklet';
  const S = x.S;
  const n = S[base];
  const flags = S[base + 1];
  let c = base + 2;
  // Element indices ship as first differences: consecutive bindings sit close
  // together in document order, and an instanced asset's column then replays at
  // any base.
  const E = new Array(n);
  for (let i = 0, e = 0; i < n; i++) E[i] = x.els[eb + (e += S[c + i])];
  c += n;
  const G = new Int32Array(n);
  if (flags & 1) {
    for (let i = 0; i < n; i++) G[i] = S[c + i];
    c += n;
  }
  const L = new Int32Array(n);
  if (flags & 2) {
    // A local slot of zero is the instance's own clock, not the composition's.
    for (let i = 0; i < n; i++) { const v = S[c + i]; L[i] = v ? sb + v : ps; }
    c += n;
  } else if (ps) {
    L.fill(ps);
  }
  // Arguments are copied out of the stream rather than indexed through it, so
  // the frame loop reads a dense typed array it can hold in a register.
  const A = new Array(k);
  for (let j = 0; j < k; j++, c += n) {
    const col = new Int32Array(n);
    for (let i = 0; i < n; i++) col[i] = S[c + i];
    A[j] = col;
  }
  return { n, E, G, L, A };
}

/** Undo a column's first differences, in place. */
// Cubic-bezier timing solve.
//
// Only bundled when the animation actually has a non-linear easing handle —
// the compiler folds every linear (and linear-equivalent) segment to index 0
// and the interpolator skips this entirely for those.

/**
 * Solve `x(s) = u` for the bezier through (0,0), (x1,y1), (x2,y2), (1,1),
 * then return `y(s)`. Newton–Raphson seeded at `u`; eight iterations is well
 * past convergence for the handle ranges Lottie produces.
 *
 * @param {ArrayLike<number>} e `[x1, y1, x2, y2]`
 */
function EASE(e, u) { 'worklet';
  const x1 = e[0], y1 = e[1], x2 = e[2], y2 = e[3];
  let s = u;
  for (let i = 0; i < 8; i++) {
    const m = 1 - s;
    const x = 3 * m * m * s * x1 + 3 * m * s * s * x2 + s * s * s - u;
    if (x > -1e-6 && x < 1e-6) break;
    const dx = 3 * m * m * x1 + 6 * m * s * (x2 - x1) + 3 * s * s * (1 - x2);
    if (dx > -1e-6 && dx < 1e-6) break;
    s -= x / dx;
    s = s < 0 ? 0 : s > 1 ? 1 : s;
  }
  const m = 1 - s;
  return 3 * m * m * s * y1 + 3 * m * s * s * y2 + s * s * s;
}
// Spatial bezier motion paths.
//
// A Lottie position keyframe can carry in/out tangents that bend the path
// between two values, and the result is parameterized by arc length so the
// motion is evenly paced. Both endpoints and both tangents are constants for a
// given segment, so the sample table is built once and reused.
//
// The split is deliberate: `spBuild` takes plain numbers and runs once per
// segment, `spSample` runs per frame and touches nothing but the table it is
// given. That keeps it usable from both callers — the interpreter, which has
// its values in an `Int32Array` and materializes four small arrays on a
// segment's first visit, and generated code, which knows the endpoints at
// compile time and can build the table when the module loads.

const SP_SEG = 200;

/**
 * Arc-length sample table for one segment.
 *
 * @param {ArrayLike<number>} a start value, `d` components
 * @param {ArrayLike<number>} b end value
 * @param {ArrayLike<number>} to out-tangent, relative to `a`
 * @param {ArrayLike<number>} ti in-tangent, relative to `b`
 */
function spBuild(a, b, to, ti, d) { 'worklet';
  const pts = new Float64Array((SP_SEG + 1) * d);
  const cum = new Float64Array(SP_SEG + 1);
  let total = 0;
  for (let k = 0; k <= SP_SEG; k++) {
    const u = k / SP_SEG;
    const m = 1 - u;
    const c0 = m * m * m, c1 = 3 * m * m * u, c2 = 3 * m * u * u, c3 = u * u * u;
    const base = k * d;
    let dist = 0;
    for (let j = 0; j < d; j++) {
      const p0 = a[j];
      const p3 = b[j];
      const p1 = p0 + to[j];
      const p2 = p3 + ti[j];
      const x = c0 * p0 + c1 * p1 + c2 * p2 + c3 * p3;
      pts[base + j] = x;
      if (k) {
        const dd = x - pts[base - d + j];
        dist += dd * dd;
      }
    }
    if (k) total += Math.sqrt(dist);
    cum[k] = total;
  }
  return { pts, cum, total, d };
}

/** Sample a built table at `u`, by arc length, into `out`. */
function spSample(tab, u, out) { 'worklet';
  const { pts, cum, total, d } = tab;
  if (total === 0) {
    for (let j = 0; j < d; j++) out[j] = pts[j];
    return out;
  }
  const target = u * total;
  let lo = 0, hi = SP_SEG;
  while (hi - lo > 1) {
    const m = (lo + hi) >> 1;
    if (cum[m] <= target) lo = m; else hi = m;
  }
  const span = cum[hi] - cum[lo];
  const f = span > 0 ? (target - cum[lo]) / span : 0;
  const a = lo * d, b = hi * d;
  for (let j = 0; j < d; j++) {
    const x = pts[a + j];
    out[j] = x + (pts[b + j] - x) * f;
  }
  return out;
}

/**
 * Build a segment's table straight from the payload stream.
 *
 * Lives here rather than in the interpolator so it is gated with the rest of
 * the motion-path code: inline in `keyframed`, these four little arrays cost
 * every keyframed animation ~135 bytes for a branch it never takes.
 */
function spSeg(S, ai, bi, so, si, d, iv) { 'worklet';
  const a = [], b = [], to = [], ti = [];
  for (let k = 0; k < d; k++) {
    a.push(S[ai + k] * iv);
    b.push(S[bi + k] * iv);
    to.push(S[so + k] * iv);
    ti.push(S[si + k] * iv);
  }
  return spBuild(a, b, to, ti, d);
}
// Property evaluation, read straight off the stream.
//
// A property is a run of integers at an offset in the single `Int32Array` the
// payload decodes to. These functions read it at the frame they are asked for:
// there is no closure per property, no object, and no copy of the keyframe
// data. The only state a property needs is its segment cursor, which lives in
// an `Int32Array` the caller indexes by binding.
//
// **One function per result shape, not one closure per property shape.** That
// is what makes an op's frame loop monomorphic: `pv` is a single call target,
// so V8 can inline it into the loop, where twelve closure shapes reached
// through one `U[i](f)` could only ever be a generic call.
//
// The three shapes are the three things a binding can consume — a number, a
// vector written into the caller's scratch, and a path object.


/// Property tags, in the low three bits of a property's first word. Kept in
/// sync with `scene/flat.rs`. `T_ANIM` is what the readers fall through to.
const T_SCALAR = 0;
const T_VECTOR = 1;
const T_EXPR = 4;

/// An `Anim`'s value kind, in bits 11–12. Path keyframes hold offsets to pooled
/// path properties where the others hold numbers.
const F_EASE = 1;
const F_HOLD = 2;
const F_SPATIAL = 4;

/**
 * The segment containing `ft`, remembered per binding.
 *
 * Playback is overwhelmingly monotonic, so checking the cursor's own segment
 * first turns the search into two comparisons. The cursor is only ever a hint,
 * which is why two bindings sharing a hash-consed property may share one.
 */
function pseg(S, t, n, ft, c, i) { 'worklet';
  const k = c[i];
  if (ft >= S[t + k] && ft <= S[t + k + 1]) return k;
  let lo = 0, hi = n - 1;
  while (hi - lo > 1) {
    const m = (lo + hi) >> 1;
    if (S[t + m] <= ft) lo = m; else hi = m;
  }
  c[i] = lo;
  return lo;
}

/** Segment easing. Handle 0 is linear and never reaches the solver. */
function pease(z, S, ez, k, u) { 'worklet';
  if (!ez) return u;
  const h = S[ez + k];
  return h === 0 ? u : EASE(z[h], u);
}

// The optional columns follow the values in a fixed order — easing, holds,
// then the two spatial tangent columns — so each reader walks a running offset
// through the ones it needs. Three functions that each recomputed the whole
// staircase from the header meant the shared prefix was derived two or three
// times per property per frame, and adding a column meant editing all three
// in step.

/**
 * A scalar property at frame `f`.
 *
 * `off` of zero means the property is absent, which is unambiguous because
 * offset zero is the header and no property can live there.
 */
function pv(x, off, f, c, i) { 'worklet';
  if (!off) return 0;
  const S = x.S;
  const head = S[off];
  const tag = head & 7;
  if (tag === T_SCALAR) return S[off + 1] * INV[(head >> 3) & 3];
  // A one-component vector in a scalar slot. The planner classifies by the
  // dimension it asked for, not by what Lottie stored, so a scalar property
  // written as `[x]` arrives here. The closure form this replaced handed the
  // array back and let JS coerce it; reading component zero is the same value
  // and does not depend on that coercion.
  if (tag === T_VECTOR) return S[off + 2] * INV[(head >> 3) & 3];
  // An expression with no engine to run it is its own value source. With an
  // engine, the whole column is resolved ahead of the loop and never lands here.
  if (tag === T_EXPR) return pv(x, S[off + 2], f, c, i);
  const n = S[off + 1];
  const iv = INV[(head >> 5) & 3];
  const t = off + 2;
  const v = t + n;
  const ft = f * P10[(head >> 3) & 3];
  if (ft <= S[t]) return S[v] * iv;
  if (ft >= S[t + n - 1]) return S[v + n - 1] * iv;
  const k = pseg(S, t, n, ft, c, i);
  const span = S[t + k + 1] - S[t + k];
  if (span === 0) return S[v + k + 1] * iv;
  const fl = (head >> 7) & 7;
  let nx = v + n;
  const ez = fl & F_EASE ? nx : 0;
  if (ez) nx += n - 1;
  if (fl & F_HOLD && S[nx + k]) return S[v + k] * iv;
  const u = pease(x.z, S, ez, k, (ft - S[t + k]) / span);
  const a = S[v + k];
  const b = S[v + k + 1];
  return (a + (b - a) * u) * iv;
}

/**
 * A vector property at frame `f`, written into `out`.
 *
 * `out` is the column's scratch, so a steady-state frame allocates nothing. One
 * per column is enough because a binding never holds two values from the same
 * column at once — except for paint, where `css` asks the buffer itself whether
 * the colour carries an alpha channel and so needs one sized per binding. See
 * [`vscratch`].
 */
function pvv(x, off, f, c, i, out) { 'worklet';
  const S = x.S;
  if (!off) {
    for (let k = 0; k < out.length; k++) out[k] = 0;
    return out;
  }
  const head = S[off];
  const tag = head & 7;
  if (tag === T_VECTOR) {
    const iv = INV[(head >> 3) & 3];
    for (let k = 0, m = S[off + 1]; k < m; k++) out[k] = S[off + 2 + k] * iv;
    return out;
  }
  if (tag === T_SCALAR) {
    out[0] = S[off + 1] * INV[(head >> 3) & 3];
    return out;
  }
  if (tag === T_EXPR) return pvv(x, S[off + 2], f, c, i, out);
  const n = S[off + 1];
  const d = ((head >> 13) & 3) + 1;
  const iv = INV[(head >> 5) & 3];
  const t = off + 2;
  const v = t + n;
  const vlen = n * d;
  const ft = f * P10[(head >> 3) & 3];
  if (ft <= S[t]) return pslice(S, v, d, iv, out);
  if (ft >= S[t + n - 1]) return pslice(S, v + (n - 1) * d, d, iv, out);
  const k = pseg(S, t, n, ft, c, i);
  const span = S[t + k + 1] - S[t + k];
  if (span === 0) return pslice(S, v + (k + 1) * d, d, iv, out);
  const fl = (head >> 7) & 7;
  let nx = v + vlen;
  const ez = fl & F_EASE ? nx : 0;
  if (ez) nx += n - 1;
  if (fl & F_HOLD) {
    if (S[nx + k]) return pslice(S, v + k * d, d, iv, out);
    nx += n - 1;
  }
  const u = pease(x.z, S, ez, k, (ft - S[t + k]) / span);
  const ai = v + k * d;
  const bi = v + (k + 1) * d;
  if (fl & F_SPATIAL) {
    const to = nx;
    // Both tangent columns are per *segment*, so each is `(n-1)*d` — one
    // keyframe shorter than the values. Reading `ti` at `n*d` puts every
    // in-tangent one keyframe late, which bends a motion path by a couple of
    // percent: visible to the geometry check, invisible to the pixel diff.
    const so = to + k * d, si = to + (n - 1) * d + k * d;
    if (S[so] || S[so + 1] || S[si] || S[si + 1]) {
      // Arc-length tables are built on a segment's first visit and kept. Keyed
      // by the tangent column's own offset, which names one (property,
      // segment) uniquely — so two bindings sharing a hash-consed property
      // share the table, which depends on nothing else.
      const sp = x.sp || (x.sp = new Map());
      let tab = sp.get(so);
      if (tab === undefined) sp.set(so, tab = spSeg(S, ai, bi, so, si, d, iv));
      return spSample(tab, u, out);
    }
  }
  for (let q = 0; q < d; q++) {
    const a = S[ai + q];
    out[q] = (a + (S[bi + q] - a) * u) * iv;
  }
  return out;
}

/** One keyframe's components, descaled into `out`. */
function pslice(S, base, d, iv, out) { 'worklet';
  for (let k = 0; k < d; k++) out[k] = S[base + k] * iv;
  return out;
}

/**
 * A geometry property at frame `f`.
 *
 * Path objects are the one place where an object is the working representation
 * rather than the wire one — `pathD`, `trimTable` and `lerpPath` all walk one —
 * so they are materialized once into `m`, the caller's per-binding cache, and
 * never again.
 */
function xv(x, X, C, i, f, c) { 'worklet';
  return X && X[i] ? X[i](f) : pv(x, C[i], f, c, i);
}

/** The same for a vector column, into the column's scratch. */
function xvv(x, X, C, i, f, c, out) { 'worklet';
  return X && X[i] ? X[i](f) : pvv(x, C[i], f, c, i, out);
}

/**
 * One scratch buffer per binding in a vector column, sized to that binding's
 * own property.
 *
 * Sizing it per property rather than per column is what lets `css` keep asking
 * `c.length > 3` for an alpha channel: a shared four-slot buffer would answer
 * yes for a three-component colour and paint it with whatever the previous
 * binding left behind.
 */
// Full transform: position, anchor, scale and rotation may each vary.


function bTransform(x, base, eb, sb, ps, at) { 'worklet';
  const b = open(x, base, eb, sb, ps, 4);
  const n = b.n;
  return {
    n, E: b.E, G: b.G, L: b.L,
    P: b.A[0], A: b.A[1], K: b.A[2], R: b.A[3],
    XP: x.expr ? xcol(x, b.A[0], n, at) : null,
    XA: x.expr ? xcol(x, b.A[1], n, at) : null,
    XK: x.expr ? xcol(x, b.A[2], n, at) : null,
    XR: x.expr ? xcol(x, b.A[3], n, at) : null,
    CP: new Int32Array(n), CA: new Int32Array(n),
    CK: new Int32Array(n), CR: new Int32Array(n),
    // One scratch per column, not per binding: a binding never holds two values
    // from the same column at once, and every consumer here reads only the
    // components its own property has.
    VP: [0, 0, 0], VA: [0, 0, 0], VK: [0, 0, 0],
    W: new Array(n),
  };
}

function oTransform(x, s) { 'worklet';
  // Every field is hoisted before the loop, not read inside it. This is the
  // closure's capture list written out: the loop body must see locals, or each
  // iteration pays a property load per column.
  const n = s.n, E = s.E, G = s.G, L = s.L, W = s.W, T = x.T, ON = x.ON;
  const P = s.P, A = s.A, K = s.K, R = s.R;
  const XP = s.XP, XA = s.XA, XK = s.XK, XR = s.XR;
  const CP = s.CP, CA = s.CA, CK = s.CK, CR = s.CR;
  const VP = s.VP, VA = s.VA, VK = s.VK;
  for (let i = 0; i < n; i++) {
    if (!ON[G[i]]) continue;
    const t = T[L[i]];
    put(E[i], 'transform', mtx(
      xvv(x, XP, P, i, t, CP, VP),
      xvv(x, XA, A, i, t, CA, VA),
      xvv(x, XK, K, i, t, CK, VK),
      xv(x, XR, R, i, t, CR)), W, i);
  }
}

// --- transform with a live skew --------------------------------------------
//
// Its own op, not a branch in `oTransform`: the skewless majority must not
// read two extra columns per binding per frame.

function rnNumeric(p) { 'worklet';
  return p === 'opacity' || p === 'fillOpacity' || p === 'strokeOpacity'
    || p === 'strokeDashoffset';
}

/**
 * Direct prop write for the few loops that write outside `put`'s
 * one-attribute guard (the display gates, the rect radius pair). The caller
 * has already change-detected; this only records the prop and marks the
 * element dirty.
 */
function rnProp(name) { 'worklet';
  if (name.indexOf('-') < 0) return name;
  let out = '';
  for (let i = 0; i < name.length; i++) {
    const c = name[i];
    if (c === '-') { i++; out += name[i].toUpperCase(); } else out += c;
  }
  return out;
}

/**
 * `matrix(a,b,c,d,e,f)` / `translate(x,y)` → `[a, b, c, d, e, f]`.
 *
 * The ops keep producing the transform *string* — its identity is what the
 * change detection above compares, so the parse runs only on actual changes,
 * and the string builders (`mtx`, the translate prefix) stay shared with the
 * web runtime byte for byte. Those two spellings are the only ones the
 * compiler ever writes (see `scene::svg::matrix`).
 */
function rnMatrix(v) { 'worklet';
  const a = v.slice(v.indexOf('(') + 1, v.length - 1).split(',');
  return v.charCodeAt(0) === 116
    ? [1, 0, 0, 1, +a[0], +a[1]]
    : [+a[0], +a[1], +a[2], +a[3], +a[4], +a[5]];
}
// μLottie RN runtime — mount, without a document.
//
// The web `mount` parses markup, adopts DOM nodes and hands the ops
// `svg.querySelectorAll('*')`. Here the compiler already emitted the element
// tree as a static descriptor (`tree` in the generated module), so mounting
// is pure data: decode the stream, widen the easing/clock/gate tables exactly
// as core.js does, and hand the program an `els` array of plain prop-store
// handles in the same document order `querySelectorAll` would have produced
// (root `<svg>` excluded — it stays static, animated writes go to inner
// elements only).
//
//   D — the payload, one integer stream;
//   P/A — the emitted bind/apply program pair;
//   N — the element count (handles are dense; most never receive a write);
//   ext.p — the string pool; ext.r — the time-remap resolver, when used.
//
// `apply(f)` runs one frame: clocks, gates, one program pass. Changed
// elements collect in `dirty`; the consumer drains it (clearing each `d`)
// and pushes `p` into the matching react-native-svg elements.


function mountRn(D, P, A, N, ext) { 'worklet';
  ext = ext || {};
  // The immutable half — the payload decode, the widened easing handles and
  // the arc-length table cache — is identical for every instance of one
  // module, so it is built once per JS runtime and shared; init() then only
  // creates per-instance state (clocks, gates, element handles, bind state).
  // The cache must live on `globalThis`: worklet closures capture module
  // scope BY COPY at definition time, so a module-level `let` mutated on the
  // UI runtime would not persist across init() calls. The payload string is
  // its own cache key — it names the animation content exactly, and every
  // call passes the same captured string object, so the engine's cached
  // string hash makes the lookup cheap.
  const g = globalThis;
  const cache = g.__ulottie || (g.__ulottie = {});
  let sh = cache[D];
  if (!sh) {
    const dS = dec(D);

    // Easing handles, widened once — same as core.js.
    const ez = dS[H_EASINGS];
    const easings = [];
    if (ez) {
      for (let i = 0, n = dS[ez]; i < n; i++) {
        const at = ez + 1 + i * 4;
        easings.push([dS[at] / 1000, dS[at + 1] / 1000, dS[at + 2] / 1000, dS[at + 3] / 1000]);
      }
    }

    // `sp` holds spatial arc-length tables, keyed by tangent-column offset —
    // deterministic from the stream alone (see `pvv`), so instances share it.
    sh = cache[D] = { S: dS, z: easings, sp: new Map() };
  }
  const S = sh.S;
  const str = ext.p || [];

  const fr = S[H_FR] / 1000;
  const ip = S[H_IP] / 1000;
  const op = S[H_OP] / 1000;

  // Precomp clocks — see core.js for the row layout.
  const tl = S[H_TIMELINES];
  const nTl = tl ? S[tl] : 0;
  const tScale = nTl ? INV[S[tl + 1]] : 1;
  const tRows = tl + 2;
  const T = new Float64Array(nTl + 1);

  // Visibility gates — gate 0 pinned on, as on the web.
  const gt = S[H_GATES];
  const nGates = gt ? S[gt] : 0;
  const gScale = nGates ? INV[S[gt + 1]] : 1;
  const gRows = gt + 2;
  const ON = new Uint8Array(nGates + 1);
  ON[0] = 1;

  // Element handles: slot index, dynamic props, dirty flag, shared queue.
  // `x.els[i]` replaces the web's NodeList — same indexing, plain records.
  const dirty = [];
  const els = new Array(N);
  for (let i = 0; i < N; i++) els[i] = { i, p: {}, d: 0, q: dirty };

  const ctx = {
    S, str, els, z: sh.z,
    fr, frame: 0, T, ON, sp: sh.sp, expr: null, y: null,
  };

  // Time remap — the column is parallel to the timeline table.
  const rmc = S[H_REMAPS];
  const rm = rmc && ext.r
    ? Array.from({ length: S[rmc] }, (_, i) => (S[rmc + 1 + i] ? ext.r(S[rmc + 1 + i], ctx) : 0))
    : null;

  // One program: precomp instancing is off in this target, so every binding
  // lives in the document program and there is no uses/assets table to walk.
  const prog = S[H_PROGRAM];
  const st = prog ? P(ctx, S.subarray(prog + 1, prog + 1 + S[prog]), 0, 0, 0, 0) : null;

  function apply(f) {
    ctx.frame = f;
    T[0] = f;
    for (let i = 0; i < nTl; i++) {
      const e = tRows + i * 5;
      const remap = rm && rm[i];
      if (remap) {
        // Lottie stores the remap in seconds; the timeline is in frames.
        T[i + 1] = remap(T[S[e]]) * fr;
        continue;
      }
      T[i + 1] = (T[S[e]] - S[e + 1] * tScale) / (S[e + 2] / 1000);
    }
    for (let i = 0; i < nGates; i++) {
      const g = gRows + i * 2;
      ON[i + 1] = f >= S[g] * gScale && f < S[g + 1] * gScale ? 1 : 0;
    }
    if (st) A(ctx, st);
  }

  return { els, dirty, apply, fr, ip, op };
}
function P0(x, B, e, l, q, a) { 'worklet'; return [bTransform(x, B[0], e, l, q, a)]; }
function A0(x, S) { 'worklet'; oTransform(x, S[0]); }

const D = "0gmqe0gpst10q100qh10000c00gt7gt7qp200gt7gp70kn4gt7gt70mj5gt7qp20mj5gt7uk10mj5gt7msl5e0k1o2s3g5k6o7sgopg1inngt1sgopg1ihlp8sgopg1inngt1sgopg1ihlp8sgopg1inngt1sgopg1ihlp8sgopg1inngt12426260lmom3000000000000000000000lmom3i34upvu3spsk8mgh5i1k1i2q2u3s4k5k6i7q7g5g5o3m6g5g5g5g5o3m6g5g5g5g5o3m6g5g588888a8800204s4mbubog12sg1";

export const tree =
{ type: 'Svg', staticProps: { viewBox: '0 0 1080 1080', width: '100%', height: '100%', preserveAspectRatio: 'xMidYMid meet' }, children: [
  { type: 'Defs', staticProps: {  }, children: [
    { type: 'ClipPath', staticProps: { id: 'vp0' }, children: [
      { type: 'Rect', staticProps: { width: '1080', height: '1080' } }
    ] }
  ] },
  { type: 'G', staticProps: { clipPath: 'url(#vp0)' }, children: [
    { type: 'Rect', staticProps: { width: '1080', height: '1080', fill: '#ffffff' } },
    { type: 'G', slot: 2, staticProps: { transform: [0.4, 0, 0, 0.4, 492.16, 842.45] }, children: [
      { type: 'G', staticProps: { transform: [1, 0, 0, 1, 128.98, 64.97] }, children: [
        { type: 'Rect', staticProps: { x: '-206.975', y: '-206.975', width: '413.95', height: '413.95', rx: '206.975', ry: '206.975', fill: '#63d3bf' } }
      ] }
    ] }
  ] }
] };

export const meta = { fr: 30, ip: 0, op: 61, width: 1080, height: 1080 };
export const init = () => { 'worklet'; return mountRn(D, P0, A0, 5); };
