// Generated by ulottie — rt target (native tiny-skia rasterizer via ulottie-rt).
// The scene ships as RTDL: a binary display list + numeric keyframe tracks,
// decoded and played natively; per-frame JS work is one renderFrame() call.
// caps: none

export const rtdl = 'UlRETAEAAAAARAAAAEQAAHBCAAAAAAAANEMDAAAAAACAPwAAAAAAAAABAgEAAAAAgD8AAAcAAQEBAQEDDDEI+0L8GeJDTLdwQ32/GkI779lDtvPfQwCAKEL2qC1DZmbmQ0x3HEMxCPtC/BniQwABAAAAgD/7+no/j46OPgAAgD8AAIA/AAAAgD8AAIA/AAAAAIBAAAAAAAAAAIA/AAABAAAAAAAAAAAAAAAARAAAAEQAAAAAAQEAAAA=';

export const meta = { fr: 60, ip: 0, op: 180, width: 512, height: 512 };

export const init = () => ({ fr: 60, ip: 0, op: 180, width: 512, height: 512 });
