// Generated by ulottie — unminified for review; not what ships.
// Object keys are sorted here for stable diffs; emitted order differs.
// mode: extern
// caps: DISPLAY | SHAPE | KEYFRAMES | EASING | PATH_D | TRIM

import { mount } from './runtime/core.js';
import { bDisplay, oDisplay } from './runtime/ops/display.js';
import { bShape, oShape } from './runtime/ops/shape.js';
const P0=(x,B,e,l,q,a)=>[bDisplay(x,B[0],e,l,q,a),bShape(x,B[1],e,l,q,a)];
const A0=(x,S)=>{oDisplay(x,S[0]);oShape(x,S[1])};

const M =
  '<svg viewBox="0 0 200 200" width="100%" height="100%" preserveAspectRatio="xMidYMid meet" style="overflow:hidden">' +
    '<svg width="200" height="200">' +
      '<g transform="matrix(.7,0,0,.7,47.11,52.19)">' +
        '<g transform="matrix(-.97815,-.20791,.20791,-.97815,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.80902,.58779,-.58779,-.80902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.10453,.99452,-.99452,-.10453,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.66913,.74314,-.74314,.66913,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '</g>' +
        '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '<g transform="matrix(.66913,-.74314,.74314,.66913,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.10453,-.99452,.99452,-.10453,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.80902,-.58779,.58779,-.80902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.97815,.20791,-.20791,-.97815,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.5,.86603,-.86603,-.5,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.30902,.95106,-.95106,.30902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.91355,.40674,-.40674,.91355,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.91355,-.40674,.40674,.91355,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.30902,-.95106,.95106,.30902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.5,-.86603,.86603,-.5,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.97815,-.20791,.20791,-.97815,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.80902,.58779,-.58779,-.80902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.10453,.99452,-.99452,-.10453,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.66913,.74314,-.74314,.66913,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
        '</g>' +
        '<path fill="#f00" stroke-linecap="round" stroke="#9661ba" stroke-width="5"/>' +
      '</g>' +
      '<g transform="matrix(.7,0,0,.7,106.11,166.19)">' +
        '<g transform="matrix(-.97815,-.20791,.20791,-.97815,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.80902,.58779,-.58779,-.80902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.10453,.99452,-.99452,-.10453,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.66913,.74314,-.74314,.66913,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '</g>' +
        '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '<g transform="matrix(.66913,-.74314,.74314,.66913,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.10453,-.99452,.99452,-.10453,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.80902,-.58779,.58779,-.80902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.97815,.20791,-.20791,-.97815,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.5,.86603,-.86603,-.5,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.30902,.95106,-.95106,.30902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.91355,.40674,-.40674,.91355,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.91355,-.40674,.40674,.91355,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.30902,-.95106,.95106,.30902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.5,-.86603,.86603,-.5,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.97815,-.20791,.20791,-.97815,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.80902,.58779,-.58779,-.80902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.10453,.99452,-.99452,-.10453,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.66913,.74314,-.74314,.66913,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
        '</g>' +
        '<path fill="#f00" stroke-linecap="round" stroke="#40c9ff" stroke-width="5"/>' +
      '</g>' +
      '<g transform="matrix(.7,0,0,.7,45.11,111.19)">' +
        '<g transform="matrix(-.97815,-.20791,.20791,-.97815,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.80902,.58779,-.58779,-.80902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.10453,.99452,-.99452,-.10453,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.66913,.74314,-.74314,.66913,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '</g>' +
        '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '<g transform="matrix(.66913,-.74314,.74314,.66913,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.10453,-.99452,.99452,-.10453,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.80902,-.58779,.58779,-.80902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.97815,.20791,-.20791,-.97815,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.5,.86603,-.86603,-.5,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.30902,.95106,-.95106,.30902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.91355,.40674,-.40674,.91355,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.91355,-.40674,.40674,.91355,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.30902,-.95106,.95106,.30902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.5,-.86603,.86603,-.5,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.97815,-.20791,.20791,-.97815,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.80902,.58779,-.58779,-.80902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.10453,.99452,-.99452,-.10453,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.66913,.74314,-.74314,.66913,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
        '</g>' +
        '<path fill="#f00" stroke-linecap="round" stroke="#ed6680" stroke-width="5"/>' +
      '</g>' +
      '<g transform="matrix(.7,0,0,.7,143.11,56.19)">' +
        '<g transform="matrix(-.97815,-.20791,.20791,-.97815,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.80902,.58779,-.58779,-.80902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.10453,.99452,-.99452,-.10453,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.66913,.74314,-.74314,.66913,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '</g>' +
        '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '<g transform="matrix(.66913,-.74314,.74314,.66913,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.10453,-.99452,.99452,-.10453,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.80902,-.58779,.58779,-.80902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.97815,.20791,-.20791,-.97815,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.5,.86603,-.86603,-.5,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.30902,.95106,-.95106,.30902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.91355,.40674,-.40674,.91355,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.91355,-.40674,.40674,.91355,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.30902,-.95106,.95106,.30902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.5,-.86603,.86603,-.5,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.97815,-.20791,.20791,-.97815,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.80902,.58779,-.58779,-.80902,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(-.10453,.99452,-.99452,-.10453,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '</g>' +
        '<g transform="matrix(.66913,.74314,-.74314,.66913,0,0)">' +
          '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
        '</g>' +
        '<path fill="#f00" stroke-linecap="round" stroke="#f3a54d" stroke-width="5"/>' +
      '</g>' +
    '</svg>' +
  '</svg>';

const D = "0gjl70gthg10q10s3mo60000800gt7gt7qp20sv4gt7qp20qo4gt7qp20ov4gt760i2ug1m1ig1amf60g5u4u4ghn2gvl5gtk8gvgs3gtvu3gruh4k34uu2pfuu2hgqs1mg14aq10oc6mj140oju30oc6002u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q82mg14k1k20oc4mg14aq10oc42ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q82mg14g2g30oc2mg14m1m20oc22qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q82mg14s2s30oc2mg14i2i30oc22uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q82ga26444244444444444444264442444444444444442644424444444444444426444244444444444444200000000000000000000666666666666666666664444444444444444444422222222222222222222i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6u8o9iasambgcqckdudoeifsfmg1gh1qh1ki1ui1oj1ik1sk1in1sn1mo1gp1qp1kq1uq1or1is1ss1mt1gu1qu1kv1uv1og2ih2sh2mi2gj2ml2gm2qm2kn2un2oo2ip2sp2mq2gr2qr2ks2us2ot2iu2su2mv2gg3qg3kh3qj3kk3uk3ol3im3sm3mn3go3qo3kp3up3oq3ir3sr3ms3gt3qt3ku3uu3ov34s4ig4";

export const markup = M;
export const init = (c, o) => mount(M, D, P0, A0, c, o);
