// Generated by ulottie — skia-aot target (@shopify/react-native-skia + react-native-reanimated).
// Deliberately unminified: Metro's reanimated plugin reads the 'worklet' directives
// before its own minifier runs; a minifier here could strip them.
// caps: DISPLAY | SHAPE | KEYFRAMES | EASING | PATH_D | TRIM

// runtime symbols: fmt, r, dec, H_FR, H_IP, H_OP, H_EASINGS, H_TIMELINES, H_GATES, H_PROGRAM, H_REMAPS, INV, P10, put, open, EASE, T_SCALAR, T_VECTOR, T_PATH, T_EXPR, F_EASE, F_HOLD, pseg, pease, pv, pvp, mkPath, xv, pdPair, pdSep, pathD, SAMPLES, trimTable, trimApply, tmConcat, tmCut, tmLocate, tmBetween, tmSplit, bDisplay, oDisplay, hasTrim, trimCols, trim, bShape, oShape, rput, skSet, skMatrix, skNums, skGeom, skPaints, skGrad, skOwn, skFxPaint, mountRn, skPrepare, skGradRec, skDraw, skFx, skShape, skGeomDraw, mountSkia
// Shared number → string formatting for attribute values.
//
// Precision is chosen per role, because the error budgets differ by orders of
// magnitude: a matrix's linear part multiplies every coordinate beneath it
// (error ~ quantum * extent), while a translation or a path coordinate
// contributes absolute error only.
//
// Do not "optimize" this by assembling the digits from the rounded integer
// instead of handing a float to V8's dtoa. That version was written, tested
// byte-identical over 7434 real interpolated values, and measured 2.36× faster
// in isolation — and it was still reverted:
//
//   • A CDP sampling profile puts `fmt` at 3.0% of frame time on `lottie_logo_1`
//     (the most format-heavy fixture) and below the top twelve on `ripple`, so
//     2.36× caps out at a 1.7% win.
//   • End-to-end frame time, alternating four runs, showed no effect outside
//     noise.
//   • It cost +118 B gzipped on `lottie_logo_1`, +2.2% of the whole module.
//
// The profile says the time is in path-string assembly (`pathD` + `pdPair` +
// `pdSep`, 15% together) and in `setAttribute` and `evalExpr` — not here.
//
// A fraction keeps its leading zero even though SVG parses ".5" fine. The
// react-native-svg target shares this helper, and its JS prop parser rejects
// ".47" ("not a valid number or percentage string"), leaves the prop a String,
// and Fabric's generated RNSVGGroupManagerDelegate.setProperty then throws
// ClassCastException: String cannot be cast to Double — an app-killing crash on
// Android, observed on a Pixel 8 with the `mixed16` fixture.
function fmt(x, scale) { 'worklet';
  return '' + Math.round(x * scale) / scale;
}

/** Coordinates and plain attribute values: 3 decimals. */
function r(x) { 'worklet';
  return fmt(x, 1000);
}

/** Matrix linear part: 5 decimals. */
// The payload decoder: one base36 VLQ string → one `Int32Array`.
//
// Runs once per mount. Everything downstream reads properties straight out of
// the array by offset, so this is the only place the wire format is touched.

/**
 * Decode the stream.
 *
 * Each character carries four data bits plus a continuation bit, written with
 * base36 digits — `0`–`9` are 0–15 and part of `a`–`v` the rest, which is what
 * `parseInt(c, 36)` would give. Doing the digit arithmetic on the char code
 * directly avoids a `parseInt` call per character, and there are a lot of
 * characters.
 *
 * Values are zigzagged, so a small negative costs one character just like a
 * small positive.
 */
function dec(s) { 'worklet';
  const n = s.length;
  // Every integer takes at least one character, so the string length is a
  // safe upper bound and the array is allocated exactly once.
  const out = new Int32Array(n);
  let k = 0, acc = 0, sh = 0;
  for (let i = 0; i < n; i++) {
    const c = s.charCodeAt(i);
    // '0'..'9' are 48..57, 'a'..'v' are 97..118.
    const d = c < 58 ? c - 48 : c - 87;
    acc |= (d & 15) << sh;
    if (d & 16) {
      sh += 4;
    } else {
      // Un-zigzag. `acc` is a full 32-bit pattern by now, so the shift has to
      // be unsigned or the sign bit would smear.
      out[k++] = (acc >>> 1) ^ -(acc & 1);
      acc = 0;
      sh = 0;
    }
  }
  return out.subarray(0, k);
}
// Where things live in the integer stream.
//
// The single source of truth on this side is `scene/flat.rs`; these must stay
// in step with it.
//
// One constant per slot rather than one table: a minifier will fold
// `H_PROGRAM` to `8` but cannot fold `head.PROGRAM`, so the table shipped whole
// in every self-contained module. Separate bindings also shake individually, so
// an animation without records carries none of the record bits.

// Fixed slots at the head of the stream. A zero means the section is absent.
const H_FR = 1;
const H_IP = 2;
const H_OP = 3;
const H_EASINGS = 5;
const H_TIMELINES = 6;
const H_GATES = 7;
// `[count, batchOffset × count]` — the document's own bindings, grouped by op.
const H_PROGRAM = 8;
const H_REMAPS = 12;

// One precomp asset: `[template, program, timelines, records]`.
// Descaling factors for the wire's per-column shifts.
//
// A column carries the smallest power of ten that represents it exactly, so
// reading one back is a single multiply by its reciprocal. Shared because the
// property reader, the clock table and the gate table all need it.

const INV = [1, 0.1, 0.01, 0.001];

// The other direction. A keyframe time column stays in its own scale and the
// frame is scaled up to meet it, so the hot comparisons are integer against
// integer and no time is ever descaled.
const P10 = [1, 10, 100, 1000];
// The Skia write point — the skia-aot counterpart of `runtime/rn/set.js`.
//
// An element handle is the same `{ i, p, d, q }` record `mountRn` builds,
// plus two fields `skPrepare` links at mount: `el.n`, the display-list node
// the slot lowered to, and `el.K`, the Skia factory. The ops keep producing
// the web runtime's strings — identity is what the change detection
// compares, so every conversion below runs on actual changes only — and the
// converted value lands on the node record the draw walker reads: matrices
// as 9-number row-major arrays, `d` strings as cached SkPath objects,
// paint attributes as rebuilt SkPaint state.

function put(el, name, v, w, i) { 'worklet';
  if (v !== w[i]) {
    w[i] = v;
    skSet(el, name, v);
    if (!el.d) { el.d = 1; el.q.push(el); }
  }
}

/**
 * Direct write for the loops that write outside `put`'s one-attribute guard
 * (the display gates, the rect radius pair). The caller has already
 * change-detected; this only converts and marks the element dirty.
 */
// Opening one op's batch.
//
// The compiler groups every binding by op and writes each group as a
// struct-of-arrays batch:
//
// ```text
// [count, flags,
//  el…     count, first differences
//  gate…   count, when flags & 1
//  slot…   count, when flags & 2
//  arg0…   count
//  …
//  argK…   count]
// ```
//
// An op comes in two halves, and neither is a callback. `bXxx` binds a batch
// once and hands back a plain state record; `oXxx(x, s)` is the frame, called
// directly. The module names both, because which op a binding is was never
// anything but a compile-time fact — so nothing here closes over anything, and
// the only closure left in an animation is the one `player` is handed.
//
// Gates and clocks are materialized as dense columns even when the wire omits
// them, so the loop reads `ON[G[i]]` and `T[L[i]]` unconditionally — gate 0 is
// pinned on and slot 0 is the composition clock. A present-or-absent branch per
// binding per frame buys nothing against two loads from a small typed array.

/**
 * Resolve a batch's columns: elements, gate, clock, and `k` argument columns.
 *
 * `eb`/`sb`/`ps` position the batch within an instantiation — the element base,
 * the clock base, and the clock the instance itself runs on. All three are zero
 * for the document's own bindings, which is what lets one code path serve both.
 */
function open(x, base, eb, sb, ps, k) { 'worklet';
  const S = x.S;
  const n = S[base];
  const flags = S[base + 1];
  let c = base + 2;
  // Element indices ship as first differences: consecutive bindings sit close
  // together in document order, and an instanced asset's column then replays at
  // any base.
  const E = new Array(n);
  for (let i = 0, e = 0; i < n; i++) E[i] = x.els[eb + (e += S[c + i])];
  c += n;
  const G = new Int32Array(n);
  if (flags & 1) {
    for (let i = 0; i < n; i++) G[i] = S[c + i];
    c += n;
  }
  const L = new Int32Array(n);
  if (flags & 2) {
    // A local slot of zero is the instance's own clock, not the composition's.
    for (let i = 0; i < n; i++) { const v = S[c + i]; L[i] = v ? sb + v : ps; }
    c += n;
  } else if (ps) {
    L.fill(ps);
  }
  // Arguments are copied out of the stream rather than indexed through it, so
  // the frame loop reads a dense typed array it can hold in a register.
  const A = new Array(k);
  for (let j = 0; j < k; j++, c += n) {
    const col = new Int32Array(n);
    for (let i = 0; i < n; i++) col[i] = S[c + i];
    A[j] = col;
  }
  return { n, E, G, L, A };
}

/** Undo a column's first differences, in place. */
// Cubic-bezier timing solve.
//
// Only bundled when the animation actually has a non-linear easing handle —
// the compiler folds every linear (and linear-equivalent) segment to index 0
// and the interpolator skips this entirely for those.

/**
 * Solve `x(s) = u` for the bezier through (0,0), (x1,y1), (x2,y2), (1,1),
 * then return `y(s)`. Newton–Raphson seeded at `u`; eight iterations is well
 * past convergence for the handle ranges Lottie produces.
 *
 * @param {ArrayLike<number>} e `[x1, y1, x2, y2]`
 */
function EASE(e, u) { 'worklet';
  const x1 = e[0], y1 = e[1], x2 = e[2], y2 = e[3];
  let s = u;
  for (let i = 0; i < 8; i++) {
    const m = 1 - s;
    const x = 3 * m * m * s * x1 + 3 * m * s * s * x2 + s * s * s - u;
    if (x > -1e-6 && x < 1e-6) break;
    const dx = 3 * m * m * x1 + 6 * m * s * (x2 - x1) + 3 * s * s * (1 - x2);
    if (dx > -1e-6 && dx < 1e-6) break;
    s -= x / dx;
    s = s < 0 ? 0 : s > 1 ? 1 : s;
  }
  const m = 1 - s;
  return 3 * m * m * s * y1 + 3 * m * s * s * y2 + s * s * s;
}
// Property evaluation, read straight off the stream.
//
// A property is a run of integers at an offset in the single `Int32Array` the
// payload decodes to. These functions read it at the frame they are asked for:
// there is no closure per property, no object, and no copy of the keyframe
// data. The only state a property needs is its segment cursor, which lives in
// an `Int32Array` the caller indexes by binding.
//
// **One function per result shape, not one closure per property shape.** That
// is what makes an op's frame loop monomorphic: `pv` is a single call target,
// so V8 can inline it into the loop, where twelve closure shapes reached
// through one `U[i](f)` could only ever be a generic call.
//
// The three shapes are the three things a binding can consume — a number, a
// vector written into the caller's scratch, and a path object.


/// Property tags, in the low three bits of a property's first word. Kept in
/// sync with `scene/flat.rs`. `T_ANIM` is what the readers fall through to.
const T_SCALAR = 0;
const T_VECTOR = 1;
const T_PATH = 2;
const T_EXPR = 4;

/// An `Anim`'s value kind, in bits 11–12. Path keyframes hold offsets to pooled
/// path properties where the others hold numbers.
const F_EASE = 1;
const F_HOLD = 2;
function pseg(S, t, n, ft, c, i) { 'worklet';
  const k = c[i];
  if (ft >= S[t + k] && ft <= S[t + k + 1]) return k;
  let lo = 0, hi = n - 1;
  while (hi - lo > 1) {
    const m = (lo + hi) >> 1;
    if (S[t + m] <= ft) lo = m; else hi = m;
  }
  c[i] = lo;
  return lo;
}

/** Segment easing. Handle 0 is linear and never reaches the solver. */
function pease(z, S, ez, k, u) { 'worklet';
  if (!ez) return u;
  const h = S[ez + k];
  return h === 0 ? u : EASE(z[h], u);
}

// The optional columns follow the values in a fixed order — easing, holds,
// then the two spatial tangent columns — so each reader walks a running offset
// through the ones it needs. Three functions that each recomputed the whole
// staircase from the header meant the shared prefix was derived two or three
// times per property per frame, and adding a column meant editing all three
// in step.

/**
 * A scalar property at frame `f`.
 *
 * `off` of zero means the property is absent, which is unambiguous because
 * offset zero is the header and no property can live there.
 */
function pv(x, off, f, c, i) { 'worklet';
  if (!off) return 0;
  const S = x.S;
  const head = S[off];
  const tag = head & 7;
  if (tag === T_SCALAR) return S[off + 1] * INV[(head >> 3) & 3];
  // A one-component vector in a scalar slot. The planner classifies by the
  // dimension it asked for, not by what Lottie stored, so a scalar property
  // written as `[x]` arrives here. The closure form this replaced handed the
  // array back and let JS coerce it; reading component zero is the same value
  // and does not depend on that coercion.
  if (tag === T_VECTOR) return S[off + 2] * INV[(head >> 3) & 3];
  // An expression with no engine to run it is its own value source. With an
  // engine, the whole column is resolved ahead of the loop and never lands here.
  if (tag === T_EXPR) return pv(x, S[off + 2], f, c, i);
  const n = S[off + 1];
  const iv = INV[(head >> 5) & 3];
  const t = off + 2;
  const v = t + n;
  const ft = f * P10[(head >> 3) & 3];
  if (ft <= S[t]) return S[v] * iv;
  if (ft >= S[t + n - 1]) return S[v + n - 1] * iv;
  const k = pseg(S, t, n, ft, c, i);
  const span = S[t + k + 1] - S[t + k];
  if (span === 0) return S[v + k + 1] * iv;
  const fl = (head >> 7) & 7;
  let nx = v + n;
  const ez = fl & F_EASE ? nx : 0;
  if (ez) nx += n - 1;
  if (fl & F_HOLD && S[nx + k]) return S[v + k] * iv;
  const u = pease(x.z, S, ez, k, (ft - S[t + k]) / span);
  const a = S[v + k];
  const b = S[v + k + 1];
  return (a + (b - a) * u) * iv;
}

/**
 * A vector property at frame `f`, written into `out`.
 *
 * `out` is the column's scratch, so a steady-state frame allocates nothing. One
 * per column is enough because a binding never holds two values from the same
 * column at once — except for paint, where `css` asks the buffer itself whether
 * the colour carries an alpha channel and so needs one sized per binding. See
 * [`vscratch`].
 */
function pvp(x, off, f, c, i, m) { 'worklet';
  if (!off) return null;
  const S = x.S;
  const head = S[off];
  const tag = head & 7;
  if (tag === T_PATH) return m[i] || (m[i] = mkPath(S, off));
  if (tag === T_EXPR) return pvp(x, S[off + 2], f, c, i, m);
  const n = S[off + 1];
  const t = off + 2;
  const v = t + n;
  const fl = (head >> 7) & 7;
  // The keyframes hold offsets to pooled path properties. They are constant,
  // so the whole column is materialized on this binding's first frame.
  let keys = m[i];
  if (keys === undefined) {
    keys = m[i] = new Array(n);
    for (let k = 0; k < keys.length; k++) keys[k] = mkPath(S, S[v + k]);
  }
  const ft = f * P10[(head >> 3) & 3];
  if (ft <= S[t]) return keys[0];
  if (ft >= S[t + n - 1]) return keys[n - 1];
  const k = pseg(S, t, n, ft, c, i);
  const span = S[t + k + 1] - S[t + k];
  if (span === 0) return keys[k + 1];
  let nx = v + n;
  const ez = fl & F_EASE ? nx : 0;
  if (ez) nx += n - 1;
  if (fl & F_HOLD && S[nx + k]) return keys[k];
  const u = pease(x.z, S, ez, k, (ft - S[t + k]) / span);
  return lerpPath(keys[k], keys[k + 1], u);
}

/**
 * `[tag|shift<<3|closed<<5|curved<<6, points, x,y…, (i…), (o…)]` → `{v,i,o,c}`.
 */
function mkPath(S, off) { 'worklet';
  const head = S[off];
  const iv = INV[(head >> 3) & 3];
  const n = S[off + 1] * 2;
  const base = off + 2;
  const v = new Array(n);
  for (let k = 0; k < n; k++) v[k] = S[base + k] * iv;
  let i = null, o = null;
  if (head & 64) {
    i = new Array(n);
    o = new Array(n);
    for (let k = 0; k < n; k++) {
      i[k] = S[base + n + k] * iv;
      o[k] = S[base + n + n + k] * iv;
    }
  }
  return { v, i, o, c: (head >> 5) & 1 };
}

/**
 * A scalar column's value, taking the expression column ahead of the wire.
 *
 * `X` is null for the columns nothing drives by expression, which is nearly all
 * of them, so the test costs one compare against a loop-invariant.
 */
function xv(x, X, C, i, f, c) { 'worklet';
  return X && X[i] ? X[i](f) : pv(x, C[i], f, c, i);
}

/** The same for a vector column, into the column's scratch. */
// Path serialization.
//
// Only bundled when some geometry is actually animated — every static path in
// the animation was serialized by the compiler and lives in the markup.
//
// Paths use the flat layout `{v:[x,y,…], i:[…], o:[…], c:0|1}`. `i`/`o` are
// null for polygonal paths.


/** `x,y` — the comma is dropped when `y` self-delimits via its sign. */
function pdPair(x, y) { 'worklet';
  const b = r(y);
  return r(x) + (b.charCodeAt(0) === 45 ? '' : ',') + b;
}

/** Separator ahead of an already-formatted number. */
function pdSep(s) { 'worklet';
  return s.charCodeAt(0) === 45 ? '' : ',';
}

function pathD(p) { 'worklet';
  const v = p.v;
  const n = v.length >> 1;
  if (!n) return '';
  const ti = p.i, to = p.o;
  const segs = p.c ? n : n - 1;
  let d = 'M' + pdPair(v[0], v[1]);
  for (let s = 0; s < segs; s++) {
    const a = s * 2;
    const b = ((s + 1) % n) * 2;
    const ox = to ? to[a] : 0, oy = to ? to[a + 1] : 0;
    const ix = ti ? ti[b] : 0, iy = ti ? ti[b + 1] : 0;
    if (!ox && !oy && !ix && !iy) {
      d += 'L' + pdPair(v[b], v[b + 1]);
    } else {
      const c2 = pdPair(v[b] + ix, v[b + 1] + iy);
      const c3 = pdPair(v[b], v[b + 1]);
      d += 'C' + pdPair(v[a] + ox, v[a + 1] + oy) + pdSep(c2) + c2 + pdSep(c3) + c3;
    }
  }
  return p.c ? d + 'Z' : d;
}
// Trim-path modifier.
//
// Splitting a path at an arc-length fraction needs a per-segment length table.
// That table depends only on the geometry, so when the source path is static
// (the common case — a traced outline being drawn on) it is built once at
// mount and reused for the whole animation.

const SAMPLES = 30;

/** Build the per-segment arc-length table for a flat path. */
function trimTable(p) { 'worklet';
  const v = p.v, ti = p.i, to = p.o;
  const n = v.length >> 1;
  const segCount = p.c ? n : n - 1;
  if (n < 2) return null;
  const segs = new Array(segCount);
  let total = 0;
  for (let s = 0; s < segCount; s++) {
    const a = s * 2, b = ((s + 1) % n) * 2;
    const p0x = v[a], p0y = v[a + 1], p3x = v[b], p3y = v[b + 1];
    const p1x = p0x + (to ? to[a] : 0), p1y = p0y + (to ? to[a + 1] : 0);
    const p2x = p3x + (ti ? ti[b] : 0), p2y = p3y + (ti ? ti[b + 1] : 0);
    const dist = new Float64Array(SAMPLES + 1);
    let cum = 0, px = p0x, py = p0y;
    for (let k = 1; k <= SAMPLES; k++) {
      const t = k / SAMPLES, u = 1 - t;
      const u3 = u * u * u, u2t = 3 * u * u * t, ut2 = 3 * u * t * t, t3 = t * t * t;
      const x = u3 * p0x + u2t * p1x + ut2 * p2x + t3 * p3x;
      const y = u3 * p0y + u2t * p1y + ut2 * p2y + t3 * p3y;
      cum += Math.hypot(x - px, y - py);
      dist[k] = cum;
      px = x; py = y;
    }
    segs[s] = { len: cum, dist, p: [p0x, p0y, p1x, p1y, p2x, p2y, p3x, p3y] };
    total += cum;
  }
  return { segs, total, closed: !!p.c };
}

/**
 * Trim `tab` to the arc-length range `[lo, hi]` (fractions of total length),
 * rotated by `offset` turns. Returns a flat open path.
 */
function trimApply(tab, lo, hi, offset) { 'worklet';
  if (!tab || tab.total === 0) return { v: [], i: null, o: null, c: 0 };
  if (hi - lo >= 1) return null;   // caller keeps the untrimmed path
  let a = lo + offset, b = hi + offset;
  if (tab.closed) {
    const floor = Math.floor(a);
    a -= floor; b -= floor;
    if (b > 1) return tmConcat(tmCut(tab, a, 1), tmCut(tab, 0, b - 1));
    return tmCut(tab, a, b);
  }
  a = a < 0 ? 0 : a > 1 ? 1 : a;
  b = b < 0 ? 0 : b > 1 ? 1 : b;
  if (b <= a) return { v: [], i: null, o: null, c: 0 };
  return tmCut(tab, a, b);
}

function tmConcat(x, y) { 'worklet';
  if (!x.v.length) return y;
  if (!y.v.length) return x;
  return { v: x.v.concat(y.v), i: x.i.concat(y.i), o: x.o.concat(y.o), c: 0 };
}

function tmCut(tab, af, bf) { 'worklet';
  const aLoc = tmLocate(tab, af * tab.total);
  const bLoc = tmLocate(tab, bf * tab.total);
  const v = [], i = [], o = [];

  if (aLoc.s === bLoc.s) {
    const p = tmBetween(tab.segs[aLoc.s].p, aLoc.t, bLoc.t);
    v.push(p[0], p[1], p[6], p[7]);
    i.push(0, 0, p[4] - p[6], p[5] - p[7]);
    o.push(p[2] - p[0], p[3] - p[1], 0, 0);
    return { v, i, o, c: 0 };
  }

  const head = tmBetween(tab.segs[aLoc.s].p, aLoc.t, 1);
  v.push(head[0], head[1]);
  i.push(0, 0);
  o.push(head[2] - head[0], head[3] - head[1]);
  let px = head[4], py = head[5], ex = head[6], ey = head[7];

  for (let s = aLoc.s + 1; s < bLoc.s; s++) {
    const p = tab.segs[s].p;
    v.push(p[0], p[1]);
    i.push(px - ex, py - ey);
    o.push(p[2] - p[0], p[3] - p[1]);
    px = p[4]; py = p[5]; ex = p[6]; ey = p[7];
  }

  const tail = tmBetween(tab.segs[bLoc.s].p, 0, bLoc.t);
  v.push(tail[0], tail[1]);
  i.push(px - ex, py - ey);
  o.push(tail[2] - tail[0], tail[3] - tail[1]);
  v.push(tail[6], tail[7]);
  i.push(tail[4] - tail[6], tail[5] - tail[7]);
  o.push(0, 0);

  return { v, i, o, c: 0 };
}

function tmLocate(tab, dist) { 'worklet';
  let acc = 0;
  const segs = tab.segs;
  for (let s = 0; s < segs.length; s++) {
    const seg = segs[s];
    if (dist <= acc + seg.len || s === segs.length - 1) {
      const local = Math.max(0, dist - acc);
      const d = seg.dist;
      let lo = 0, hi = SAMPLES;
      while (lo < hi) {
        const m = (lo + hi) >> 1;
        if (d[m] < local) lo = m + 1; else hi = m;
      }
      const up = lo, low = up > 0 ? up - 1 : 0;
      const dl = d[low], dh = d[up];
      const f = dh === dl ? 0 : (local - dl) / (dh - dl);
      const t = (low + f) / SAMPLES;
      return { s, t: t < 0 ? 0 : t > 1 ? 1 : t };
    }
    acc += seg.len;
  }
  return { s: segs.length - 1, t: 1 };
}

/** Sub-curve of a cubic between parameters `a` and `b`. */
function tmBetween(p, a, b) { 'worklet';
  const left = tmSplit(p, b).left;
  return tmSplit(left, b === 0 ? 0 : a / b).right;
}

function tmSplit(p, t) { 'worklet';
  const u = 1 - t;
  const a01x = u * p[0] + t * p[2], a01y = u * p[1] + t * p[3];
  const a12x = u * p[2] + t * p[4], a12y = u * p[3] + t * p[5];
  const a23x = u * p[4] + t * p[6], a23y = u * p[5] + t * p[7];
  const b01x = u * a01x + t * a12x, b01y = u * a01y + t * a12y;
  const b12x = u * a12x + t * a23x, b12y = u * a12y + t * a23y;
  const cx = u * b01x + t * b12x, cy = u * b01y + t * b12y;
  return {
    left: [p[0], p[1], a01x, a01y, b01x, b01y, cx, cy],
    right: [cx, cy, b12x, b12y, a23x, a23y, p[6], p[7]],
  };
}
// Layer in/out point. Only emitted for layers whose span is narrower than the
// composition's.


function bDisplay(x, base, eb, sb, ps) { 'worklet';
  const b = open(x, base, eb, sb, ps, 2);
  const n = b.n;
  const O = new Float64Array(n), Q = new Float64Array(n);
  for (let i = 0; i < n; i++) { O[i] = b.A[0][i] / 1000; Q[i] = b.A[1][i] / 1000; }
  return { n, E: b.E, G: b.G, L: b.L, O, Q, W: new Array(n) };
}

// Layer in/out on a react-native-svg handle — replaces the web `oDisplay`
// at declaration granularity (`bDisplay` is DOM-free and stays shared).
//
// There is no style object on an RN handle, so the gate lands in the props
// record as `display: '' | 'none'`, and the consumer's element wrapper
// renders nothing while it is 'none'. Not `opacity`: a layer can carry an
// animated opacity *and* an in/out span, and folding the gate into opacity
// would have the two fight over one prop slot.


function oDisplay(x, s) { 'worklet';
  const n = s.n, E = s.E, G = s.G, L = s.L, O = s.O, Q = s.Q, W = s.W;
  const T = x.T, ON = x.ON;
  for (let i = 0; i < n; i++) {
    if (!ON[G[i]]) continue;
    const t = T[L[i]];
    const v = t >= O[i] && t < Q[i];
    if (v !== W[i]) { W[i] = v; rput(E[i], 'display', v ? '' : 'none'); }
  }
}
// Geometry: build a path for the frame, optionally trim it, write `d`.
//
// Reached only when something about the shape actually moves. A static shape
// under an animated trim still comes through here, but with its source path
// already resolved by the compiler — so its arc-length table is built once.
//
// **One loop per geometry kind, not one loop with a switch.** Which generator a
// shape needs was decided when the shape was planned, so it is the op code: an
// animation that only draws bezier paths ships neither the polystar generator
// nor the branch that skips past it, and each loop below calls exactly one
// generator from exactly one call site.
//
// The trim modifier stays a column rather than doubling the op count. It is
// shared, and a batch that has none never enters it.


/** Does any binding in this batch carry a trim? */
function hasTrim(TM, n) { 'worklet';
  for (let i = 0; i < n; i++) if (TM[i]) return true;
  return false;
}

/**
 * The extra steps of one binding's trim chain: property offsets, cursors and
 * — when an engine is present — expression handles, per binding.
 *
 * Its own declaration, cut by `TRIM_CHAIN`: a chain is rare (a group trim
 * nested inside a layer trim), and an ordinarily-trimmed animation should not
 * carry the composing machinery. The call site guards on the wire's own step
 * count, which a module without the capability never exceeds.
 */
function trimCols(x, TM, P, n, at) { 'worklet';
  const S = x.S;
  const M = new Int32Array(n), M2 = new Int32Array(n), M3 = new Int32Array(n);
  const B = new Array(n);
  let R = null;
  for (let i = 0; i < n; i++) {
    const m = TM[i];
    if (!m) continue;
    M[i] = S[m + 1]; M2[i] = S[m + 2]; M3[i] = S[m + 3];
    if (S[m] > 1) R = trimChainCols(x, R, n, i, m, at);
    // A keyframed or expression-driven shape is not a static path.
    if (P && P[i] && (S[P[i]] & 7) === T_PATH) B[i] = trimTable(mkPath(S, P[i]));
  }
  return {
    M, M2, M3, B, R,
    X: x.expr ? xcol(x, M, n, at) : null,
    X2: x.expr ? xcol(x, M2, n, at) : null,
    X3: x.expr ? xcol(x, M3, n, at) : null,
    C: new Int32Array(n), C2: new Int32Array(n), C3: new Int32Array(n),
    W: new Array(n),
  };
}

/**
 * The outline to draw, or null when the trim range has closed over it.
 *
 * Hiding is the element's own state rather than an attribute, so it is settled
 * here and the caller only has to know whether there is anything left to write.
 *
 * Whether *this* binding has a trim at all is the caller's test — a batch can
 * mix trimmed and untrimmed shapes, and the untrimmed ones should cost one
 * array load rather than a call that reads eleven fields to learn they have
 * nothing to do.
 */
// The web `trim` settles a fully-closed trim range by writing
// `el.style.display` — the second of the three direct DOM writes in the
// runtime. Same body, with the hide landing in the RN prop store instead.
// Every other declaration in ops/shape.js is DOM-free and stays shared;
// this one keeps its name so the `TRIM` capability gate still cuts it.


function trim(x, m, i, t, src, el) { 'worklet';
  const a = xv(x, m.X, m.M, i, t, m.C) / 100;
  const z = xv(x, m.X2, m.M2, i, t, m.C2) / 100;
  let lo = a < z ? a : z, hi = a < z ? z : a;
  let off = xv(x, m.X3, m.M3, i, t, m.C3) / 360;
  if (m.R && m.R.r[i]) {
    const w = trimChainWin(x, m.R, i, t, lo + off, hi - lo);
    lo = w[0]; hi = w[1]; off = 0;
  }
  const vis = hi - lo;
  let out = null, hide = false;
  if (vis <= 0) {
    hide = true;
  } else if (vis < 1) {
    out = trimApply(m.B[i] || trimTable(src), lo, hi, off);
    if (out && !out.v.length) hide = true;
  }
  if (hide !== m.W[i]) { m.W[i] = hide; rput(el, 'display', hide ? 'none' : ''); }
  return hide ? null : out || src;
}
function bShape(x, base, eb, sb, ps, at) { 'worklet';
  const b = open(x, base, eb, sb, ps, 2);
  const n = b.n, P = b.A[0];
  return {
    n, E: b.E, G: b.G, L: b.L, P,
    XP: x.expr ? xcol(x, P, n, at) : null,
    TM: hasTrim(b.A[1], n) ? trimCols(x, b.A[1], P, n, at) : null,
    C: new Int32Array(n), Q: new Array(n), W: new Array(n),
  };
}

function oShape(x, s) { 'worklet';
  const n = s.n, E = s.E, G = s.G, L = s.L, P = s.P, XP = s.XP, TM = s.TM;
  const TB = TM && TM.M, C = s.C, Q = s.Q, W = s.W, T = x.T, ON = x.ON;
  for (let i = 0; i < n; i++) {
    if (!ON[G[i]]) continue;
    const t = T[L[i]], el = E[i];
    let src = XP && XP[i] ? XP[i](t) : pvp(x, P[i], t, C, i, Q);
    if (TB && TB[i]) src = trim(x, TM, i, t, src, el);
    if (src) put(el, 'd', pathD(src), W, i);
  }
}

// --- one element, several path properties -----------------------------------
//
// lottie-web gives every style ONE element and writes each shape it paints
// into that element, so contours sharing a style share a fill rule and their
// windings interact — that is how holes and merged paths render. The compiler
// buckets same-style siblings onto one element; this concatenates their
// outlines per frame. The property list is the one argument, a section
// `[count, prop offset…]` referenced by offset.

function rput(el, prop, v) { 'worklet';
  skSet(el, prop, v);
  if (!el.d) { el.d = 1; el.q.push(el); }
}

/**
 * One attribute write onto a display-list node. The name set is closed: it
 * is exactly what the ops inside the skia-aot capability whitelist emit, and
 * an unknown name throws instead of dropping the write — the runtime twin of
 * the compiler's named-refusal rule.
 */
function skSet(el, name, v) { 'worklet';
  const n = el.n, Sk = el.K;
  switch (name) {
    case 'transform': n.m = skMatrix(v); break;
    case 'opacity': n.o = +v; break;
    case 'display': n.h = v === 'none' ? 1 : 0; break;
    case 'd': {
      n.P = Sk.Path.MakeFromSVGString(v);
      if (n.P && n.eo) n.P.setFillType(1);
      break;
    }
    case 'fill': n.f = v; skPaints(n, Sk); break;
    case 'fill-opacity': n.fo = +v; skPaints(n, Sk); break;
    case 'stroke': n.sc = v; skPaints(n, Sk); break;
    case 'stroke-opacity': n.so = +v; skPaints(n, Sk); break;
    case 'stroke-width': n.sw = +v; skPaints(n, Sk); break;
    case 'stroke-dasharray': n.da = skNums(v); skPaints(n, Sk); break;
    case 'stroke-dashoffset': n.doff = +v; skPaints(n, Sk); break;
    case 'x': n.gx = +v; skGeom(n); break;
    case 'y': n.gy = +v; skGeom(n); break;
    case 'width': n.gw = +v; skGeom(n); break;
    case 'height': n.gh = +v; skGeom(n); break;
    // `cx`/`cy` are written by both the ellipse geometry ops and the radial
    // GRADIENT op; the record kind (4 = gradient) dispatches.
    case 'cx': if (n.k === 4) { n.g.cx = +v; skOwn(n, Sk); } else { n.cx = +v; skGeom(n); } break;
    case 'cy': if (n.k === 4) { n.g.cy = +v; skOwn(n, Sk); } else { n.cy = +v; skGeom(n); } break;
    case 'rx': n.rx = +v; skGeom(n); break;
    case 'ry': n.ry = +v; skGeom(n); break;
    // Animated gradient geometry (ops/grad.js) on a `k: 4` record.
    case 'r': n.g.r = +v; skOwn(n, Sk); break;
    case 'x1': n.g.x1 = +v; skOwn(n, Sk); break;
    case 'y1': n.g.y1 = +v; skOwn(n, Sk); break;
    case 'x2': n.g.x2 = +v; skOwn(n, Sk); break;
    case 'y2': n.g.y2 = +v; skOwn(n, Sk); break;
    // A keyframed ramp stop (ops/ramp.js) on a `k: 5` record.
    case 'offset': n.g.st[n.i][0] = +v; skOwn(n, Sk); break;
    case 'stop-color': n.g.st[n.i][1] = v; skOwn(n, Sk); break;
    // Animated layer-effect parameters (ops/fx.js) on a `k: 6` record.
    // `stdDeviation` arrives as an `"sx sy"` pair from the blur op and as a
    // lone scalar from the shadow-softness op; the record type (2 = shadow)
    // dispatches.
    case 'stdDeviation': {
      if (n.t === 2) {
        n.sd = +v;
      } else {
        const a = skNums(v);
        n.sx = a[0]; n.sy = a[1];
      }
      skFxPaint(n, Sk);
      break;
    }
    case 'dx': n.dx = +v; skFxPaint(n, Sk); break;
    case 'dy': n.dy = +v; skFxPaint(n, Sk); break;
    case 'flood-opacity': n.fo = +v; skFxPaint(n, Sk); break;
    default: throw new Error('skia-aot runtime has no write for `' + name + '`');
  }
}

/**
 * `matrix(a,b,c,d,e,f)` / `translate(x,y)` → row-major 3x3 for
 * `canvas.concat`. Those two spellings are the only ones the compiler ever
 * writes (see `scene::svg::matrix`); the parse mirrors `rnMatrix`.
 */
function skMatrix(v) { 'worklet';
  const a = v.slice(v.indexOf('(') + 1, v.length - 1).split(',');
  return v.charCodeAt(0) === 116
    ? [1, 0, +a[0], 0, 1, +a[1], 0, 0, 1]
    : [+a[0], +a[2], +a[4], +a[1], +a[3], +a[5], 0, 0, 1];
}

/** Space-separated number list (the dash op's `"4 2"` spelling). */
function skNums(v) { 'worklet';
  const parts = v.split(' ');
  const out = [];
  for (let i = 0; i < parts.length; i++) out.push(+parts[i]);
  return out;
}

/**
 * Refresh the scratch draw rect from the geometry fields. Rect nodes carry
 * `gx/gy/gw/gh` (+ corner `rx/ry`); ellipse nodes carry center + radii. One
 * mutable rect per node — the draw walk allocates nothing per frame.
 */
function skGeom(n) { 'worklet';
  const R = n.R;
  if (n.k === 2) {
    R.x = n.gx; R.y = n.gy; R.width = n.gw; R.height = n.gh;
  } else {
    R.x = n.cx - n.rx; R.y = n.cy - n.ry; R.width = 2 * n.rx; R.height = 2 * n.ry;
  }
}

/**
 * Rebuild a shape node's fill/stroke SkPaint pair from its paint fields.
 * Coarse on purpose: any paint-field change rebuilds both paints, which
 * keeps the write point tiny and still runs only on change (the string
 * guards upstream).
 */
function skPaints(n, Sk) { 'worklet';
  const f = n.f;
  if (f == null || f === 'none') {
    n.FP = null;
  } else {
    const p = n.FP || (n.FP = Sk.Paint());
    p.setAntiAlias(true);
    if (typeof f === 'string') {
      p.setShader(null);
      p.setColor(Sk.Color(f));
    } else {
      p.setColor(Sk.Color('#000'));
      p.setShader(skGrad(f.g, Sk));
    }
    if (n.fo != null) p.setAlphaf(p.getAlphaf() * n.fo);
  }
  const s = n.sc;
  if (s == null || s === 'none') {
    n.SP = null;
  } else {
    const p = n.SP || (n.SP = Sk.Paint());
    p.setAntiAlias(true);
    p.setStyle(1);
    if (typeof s === 'string') {
      p.setShader(null);
      p.setColor(Sk.Color(s));
    } else {
      p.setColor(Sk.Color('#000'));
      p.setShader(skGrad(s.g, Sk));
    }
    if (n.so != null) p.setAlphaf(p.getAlphaf() * n.so);
    p.setStrokeWidth(n.sw == null ? 1 : n.sw);
    p.setStrokeCap(n.cap || 0);
    p.setStrokeJoin(n.join || 0);
    if (n.ml != null) p.setStrokeMiter(n.ml);
    if (n.da && n.da.length) {
      // Skia requires an even interval count; SVG doubles an odd list.
      let iv = n.da;
      if (iv.length & 1) iv = iv.concat(iv);
      p.setPathEffect(Sk.PathEffect.MakeDash(iv, n.doff || 0));
    } else {
      p.setPathEffect(null);
    }
  }
}

/**
 * A live gradient object (`skGradRec`'s `.g`) → SkShader. Runs at mount and
 * again whenever a GRADIENT/RAMP op writes a field, via `skOwn`.
 */
function skGrad(g, Sk) { 'worklet';
  const colors = [];
  const pos = [];
  for (let i = 0; i < g.st.length; i++) {
    pos.push(g.st[i][0]);
    colors.push(Sk.Color(g.st[i][1]));
  }
  const lm = g.gt ? Sk.Matrix(g.gt) : undefined;
  return g.rad
    ? Sk.Shader.MakeRadialGradient(Sk.Point(g.cx, g.cy), g.r, colors, pos, 0, lm)
    : Sk.Shader.MakeLinearGradient(Sk.Point(g.x1, g.y1), Sk.Point(g.x2, g.y2), colors, pos, 0, lm);
}

/**
 * A gradient field changed: rebuild the shader-carrying paints of every
 * shape that draws with this gradient. `n` is a `k: 4` gradient record or a
 * `k: 5` stop record; both share the owner list.
 */
function skOwn(n, Sk) { 'worklet';
  const O = n.O;
  for (let i = 0; i < O.length; i++) skPaints(O[i], Sk);
}

/**
 * Rebuild an effect pass's layer image filter from its record fields.
 * `t: 1` is a gaussian blur (`MakeBlur`, tile mode from the effect's edge
 * behaviour); `t: 2` is a drop shadow (`MakeDropShadow` draws shadow AND
 * content — exactly the `feMerge(shadow, source)` the SVG chain ends with),
 * with the flood opacity folded into the shadow colour's alpha
 * (`Skia.Color` returns a mutable RGBA Float32Array).
 */
function skFxPaint(n, Sk) { 'worklet';
  if (n.t === 1) {
    n.P.setImageFilter(Sk.ImageFilter.MakeBlur(n.sx, n.sy, n.tm, null));
  } else {
    const col = Sk.Color(n.c);
    col[3] = n.fo;
    n.P.setImageFilter(Sk.ImageFilter.MakeDropShadow(n.dx, n.dy, n.sd, n.sd, col, null));
  }
}
// μLottie RN runtime — mount, without a document.
//
// The web `mount` parses markup, adopts DOM nodes and hands the ops
// `svg.querySelectorAll('*')`. Here the compiler already emitted the element
// tree as a static descriptor (`tree` in the generated module), so mounting
// is pure data: decode the stream, widen the easing/clock/gate tables exactly
// as core.js does, and hand the program an `els` array of plain prop-store
// handles in the same document order `querySelectorAll` would have produced
// (root `<svg>` excluded — it stays static, animated writes go to inner
// elements only).
//
//   D — the payload, one integer stream;
//   P/A — the emitted bind/apply program pair;
//   N — the element count (handles are dense; most never receive a write);
//   ext.p — the string pool; ext.r — the time-remap resolver, when used.
//
// `apply(f)` runs one frame: clocks, gates, one program pass. Changed
// elements collect in `dirty`; the consumer drains it (clearing each `d`)
// and pushes `p` into the matching react-native-svg elements.


function mountRn(D, P, A, N, ext) { 'worklet';
  ext = ext || {};
  // The immutable half — the payload decode, the widened easing handles and
  // the arc-length table cache — is identical for every instance of one
  // module, so it is built once per JS runtime and shared; init() then only
  // creates per-instance state (clocks, gates, element handles, bind state).
  // The cache must live on `globalThis`: worklet closures capture module
  // scope BY COPY at definition time, so a module-level `let` mutated on the
  // UI runtime would not persist across init() calls. The payload string is
  // its own cache key — it names the animation content exactly, and every
  // call passes the same captured string object, so the engine's cached
  // string hash makes the lookup cheap.
  const g = globalThis;
  const cache = g.__ulottie || (g.__ulottie = {});
  let sh = cache[D];
  if (!sh) {
    const dS = dec(D);

    // Easing handles, widened once — same as core.js.
    const ez = dS[H_EASINGS];
    const easings = [];
    if (ez) {
      for (let i = 0, n = dS[ez]; i < n; i++) {
        const at = ez + 1 + i * 4;
        easings.push([dS[at] / 1000, dS[at + 1] / 1000, dS[at + 2] / 1000, dS[at + 3] / 1000]);
      }
    }

    // `sp` holds spatial arc-length tables, keyed by tangent-column offset —
    // deterministic from the stream alone (see `pvv`), so instances share it.
    sh = cache[D] = { S: dS, z: easings, sp: new Map() };
  }
  const S = sh.S;
  const str = ext.p || [];

  const fr = S[H_FR] / 1000;
  const ip = S[H_IP] / 1000;
  const op = S[H_OP] / 1000;

  // Precomp clocks — see core.js for the row layout.
  const tl = S[H_TIMELINES];
  const nTl = tl ? S[tl] : 0;
  const tScale = nTl ? INV[S[tl + 1]] : 1;
  const tRows = tl + 2;
  const T = new Float64Array(nTl + 1);

  // Visibility gates — gate 0 pinned on, as on the web.
  const gt = S[H_GATES];
  const nGates = gt ? S[gt] : 0;
  const gScale = nGates ? INV[S[gt + 1]] : 1;
  const gRows = gt + 2;
  const ON = new Uint8Array(nGates + 1);
  ON[0] = 1;

  // Element handles: slot index, dynamic props, dirty flag, shared queue.
  // `x.els[i]` replaces the web's NodeList — same indexing, plain records.
  const dirty = [];
  const els = new Array(N);
  for (let i = 0; i < N; i++) els[i] = { i, p: {}, d: 0, q: dirty };

  const ctx = {
    S, str, els, z: sh.z,
    fr, frame: 0, T, ON, sp: sh.sp, expr: null, y: null,
  };

  // Time remap — the column is parallel to the timeline table.
  const rmc = S[H_REMAPS];
  const rm = rmc && ext.r
    ? Array.from({ length: S[rmc] }, (_, i) => (S[rmc + 1 + i] ? ext.r(S[rmc + 1 + i], ctx) : 0))
    : null;

  // One program: precomp instancing is off in this target, so every binding
  // lives in the document program and there is no uses/assets table to walk.
  const prog = S[H_PROGRAM];
  const st = prog ? P(ctx, S.subarray(prog + 1, prog + 1 + S[prog]), 0, 0, 0, 0) : null;

  function apply(f) {
    ctx.frame = f;
    T[0] = f;
    for (let i = 0; i < nTl; i++) {
      const e = tRows + i * 5;
      const remap = rm && rm[i];
      if (remap) {
        // Lottie stores the remap in seconds; the timeline is in frames.
        T[i + 1] = remap(T[S[e]]) * fr;
        continue;
      }
      T[i + 1] = (T[S[e]] - S[e + 1] * tScale) / (S[e + 2] / 1000);
    }
    for (let i = 0; i < nGates; i++) {
      const g = gRows + i * 2;
      ON[i + 1] = f >= S[g] * gScale && f < S[g + 1] * gScale ? 1 : 0;
    }
    if (st) A(ctx, st);
  }

  return { els, dirty, apply, fr, ip, op };
}
// The Skia draw walker — mount-time prepare plus the per-frame recursive
// record pass.
//
// `skPrepare` turns the compile-time display-list descriptor `dl` into live
// node records: SkPath for baked `d` strings and clip paths, SkPaint pairs
// for fills/strokes, mask and color-filter layer paints, gradient shaders.
// Records are built fresh per instance — worklet closures capture by copy,
// so caching them on the (captured) descriptor would never survive a second
// `init()` on the UI runtime. Slotted nodes link back onto the element
// handles (`el.n`) so `runtime/skia/set.js` can write converted values in
// place; the walk then reads only node fields and mutates nothing — zero
// per-frame allocation, matching the HANDOFF perf discipline.


/**
 * Build one node record from its descriptor. `d.k`: 0 group, 1 path,
 * 2 rect, 3 ellipse, 4 embedded image. See `backend/skia.rs` for the
 * descriptor grammar.
 */
function skPrepare(d, els, Sk) { 'worklet';
  // Hidden is `hd` in the descriptor (a rect's height already owns `h`
  // there); the live record uses `h` because that is what skSet 'display'
  // writes.
  const n = { k: d.k, h: d.hd ? 1 : 0, m: d.m || null, o: d.o == null ? 1 : d.o, OP: null };
  if (d.s != null && els[d.s]) { els[d.s].n = n; els[d.s].K = Sk; }
  if (d.k === 0) {
    if (d.clip) {
      if (d.clip.r) {
        const r = d.clip.r;
        n.CR = { x: r[0], y: r[1], width: r[2], height: r[3] };
      } else {
        // A path clip is a slim node record of its own: a lottie layer mask
        // animates its bezier, so the clip's slot links here and the write
        // point rebuilds `P` exactly as for a drawable path.
        const cl = { k: 1, eo: d.clip.eo ? 1 : 0, P: null };
        if (d.clip.d) {
          cl.P = Sk.Path.MakeFromSVGString(d.clip.d);
          if (cl.P && cl.eo) cl.P.setFillType(1);
        }
        if (d.clip.s != null && els[d.clip.s]) { els[d.clip.s].n = cl; els[d.clip.s].K = Sk; }
        n.CL = cl;
      }
    }
    if (d.bm) {
      // mix-blend-mode: the group's layer composites against the backdrop
      // with the given Skia BlendMode on restore.
      const p = Sk.Paint();
      p.setBlendMode(d.bm);
      n.BM = p;
    }
    if (d.fx) {
      // Layer effects: stages of passes, innermost stage first. A pass is
      // null (source drawn unchanged) or a record with a layer paint `P`;
      // shadow/blur pass records also carry the parameter fields the FX ops
      // write, slot-linked like any other element.
      const st = [];
      for (let i = 0; i < d.fx.length; i++) {
        const row = [];
        for (let j = 0; j < d.fx[i].length; j++) {
          const p = d.fx[i][j];
          if (!p) {
            row.push(null);
          } else if (p.cf) {
            const q = Sk.Paint();
            q.setColorFilter(Sk.ColorFilter.MakeMatrix(p.cf));
            row.push({ P: q });
          } else if (p.cf2) {
            const q = Sk.Paint();
            q.setColorFilter(Sk.ColorFilter.MakeCompose(
              Sk.ColorFilter.MakeMatrix(p.cf2[0]),
              Sk.ColorFilter.MakeMatrix(p.cf2[1]),
            ));
            row.push({ P: q });
          } else if (p.sh) {
            const r = {
              k: 6, t: 2, P: Sk.Paint(),
              dx: p.dx || 0, dy: p.dy || 0, sd: p.sd || 0,
              c: p.c, fo: p.fo == null ? 1 : p.fo,
            };
            skFxPaint(r, Sk);
            if (p.sb != null && els[p.sb]) { els[p.sb].n = r; els[p.sb].K = Sk; }
            if (p.so != null && els[p.so]) { els[p.so].n = r; els[p.so].K = Sk; }
            if (p.sf != null && els[p.sf]) { els[p.sf].n = r; els[p.sf].K = Sk; }
            row.push(r);
          } else {
            const r = {
              k: 6, t: 1, P: Sk.Paint(),
              sx: p.sx || 0, sy: p.sy || 0, tm: p.tm || 0,
            };
            skFxPaint(r, Sk);
            if (p.s != null && els[p.s]) { els[p.s].n = r; els[p.s].K = Sk; }
            row.push(r);
          }
        }
        st.push(row);
      }
      n.FX = st;
    }
    if (d.cf) {
      const p = Sk.Paint();
      p.setColorFilter(Sk.ColorFilter.MakeMatrix(d.cf.m));
      const r = d.cf.r;
      n.CF = { P: p, R: { x: r[0], y: r[1], width: r[2], height: r[3] } };
    }
    if (d.mask) {
      // Composite the mask over the content layer with DstIn: content keeps
      // the mask's coverage. A luminance mask first maps luma into alpha.
      const p = Sk.Paint();
      p.setBlendMode(6);
      if (d.mask.luma) {
        p.setColorFilter(Sk.ColorFilter.MakeMatrix([
          0, 0, 0, 0, 0,
          0, 0, 0, 0, 0,
          0, 0, 0, 0, 0,
          0.2125, 0.7154, 0.0721, 0, 0,
        ]));
      }
      const mc = [];
      for (let i = 0; i < d.mask.c.length; i++) mc.push(skPrepare(d.mask.c[i], els, Sk));
      n.MK = { P: p, c: mc };
    }
    n.c = [];
    for (let i = 0; i < d.c.length; i++) n.c.push(skPrepare(d.c[i], els, Sk));
    return n;
  }
  if (d.k === 4) {
    // Embedded image: decode once at mount. The compiler bakes the box at
    // the asset's natural size, and lottie-web's `xMidYMid slice` fit is a
    // center-crop of the source to the box's aspect — exact here as a src
    // rect, even when the decoded bitmap disagrees with the declared size.
    const img = Sk.Image.MakeImageFromEncoded(Sk.Data.fromBase64(d.u));
    if (!img) throw new Error('ulottie: embedded image failed to decode');
    const sc = Math.max(d.w / img.width(), d.h / img.height());
    const sw = d.w / sc, sh = d.h / sc;
    n.IM = img;
    n.SRC = { x: (img.width() - sw) / 2, y: (img.height() - sh) / 2, width: sw, height: sh };
    n.DST = { x: 0, y: 0, width: d.w, height: d.h };
    n.P = Sk.Paint();
    return n;
  }
  // Shape: paint fields live flat on the record so the write point can
  // rebuild paints incrementally.
  n.eo = d.eo ? 1 : 0;
  const p = d.paint;
  n.f = p.f == null ? null : skGradRec(p.f, els, Sk, n);
  n.fo = p.fo == null ? null : p.fo;
  n.sc = p.sc == null ? null : skGradRec(p.sc, els, Sk, n);
  n.so = p.so == null ? null : p.so;
  n.sw = p.sw == null ? null : p.sw;
  n.cap = p.cap || 0;
  n.join = p.join || 0;
  n.ml = p.ml == null ? null : p.ml;
  n.da = p.da || null;
  n.doff = p.doff == null ? null : p.doff;
  n.po = p.po ? 1 : 0;
  n.FP = null;
  n.SP = null;
  n.R = { x: 0, y: 0, width: 0, height: 0 };
  if (n.k === 1) {
    n.P = d.d ? Sk.Path.MakeFromSVGString(d.d) : null;
    if (n.P && n.eo) n.P.setFillType(1);
  } else if (n.k === 2) {
    n.gx = d.x; n.gy = d.y; n.gw = d.w; n.gh = d.h;
    n.rx = d.rx || 0; n.ry = d.ry || 0;
    n.RR = { rect: n.R, rx: n.rx, ry: n.ry };
    skGeom(n);
  } else {
    n.cx = d.cx; n.cy = d.cy; n.rx = d.rx; n.ry = d.ry;
    skGeom(n);
  }
  skPaints(n, Sk);
  return n;
}

/**
 * A gradient paint descriptor → a live gradient record (`k: 4`), the value a
 * shape node's `f`/`sc` holds in place of a colour string. The gradient's
 * mutable fields live on `.g` (what `skGrad` builds the shader from) and
 * `.O` lists the owner shape nodes whose paints rebuild when a
 * GRADIENT/RAMP op writes. A gradient shared by two shapes resolves inline
 * twice with the same slots, so the second sight of a slotted descriptor
 * reuses the first's record instead of re-linking the slot away from it.
 * Bound stops link slim `k: 5` records that share `.g` and `.O`.
 */
function skGradRec(g, els, Sk, owner) { 'worklet';
  if (typeof g === 'string') return g;
  let probe = g.s == null ? null : g.s;
  if (probe == null) {
    for (let i = 0; i < g.st.length; i++) {
      if (g.st[i].length > 2) { probe = g.st[i][2]; break; }
    }
  }
  if (probe != null && els[probe] && els[probe].n) {
    els[probe].n.O.push(owner);
    return els[probe].n;
  }
  const st = [];
  const rec = {
    k: 4,
    g: {
      rad: g.rad ? 1 : 0,
      cx: g.cx || 0, cy: g.cy || 0, r: g.r || 0,
      x1: g.x1 || 0, y1: g.y1 || 0, x2: g.x2 || 0, y2: g.y2 || 0,
      gt: g.gt || null,
      st,
    },
    O: [owner],
  };
  for (let i = 0; i < g.st.length; i++) {
    st.push([g.st[i][0], g.st[i][1]]);
    if (g.st[i].length > 2 && els[g.st[i][2]]) {
      els[g.st[i][2]].n = { k: 5, g: rec.g, i, O: rec.O };
      els[g.st[i][2]].K = Sk;
    }
  }
  if (g.s != null && els[g.s]) { els[g.s].n = rec; els[g.s].K = Sk; }
  return rec;
}

/** Record one node (and its subtree) onto a canvas. */
function skDraw(c, n, Sk) { 'worklet';
  if (n.h) return;
  c.save();
  if (n.m) c.concat(n.m);
  if (n.k) {
    if (n.o < 1) {
      const p = n.OP || (n.OP = Sk.Paint());
      p.setAlphaf(n.o);
      c.saveLayer(p);
      skShape(c, n);
      c.restore();
    } else {
      skShape(c, n);
    }
    c.restore();
    return;
  }
  if (n.CL) {
    // An animated clip whose first `d` has not landed yet clips everything
    // out — matching an SVG <clipPath> with no shape.
    if (n.CL.P) c.clipPath(n.CL.P, 1, true);
    else c.clipRect({ x: 0, y: 0, width: 0, height: 0 }, 1, true);
  }
  if (n.CR) c.clipRect(n.CR, 1, true);
  let pops = 0;
  if (n.BM) {
    // Blend outermost: everything the group draws — clipped, filtered,
    // masked — composites against the backdrop in one blended restore.
    c.saveLayer(n.BM);
    pops++;
  }
  if (n.CF) {
    // The filter region clips its output (userSpaceOnUse, resolved at
    // compile time); the color matrix rides the layer's restore paint.
    c.clipRect(n.CF.R, 1, true);
    c.saveLayer(n.CF.P);
    pops++;
  }
  if (n.o < 1) {
    const p = n.OP || (n.OP = Sk.Paint());
    p.setAlphaf(n.o);
    c.saveLayer(p);
    pops++;
  }
  if (n.MK) { c.saveLayer(); pops++; }
  // skDraw is passed down as a value rather than called by name from skFx:
  // the worklets babel plugin captures a worklet's free variables when its
  // factory runs at module evaluation, so a skDraw↔skFx name cycle leaves
  // whichever is defined second captured as `undefined` on the UI runtime.
  if (n.FX) skFx(c, n, Sk, n.FX.length - 1, skDraw);
  else for (let i = 0; i < n.c.length; i++) skDraw(c, n.c[i], Sk);
  if (n.MK) {
    c.saveLayer(n.MK.P);
    for (let i = 0; i < n.MK.c.length; i++) skDraw(c, n.MK.c[i], Sk);
    c.restore();
  }
  while (pops--) c.restore();
  c.restore();
}

/**
 * Draw a group's children through its effect stages. Stage `si` re-draws
 * the running content — stage `si - 1`'s output, down to the raw children —
 * once per pass: a null pass draws it plain, a paint pass wraps it in a
 * layer whose restore applies the pass's colour or image filter. SVG's
 * sequential primitive chain, as nested Skia layers.
 */
function skFx(c, n, Sk, si, draw) { 'worklet';
  if (si < 0) {
    for (let i = 0; i < n.c.length; i++) draw(c, n.c[i], Sk);
    return;
  }
  const row = n.FX[si];
  for (let i = 0; i < row.length; i++) {
    const p = row[i];
    if (p) {
      c.saveLayer(p.P);
      skFx(c, n, Sk, si - 1, draw);
      c.restore();
    } else {
      skFx(c, n, Sk, si - 1, draw);
    }
  }
}

/**
 * The two styled draws of one shape. `paint-order="stroke"` — the rn-svg
 * target's one documented degradation — is exact here: the stroke draw
 * simply issues first.
 */
function skShape(c, n) { 'worklet';
  if (n.k === 4) {
    c.drawImageRect(n.IM, n.SRC, n.DST, n.P);
    return;
  }
  const F = n.FP, S = n.SP;
  if (n.po && S) {
    skGeomDraw(c, n, S);
    if (F) skGeomDraw(c, n, F);
    return;
  }
  if (F) skGeomDraw(c, n, F);
  if (S) skGeomDraw(c, n, S);
}

/** One geometry draw with one paint. */
function skGeomDraw(c, n, p) { 'worklet';
  if (n.k === 1) {
    if (n.P) c.drawPath(n.P, p);
  } else if (n.k === 2) {
    if (n.rx || n.ry) {
      const rr = n.RR;
      rr.rx = n.rx; rr.ry = n.ry;
      c.drawRRect(rr, p);
    } else {
      c.drawRect(n.R, p);
    }
  } else {
    c.drawOval(n.R, p);
  }
}
// μLottie Skia mount — `mountRn`'s data half plus the prepared draw tree.
//
// The clock/gate/decode machinery is target-agnostic and stays `mountRn`'s
// byte for byte; this wrapper only prepares the display list against the
// caller's Skia factory and hands back the same instance record with one
// extra member: `draw(canvas)`, which records the current node state. The
// `draw` closure is created here at mount time on whichever runtime called
// `init`, so it needs no own 'worklet' directive — `skDraw` carries one.


function mountSkia(D, P, A, N, ext, Sk, dl) { 'worklet';
  const h = mountRn(D, P, A, N, ext);
  const x = skPrepare(dl, h.els, Sk);
  h.draw = function (c) { skDraw(c, x, Sk); };
  return h;
}
function P0(x, B, e, l, q, a) { 'worklet'; return [bDisplay(x, B[0], e, l, q, a), bShape(x, B[1], e, l, q, a)]; }
function A0(x, S) { 'worklet'; oDisplay(x, S[0]); oShape(x, S[1]); }

const D = "0gjl70gthg10q10s3mo60000800gt7gt7qp20sv4gt7qp20qo4gt7qp20ov4gt760i2ug1m1ig1amf60g5u4u4ghn2gvl5gtk8gvgs3gtvu3gruh4k34uu2pfuu2hgqs1mg14aq10oc6mj140oju30oc6002u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q822u6s7q82mg14k1k20oc4mg14aq10oc42ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q822ml1km1q82mg14g2g30oc2mg14m1m20oc22qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q822qj2ok2q82mg14s2s30oc2mg14i2i30oc22uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q822uh3si3q82ga26444244444444444444264442444444444444442644424444444444444426444244444444444444200000000000000000000666666666666666666664444444444444444444422222222222222222222i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6i6u8o9iasambgcqckdudoeifsfmg1gh1qh1ki1ui1oj1ik1sk1in1sn1mo1gp1qp1kq1uq1or1is1ss1mt1gu1qu1kv1uv1og2ih2sh2mi2gj2ml2gm2qm2kn2un2oo2ip2sp2mq2gr2qr2ks2us2ot2iu2su2mv2gg3qg3kh3qj3kk3uk3ol3im3sm3mn3go3qo3kp3up3oq3ir3sr3ms3gt3qt3ku3uu3ov34s4ig4";

export const dl =
{ k: 0, c: [
  { k: 0, clip: { r: [0, 0, 200, 200] }, c: [
    { k: 0, m: [0.7, 0, 47.11, 0, 0.7, 52.19, 0, 0, 1], c: [
      { k: 0, m: [-0.97815, 0.20791, 0, -0.20791, -0.97815, 0, 0, 0, 1], c: [
        { k: 1, s: 3, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
      ] },
      { k: 0, m: [-0.80902, -0.58779, 0, 0.58779, -0.80902, 0, 0, 0, 1], c: [
        { k: 1, s: 5, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
      ] },
      { k: 0, m: [-0.10453, -0.99452, 0, 0.99452, -0.10453, 0, 0, 0, 1], c: [
        { k: 1, s: 7, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
      ] },
      { k: 0, m: [0.66913, -0.74314, 0, 0.74314, 0.66913, 0, 0, 0, 1], c: [
        { k: 1, s: 9, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
      ] },
      { k: 1, s: 10, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } },
      { k: 0, m: [0.66913, 0.74314, 0, -0.74314, 0.66913, 0, 0, 0, 1], c: [
        { k: 1, s: 12, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
      ] },
      { k: 0, m: [-0.10453, 0.99452, 0, -0.99452, -0.10453, 0, 0, 0, 1], c: [
        { k: 1, s: 14, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
      ] },
      { k: 0, m: [-0.80902, 0.58779, 0, -0.58779, -0.80902, 0, 0, 0, 1], c: [
        { k: 1, s: 16, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
      ] },
      { k: 0, m: [-0.97815, -0.20791, 0, 0.20791, -0.97815, 0, 0, 0, 1], c: [
        { k: 1, s: 18, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
      ] },
      { k: 0, m: [-0.5, -0.86603, 0, 0.86603, -0.5, 0, 0, 0, 1], c: [
        { k: 1, s: 20, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
      ] },
      { k: 0, m: [0.30902, -0.95106, 0, 0.95106, 0.30902, 0, 0, 0, 1], c: [
        { k: 1, s: 22, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
      ] },
      { k: 0, m: [0.91355, -0.40674, 0, 0.40674, 0.91355, 0, 0, 0, 1], c: [
        { k: 1, s: 24, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
      ] },
      { k: 0, m: [0.91355, 0.40674, 0, -0.40674, 0.91355, 0, 0, 0, 1], c: [
        { k: 1, s: 26, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
      ] },
      { k: 0, m: [0.30902, 0.95106, 0, -0.95106, 0.30902, 0, 0, 0, 1], c: [
        { k: 1, s: 28, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
      ] },
      { k: 0, m: [-0.5, 0.86603, 0, -0.86603, -0.5, 0, 0, 0, 1], c: [
        { k: 1, s: 30, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
      ] },
      { k: 0, m: [-0.97815, 0.20791, 0, -0.20791, -0.97815, 0, 0, 0, 1], c: [
        { k: 1, s: 32, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
      ] },
      { k: 0, m: [-0.80902, -0.58779, 0, 0.58779, -0.80902, 0, 0, 0, 1], c: [
        { k: 1, s: 34, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
      ] },
      { k: 0, m: [-0.10453, -0.99452, 0, 0.99452, -0.10453, 0, 0, 0, 1], c: [
        { k: 1, s: 36, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
      ] },
      { k: 0, m: [0.66913, -0.74314, 0, 0.74314, 0.66913, 0, 0, 0, 1], c: [
        { k: 1, s: 38, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
      ] },
      { k: 1, s: 39, hd: 1, paint: { f: '#f00', cap: 1, sc: '#9661ba', sw: 5 } }
    ] },
    { k: 0, s: 40, m: [0.7, 0, 106.11, 0, 0.7, 166.19, 0, 0, 1], hd: 1, c: [
      { k: 0, m: [-0.97815, 0.20791, 0, -0.20791, -0.97815, 0, 0, 0, 1], c: [
        { k: 1, s: 42, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
      ] },
      { k: 0, m: [-0.80902, -0.58779, 0, 0.58779, -0.80902, 0, 0, 0, 1], c: [
        { k: 1, s: 44, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
      ] },
      { k: 0, m: [-0.10453, -0.99452, 0, 0.99452, -0.10453, 0, 0, 0, 1], c: [
        { k: 1, s: 46, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
      ] },
      { k: 0, m: [0.66913, -0.74314, 0, 0.74314, 0.66913, 0, 0, 0, 1], c: [
        { k: 1, s: 48, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
      ] },
      { k: 1, s: 49, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } },
      { k: 0, m: [0.66913, 0.74314, 0, -0.74314, 0.66913, 0, 0, 0, 1], c: [
        { k: 1, s: 51, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
      ] },
      { k: 0, m: [-0.10453, 0.99452, 0, -0.99452, -0.10453, 0, 0, 0, 1], c: [
        { k: 1, s: 53, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
      ] },
      { k: 0, m: [-0.80902, 0.58779, 0, -0.58779, -0.80902, 0, 0, 0, 1], c: [
        { k: 1, s: 55, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
      ] },
      { k: 0, m: [-0.97815, -0.20791, 0, 0.20791, -0.97815, 0, 0, 0, 1], c: [
        { k: 1, s: 57, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
      ] },
      { k: 0, m: [-0.5, -0.86603, 0, 0.86603, -0.5, 0, 0, 0, 1], c: [
        { k: 1, s: 59, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
      ] },
      { k: 0, m: [0.30902, -0.95106, 0, 0.95106, 0.30902, 0, 0, 0, 1], c: [
        { k: 1, s: 61, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
      ] },
      { k: 0, m: [0.91355, -0.40674, 0, 0.40674, 0.91355, 0, 0, 0, 1], c: [
        { k: 1, s: 63, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
      ] },
      { k: 0, m: [0.91355, 0.40674, 0, -0.40674, 0.91355, 0, 0, 0, 1], c: [
        { k: 1, s: 65, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
      ] },
      { k: 0, m: [0.30902, 0.95106, 0, -0.95106, 0.30902, 0, 0, 0, 1], c: [
        { k: 1, s: 67, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
      ] },
      { k: 0, m: [-0.5, 0.86603, 0, -0.86603, -0.5, 0, 0, 0, 1], c: [
        { k: 1, s: 69, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
      ] },
      { k: 0, m: [-0.97815, 0.20791, 0, -0.20791, -0.97815, 0, 0, 0, 1], c: [
        { k: 1, s: 71, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
      ] },
      { k: 0, m: [-0.80902, -0.58779, 0, 0.58779, -0.80902, 0, 0, 0, 1], c: [
        { k: 1, s: 73, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
      ] },
      { k: 0, m: [-0.10453, -0.99452, 0, 0.99452, -0.10453, 0, 0, 0, 1], c: [
        { k: 1, s: 75, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
      ] },
      { k: 0, m: [0.66913, -0.74314, 0, 0.74314, 0.66913, 0, 0, 0, 1], c: [
        { k: 1, s: 77, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
      ] },
      { k: 1, s: 78, paint: { f: '#f00', cap: 1, sc: '#40c9ff', sw: 5 } }
    ] },
    { k: 0, s: 79, m: [0.7, 0, 45.11, 0, 0.7, 111.19, 0, 0, 1], hd: 1, c: [
      { k: 0, m: [-0.97815, 0.20791, 0, -0.20791, -0.97815, 0, 0, 0, 1], c: [
        { k: 1, s: 81, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
      ] },
      { k: 0, m: [-0.80902, -0.58779, 0, 0.58779, -0.80902, 0, 0, 0, 1], c: [
        { k: 1, s: 83, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
      ] },
      { k: 0, m: [-0.10453, -0.99452, 0, 0.99452, -0.10453, 0, 0, 0, 1], c: [
        { k: 1, s: 85, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
      ] },
      { k: 0, m: [0.66913, -0.74314, 0, 0.74314, 0.66913, 0, 0, 0, 1], c: [
        { k: 1, s: 87, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
      ] },
      { k: 1, s: 88, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } },
      { k: 0, m: [0.66913, 0.74314, 0, -0.74314, 0.66913, 0, 0, 0, 1], c: [
        { k: 1, s: 90, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
      ] },
      { k: 0, m: [-0.10453, 0.99452, 0, -0.99452, -0.10453, 0, 0, 0, 1], c: [
        { k: 1, s: 92, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
      ] },
      { k: 0, m: [-0.80902, 0.58779, 0, -0.58779, -0.80902, 0, 0, 0, 1], c: [
        { k: 1, s: 94, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
      ] },
      { k: 0, m: [-0.97815, -0.20791, 0, 0.20791, -0.97815, 0, 0, 0, 1], c: [
        { k: 1, s: 96, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
      ] },
      { k: 0, m: [-0.5, -0.86603, 0, 0.86603, -0.5, 0, 0, 0, 1], c: [
        { k: 1, s: 98, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
      ] },
      { k: 0, m: [0.30902, -0.95106, 0, 0.95106, 0.30902, 0, 0, 0, 1], c: [
        { k: 1, s: 100, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
      ] },
      { k: 0, m: [0.91355, -0.40674, 0, 0.40674, 0.91355, 0, 0, 0, 1], c: [
        { k: 1, s: 102, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
      ] },
      { k: 0, m: [0.91355, 0.40674, 0, -0.40674, 0.91355, 0, 0, 0, 1], c: [
        { k: 1, s: 104, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
      ] },
      { k: 0, m: [0.30902, 0.95106, 0, -0.95106, 0.30902, 0, 0, 0, 1], c: [
        { k: 1, s: 106, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
      ] },
      { k: 0, m: [-0.5, 0.86603, 0, -0.86603, -0.5, 0, 0, 0, 1], c: [
        { k: 1, s: 108, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
      ] },
      { k: 0, m: [-0.97815, 0.20791, 0, -0.20791, -0.97815, 0, 0, 0, 1], c: [
        { k: 1, s: 110, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
      ] },
      { k: 0, m: [-0.80902, -0.58779, 0, 0.58779, -0.80902, 0, 0, 0, 1], c: [
        { k: 1, s: 112, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
      ] },
      { k: 0, m: [-0.10453, -0.99452, 0, 0.99452, -0.10453, 0, 0, 0, 1], c: [
        { k: 1, s: 114, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
      ] },
      { k: 0, m: [0.66913, -0.74314, 0, 0.74314, 0.66913, 0, 0, 0, 1], c: [
        { k: 1, s: 116, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
      ] },
      { k: 1, s: 117, paint: { f: '#f00', cap: 1, sc: '#ed6680', sw: 5 } }
    ] },
    { k: 0, s: 118, m: [0.7, 0, 143.11, 0, 0.7, 56.19, 0, 0, 1], hd: 1, c: [
      { k: 0, m: [-0.97815, 0.20791, 0, -0.20791, -0.97815, 0, 0, 0, 1], c: [
        { k: 1, s: 120, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
      ] },
      { k: 0, m: [-0.80902, -0.58779, 0, 0.58779, -0.80902, 0, 0, 0, 1], c: [
        { k: 1, s: 122, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
      ] },
      { k: 0, m: [-0.10453, -0.99452, 0, 0.99452, -0.10453, 0, 0, 0, 1], c: [
        { k: 1, s: 124, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
      ] },
      { k: 0, m: [0.66913, -0.74314, 0, 0.74314, 0.66913, 0, 0, 0, 1], c: [
        { k: 1, s: 126, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
      ] },
      { k: 1, s: 127, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } },
      { k: 0, m: [0.66913, 0.74314, 0, -0.74314, 0.66913, 0, 0, 0, 1], c: [
        { k: 1, s: 129, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
      ] },
      { k: 0, m: [-0.10453, 0.99452, 0, -0.99452, -0.10453, 0, 0, 0, 1], c: [
        { k: 1, s: 131, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
      ] },
      { k: 0, m: [-0.80902, 0.58779, 0, -0.58779, -0.80902, 0, 0, 0, 1], c: [
        { k: 1, s: 133, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
      ] },
      { k: 0, m: [-0.97815, -0.20791, 0, 0.20791, -0.97815, 0, 0, 0, 1], c: [
        { k: 1, s: 135, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
      ] },
      { k: 0, m: [-0.5, -0.86603, 0, 0.86603, -0.5, 0, 0, 0, 1], c: [
        { k: 1, s: 137, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
      ] },
      { k: 0, m: [0.30902, -0.95106, 0, 0.95106, 0.30902, 0, 0, 0, 1], c: [
        { k: 1, s: 139, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
      ] },
      { k: 0, m: [0.91355, -0.40674, 0, 0.40674, 0.91355, 0, 0, 0, 1], c: [
        { k: 1, s: 141, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
      ] },
      { k: 0, m: [0.91355, 0.40674, 0, -0.40674, 0.91355, 0, 0, 0, 1], c: [
        { k: 1, s: 143, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
      ] },
      { k: 0, m: [0.30902, 0.95106, 0, -0.95106, 0.30902, 0, 0, 0, 1], c: [
        { k: 1, s: 145, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
      ] },
      { k: 0, m: [-0.5, 0.86603, 0, -0.86603, -0.5, 0, 0, 0, 1], c: [
        { k: 1, s: 147, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
      ] },
      { k: 0, m: [-0.97815, 0.20791, 0, -0.20791, -0.97815, 0, 0, 0, 1], c: [
        { k: 1, s: 149, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
      ] },
      { k: 0, m: [-0.80902, -0.58779, 0, 0.58779, -0.80902, 0, 0, 0, 1], c: [
        { k: 1, s: 151, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
      ] },
      { k: 0, m: [-0.10453, -0.99452, 0, 0.99452, -0.10453, 0, 0, 0, 1], c: [
        { k: 1, s: 153, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
      ] },
      { k: 0, m: [0.66913, -0.74314, 0, 0.74314, 0.66913, 0, 0, 0, 1], c: [
        { k: 1, s: 155, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
      ] },
      { k: 1, s: 156, paint: { f: '#f00', cap: 1, sc: '#f3a54d', sw: 5 } }
    ] }
  ] }
] };

export const meta = { fr: 15, ip: 0, op: 33, width: 200, height: 200 };
export const init = (Sk) => { 'worklet'; return mountSkia(D, P0, A0, 157, null, Sk, dl); };
