// Generated by ulottie — unminified for review; not what ships.
// Object keys are sorted here for stable diffs; emitted order differs.
// mode: extern
// caps: SHAPE | KEYFRAMES | EASING | PATH_KF | PATH_D | EXPRESSIONS | LAYER_TX

import { mount } from './runtime/core.js';
import { makeExpr } from './runtime/expr.js';
import { bShape } from './runtime/ops/shape.js';
import { bLayerTx } from './runtime/ops/layer.js';
const B=[,,,,bShape,,,,,,bLayerTx];

const M =
  '<svg viewBox="0 0 800 600" width="100%" height="100%" preserveAspectRatio="xMidYMid meet" style="overflow:hidden">' +
    '<g transform="matrix(1,0,0,1,400,300)">' +
      '<path fill="none" stroke="#1a221b" stroke-width="4"/>' +
    '</g>' +
    '<g>' +
      '<g transform="matrix(1,0,0,1,225.56,-58)">' +
        '<g transform="matrix(1,0,0,1,-226.38,67.81)">' +
          '<rect x="-3.875" y="-2.438" width="7.75" height="4.875" rx="1" ry="1" fill="#3d3d3d"/>' +
        '</g>' +
        '<path d="M-224,72C-228,72-229.5,72.5-229.5,72.5C-229.5,72.5-236,75.5-236,80.5C-236,85.5-231.5,97-227.5,98.5C-223.5,100-218,85.5-217.5,82.5C-217,79.5-220,72-224,72Z" fill="#0c9cf8"/>' +
      '</g>' +
    '</g>' +
    '<g>' +
      '<g transform="matrix(1,0,0,1,226.85,-57.99)">' +
        '<g transform="matrix(1,0,0,1,-226.38,67.81)">' +
          '<rect x="-3.875" y="-2.438" width="7.75" height="4.875" rx="1" ry="1" fill="#3d3d3d"/>' +
        '</g>' +
        '<path d="M-224,72C-228,72-229.5,72.5-229.5,72.5C-229.5,72.5-236,75.5-236,80.5C-236,85.5-231.5,97-227.5,98.5C-223.5,100-218,85.5-217.5,82.5C-217,79.5-220,72-224,72Z" fill="#f8f50d"/>' +
      '</g>' +
    '</g>' +
    '<g>' +
      '<g transform="matrix(1,0,0,1,231.43,-58)">' +
        '<g transform="matrix(1,0,0,1,-226.38,67.81)">' +
          '<rect x="-3.875" y="-2.438" width="7.75" height="4.875" rx="1" ry="1" fill="#3d3d3d"/>' +
        '</g>' +
        '<path d="M-224,72C-228,72-229.5,72.5-229.5,72.5C-229.5,72.5-236,75.5-236,80.5C-236,85.5-231.5,97-227.5,98.5C-223.5,100-218,85.5-217.5,82.5C-217,79.5-220,72-224,72Z" fill="#0df84f"/>' +
      '</g>' +
    '</g>' +
    '<g>' +
      '<g transform="matrix(1,0,0,1,224.18,-60)">' +
        '<g transform="matrix(1,0,0,1,-226.38,67.81)">' +
          '<rect x="-3.875" y="-2.438" width="7.75" height="4.875" rx="1" ry="1" fill="#3d3d3d"/>' +
        '</g>' +
        '<path d="M-224,72C-228,72-229.5,72.5-229.5,72.5C-229.5,72.5-236,75.5-236,80.5C-236,85.5-231.5,97-227.5,98.5C-223.5,100-218,85.5-217.5,82.5C-217,79.5-220,72-224,72Z" fill="#f82c11"/>' +
      '</g>' +
    '</g>' +
    '<g/>' +
    '<g>' +
      '<g transform="matrix(1,0,0,1,222.11,-59.24)">' +
        '<g transform="matrix(1,0,0,1,-226.38,67.81)">' +
          '<rect x="-3.875" y="-2.438" width="7.75" height="4.875" rx="1" ry="1" fill="#3d3d3d"/>' +
        '</g>' +
        '<path d="M-224,72C-228,72-229.5,72.5-229.5,72.5C-229.5,72.5-236,75.5-236,80.5C-236,85.5-231.5,97-227.5,98.5C-223.5,100-218,85.5-217.5,82.5C-217,79.5-220,72-224,72Z" fill="#f88311"/>' +
      '</g>' +
    '</g>' +
  '</svg>';

const D = {
  "b": [
    [10,23,0],
    [10,-1,2],
    [10,-5,2],
    [10,-5,1],
    [10,-5,1],
    [10,-5,1],
    [
      4,
      -1,
      [
        0,
        {
          "f": {"i":[0,0,-178,0,0,0],"o":[0,0,178,0,0,0],"v":[-303,-24,-3,-24,328,-24]},
          "l": 8,
          "x": 5
        }
      ],
      null
    ]
  ],
  "f": 60,
  "o": 300,
  "s": ["wire"],
  "y": [
    {
      "ef": [
        {
          "ef": [
            {"mn":"Pseudo/ADBE Trace Path-0001","nm":"Progress","p":{"f":2,"l":0,"x":2}},
            {"mn":"Pseudo/ADBE Trace Path-0002","nm":"Loop","ty":7,"v":1.0}
          ],
          "mn": "Pseudo/ADBE Trace Path",
          "nm": "Trace Path"
        }
      ],
      "i": 1,
      "o": 0,
      "p": {"f":[400,300,0],"l":0,"x":0},
      "r": {"f":0,"l":0,"x":1}
    },
    {"i":2,"o":0,"p":[728,276,0]},
    {
      "ef": [
        {
          "ef": [{"mn":"ADBE Slider Control-0001","nm":"Slider","p":{"f":20,"l":2,"x":4}}],
          "mn": "ADBE Slider Control",
          "nm": "Position - Overshoot"
        },
        {
          "ef": [{"mn":"ADBE Slider Control-0001","nm":"Slider","p":{"f":40,"l":2,"x":4}}],
          "mn": "ADBE Slider Control",
          "nm": "Position - Bounce"
        },
        {
          "ef": [{"mn":"ADBE Slider Control-0001","nm":"Slider","p":{"f":40,"l":2,"x":4}}],
          "mn": "ADBE Slider Control",
          "nm": "Position - Friction"
        }
      ],
      "i": 3,
      "o": 0,
      "p": {
        "f": {
          "d": 3,
          "k": 1,
          "t": [0,60,180,190],
          "v": [397,276,0,397,397,0,397,397,0,397,276,0],
          "z": [1,0,2]
        },
        "l": 2,
        "x": 3
      }
    },
    {"i":4,"o":0,"p":[97,276,0]},
    {
      "ef": [
        {
          "ef": [
            {"mn":"Pseudo/ADBE Trace Path-0001","nm":"Progress","p":{"f":97,"l":4,"x":2}},
            {"mn":"Pseudo/ADBE Trace Path-0002","nm":"Loop","ty":7,"v":1.0}
          ],
          "mn": "Pseudo/ADBE Trace Path",
          "nm": "Trace Path"
        }
      ],
      "i": 5,
      "o": 0,
      "p": {"f":[400,300,0],"l":4,"x":0},
      "r": {"f":0,"l":4,"x":1}
    },
    {
      "ef": [
        {
          "ef": [
            {"mn":"Pseudo/ADBE Trace Path-0001","nm":"Progress","p":{"f":74,"l":5,"x":2}},
            {"mn":"Pseudo/ADBE Trace Path-0002","nm":"Loop","ty":7,"v":1.0}
          ],
          "mn": "Pseudo/ADBE Trace Path",
          "nm": "Trace Path"
        }
      ],
      "i": 6,
      "o": 0,
      "p": {"f":[400,300,0],"l":5,"x":0},
      "r": {"f":0,"l":5,"x":1}
    },
    {
      "ef": [
        {
          "ef": [
            {"mn":"Pseudo/ADBE Trace Path-0001","nm":"Progress","p":{"f":48,"l":6,"x":2}},
            {"mn":"Pseudo/ADBE Trace Path-0002","nm":"Loop","ty":7,"v":1.0}
          ],
          "mn": "Pseudo/ADBE Trace Path",
          "nm": "Trace Path"
        }
      ],
      "i": 7,
      "o": 0,
      "p": {"f":[400,300,0],"l":6,"x":0},
      "r": {"f":0,"l":6,"x":1}
    },
    {
      "ef": [
        {
          "ef": [
            {"mn":"Pseudo/ADBE Trace Path-0001","nm":"Progress","p":{"f":24,"l":7,"x":2}},
            {"mn":"Pseudo/ADBE Trace Path-0002","nm":"Loop","ty":7,"v":1.0}
          ],
          "mn": "Pseudo/ADBE Trace Path",
          "nm": "Trace Path"
        }
      ],
      "i": 8,
      "o": 0,
      "p": {"f":[400,300,0],"l":7,"x":0},
      "r": {"f":0,"l":7,"x":1}
    },
    {
      "ef": [
        {
          "ef": [{"mn":"ADBE Layer Control-0001","nm":"Layer","ty":10,"v":4.0}],
          "mn": "ADBE Layer Control",
          "nm": "Shape Layer 1: Path 1 [1.1.0]"
        },
        {
          "ef": [{"mn":"ADBE Layer Control-0001","nm":"Layer","ty":10,"v":3.0}],
          "mn": "ADBE Layer Control",
          "nm": "Shape Layer 1: Path 1 [1.1.1]"
        },
        {
          "ef": [{"mn":"ADBE Layer Control-0001","nm":"Layer","ty":10,"v":2.0}],
          "mn": "ADBE Layer Control",
          "nm": "Shape Layer 1: Path 1 [1.1.2]"
        }
      ],
      "h": {"f":{"i":[0,0,-178,0,0,0],"o":[0,0,178,0,0,0],"v":[-303,-24,-3,-24,328,-24]},"l":8,"x":5},
      "i": 9,
      "n": 0,
      "p": [400,300,0]
    },
    {
      "a": [-226.723,65.375,0],
      "ef": [
        {
          "ef": [
            {"mn":"Pseudo/WayfinderFollower-0001","nm":"Position","v":100.0},
            {"mn":"Pseudo/WayfinderFollower-0002","nm":"Offset","v":0.0}
          ],
          "mn": "Pseudo/WayfinderFollower",
          "nm": "Wayfinder Follower"
        }
      ],
      "h": {
        "c": 1,
        "i": [4,0,0,0,0,-5,-4,-1.5,-0.5,3],
        "o": [-4,0,0,0,0,5,4,1.5,0.5,-3],
        "v": [-224,72,-229.5,72.5,-236,80.5,-227.5,98.5,-217.5,82.5]
      },
      "i": 10,
      "p": [-2.547,5.375,0],
      "pr": 4
    },
    {
      "a": [-226.723,65.375,0],
      "ef": [
        {
          "ef": [
            {"mn":"Pseudo/WayfinderFollower-0001","nm":"Position","v":80.0},
            {"mn":"Pseudo/WayfinderFollower-0002","nm":"Offset","v":0.0}
          ],
          "mn": "Pseudo/WayfinderFollower",
          "nm": "Wayfinder Follower"
        }
      ],
      "h": {
        "c": 1,
        "i": [4,0,0,0,0,-5,-4,-1.5,-0.5,3],
        "o": [-4,0,0,0,0,5,4,1.5,0.5,-3],
        "v": [-224,72,-229.5,72.5,-236,80.5,-227.5,98.5,-217.5,82.5]
      },
      "i": 11,
      "p": [4.711,7.375,0],
      "pr": 5
    },
    {
      "a": [-226.723,65.375,0],
      "ef": [
        {
          "ef": [
            {"mn":"Pseudo/WayfinderFollower-0001","nm":"Position","v":52.0},
            {"mn":"Pseudo/WayfinderFollower-0002","nm":"Offset","v":0.0}
          ],
          "mn": "Pseudo/WayfinderFollower",
          "nm": "Wayfinder Follower"
        }
      ],
      "h": {
        "c": 1,
        "i": [4,0,0,0,0,-5,-4,-1.5,-0.5,3],
        "o": [-4,0,0,0,0,5,4,1.5,0.5,-3],
        "v": [-224,72,-229.5,72.5,-236,80.5,-227.5,98.5,-217.5,82.5]
      },
      "i": 12,
      "p": [0.124,7.383,0],
      "pr": 6
    },
    {
      "a": [-226.723,65.375,0],
      "ef": [
        {
          "ef": [
            {"mn":"Pseudo/WayfinderFollower-0001","nm":"Position","v":31.0},
            {"mn":"Pseudo/WayfinderFollower-0002","nm":"Offset","v":0.0}
          ],
          "mn": "Pseudo/WayfinderFollower",
          "nm": "Wayfinder Follower"
        }
      ],
      "h": {
        "c": 1,
        "i": [4,0,0,0,0,-5,-4,-1.5,-0.5,3],
        "o": [-4,0,0,0,0,5,4,1.5,0.5,-3],
        "v": [-224,72,-229.5,72.5,-236,80.5,-227.5,98.5,-217.5,82.5]
      },
      "i": 13,
      "p": [-1.161,7.375,0],
      "pr": 7
    },
    {
      "a": [-226.723,65.375,0],
      "h": {
        "c": 1,
        "i": [4,0,0,0,0,-5,-4,-1.5,-0.5,3],
        "o": [-4,0,0,0,0,5,4,1.5,0.5,-3],
        "v": [-224,72,-229.5,72.5,-236,80.5,-227.5,98.5,-217.5,82.5]
      },
      "i": 14,
      "p": [-4.616,6.133,0],
      "pr": 0
    }
  ],
  "z": [[0,0,1,1],[0.92,0,0.833,0.833],[0.53,0,0.833,0.833]]
};

const E = [
  function(value, thisLayer, thisProperty, frame, ctx) {
    const { thisComp, div } = ctx;
    var $bm_rt;
    var pathLayer = thisComp.layer('wire');
    var progress = div(thisLayer.effect('Pseudo/ADBE Trace Path')('Pseudo/ADBE Trace Path-0001'), 100);
    var pathToTrace = pathLayer('ADBE Root Vectors Group')(1)('ADBE Vectors Group')(1)('ADBE Vector Shape');
    $bm_rt = pathLayer.toComp(pathToTrace.pointOnPath(progress));
    return $bm_rt;
  },
  function(value, thisLayer, thisProperty, frame, ctx) {
    const { thisComp, div, radiansToDegrees } = ctx;
    var $bm_rt;
    var pathToTrace = thisComp.layer('wire')('ADBE Root Vectors Group')(1)('ADBE Vectors Group')(1)('ADBE Vector Shape');
    var progress = div(thisLayer.effect('Pseudo/ADBE Trace Path')('Pseudo/ADBE Trace Path-0001'), 100);
    var pathTan = pathToTrace.tangentOnPath(progress);
    $bm_rt = radiansToDegrees(Math.atan2(pathTan[1], pathTan[0]));
    return $bm_rt;
  },
  function(value, thisLayer, thisProperty, frame, ctx) {
    var $bm_rt;
    if (thisProperty.propertyGroup(1)('Pseudo/ADBE Trace Path-0002') == true && thisProperty.numKeys > 1) {
        $bm_rt = thisProperty.loopOut('cycle');
    } else {
        $bm_rt = value;
    }
    return $bm_rt;
  },
  function(value, thisLayer, thisProperty, frame, ctx) {
    const { thisComp, sum, sub, mul, div } = ctx;
    const time = frame / ctx.frameRate;
    const effect = (n) => (thisLayer ? thisLayer.effect(n) : (() => 0));
    const numKeys = thisProperty?.numKeys ?? 0;
    const nearestKey = thisProperty?.nearestKey ? thisProperty.nearestKey.bind(thisProperty) : ((t) => ({ index: 1, time: 0 }));
    const key = thisProperty?.key ? thisProperty.key.bind(thisProperty) : ((n) => ({ time: 0, value: 0, index: n }));
    const velocityAtTime = thisProperty?.velocityAtTime ? thisProperty.velocityAtTime.bind(thisProperty) : ((t) => 0);
    var $bm_rt;
    var amp, freq, decay, n, t, v;
    try {
        amp = div(effect('Position - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = div(effect('Position - Bounce')('ADBE Slider Control-0001'), 20), decay = div(effect('Position - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : time - key(n).time, $bm_rt = 0 < n ? (v = velocityAtTime(sub(key(n).time, div(thisComp.frameDuration, 10))), sum(value, div(mul(mul(div(v, 100), amp), Math.sin(mul(mul(mul(freq, t), 2), Math.PI))), Math.exp(mul(decay, t))))) : value;
    } catch (e$$4) {
        $bm_rt = value = value;
    }
    return $bm_rt;
  },
  function(value, thisLayer, thisProperty, frame, ctx) {
    const { clamp } = ctx;
    var $bm_rt;
    $bm_rt = clamp(value, 0, 100);
    return $bm_rt;
  },
  function(value, thisLayer, thisProperty, frame, ctx) {
    const { createPath } = ctx;
    const effect = (n) => (thisLayer ? thisLayer.effect(n) : (() => 0));
    const fromCompToSurface = (pt) => (thisLayer ? thisLayer.fromCompToSurface(pt) : pt);
    var $bm_rt;
    var nullLayerNames = [
            'Shape Layer 1: Path 1 [1.1.0]',
            'Shape Layer 1: Path 1 [1.1.1]',
            'Shape Layer 1: Path 1 [1.1.2]'
        ];
    var origPath = thisProperty;
    var origPoints = origPath.points();
    var origInTang = origPath.inTangents();
    var origOutTang = origPath.outTangents();
    var getNullLayers = [];
    for (var i = 0; i < nullLayerNames.length; i++) {
        try {
            getNullLayers.push(effect(nullLayerNames[i])('ADBE Layer Control-0001'));
        } catch (err) {
            getNullLayers.push(null);
        }
    }
    for (var i = 0; i < getNullLayers.length; i++) {
        if (getNullLayers[i] != null && getNullLayers[i].index != thisLayer.index) {
            origPoints[i] = fromCompToSurface(getNullLayers[i].toComp(getNullLayers[i].anchorPoint));
        }
    }
    $bm_rt = createPath(origPoints, origInTang, origOutTang, origPath.isClosed());
    return $bm_rt;
  },
];

export const markup = M;
export const init = (c, o) => mount(M, D, B, c, o,{x:v=>makeExpr(E,v)});
