// Generated by ulottie — unminified for review; not what ships.
// Object keys are sorted here for stable diffs; emitted order differs.
// mode: extern
// caps: SHAPE | KEYFRAMES | EASING | PATH_KF | PATH_D | EXPRESSIONS | LAYER_TX | EXPR_PROPERTY | EXPR_COMP | EXPR_PATH

import { mount } from './runtime/core.js';
import { makeExpr, fromCompToSurface, lyAnchor, lyAt, lyEffect, lyPath, toComp } from './runtime/expr.js';
import { bShape } from './runtime/ops/shape.js';
import { bLayerTx } from './runtime/ops/layer.js';
const B=[,,,,bShape,,,,,,bLayerTx];

const M =
  '<svg viewBox="0 0 800 600" width="100%" height="100%" preserveAspectRatio="xMidYMid meet" style="overflow:hidden">' +
    '<g transform="translate(400,300)">' +
      '<path fill="none" stroke="#1a221b" stroke-width="4"/>' +
    '</g>' +
    '<g>' +
      '<g transform="translate(225.56,-58)">' +
        '<g transform="translate(-226.38,67.81)">' +
          '<rect x="-3.875" y="-2.438" width="7.75" height="4.875" rx="1" ry="1" fill="#3d3d3d"/>' +
        '</g>' +
        '<path d="M-224,72C-228,72-229.5,72.5-229.5,72.5C-229.5,72.5-236,75.5-236,80.5C-236,85.5-231.5,97-227.5,98.5C-223.5,100-218,85.5-217.5,82.5C-217,79.5-220,72-224,72Z" fill="#0c9cf8"/>' +
      '</g>' +
    '</g>' +
    '<g>' +
      '<g transform="translate(226.85,-57.99)">' +
        '<g transform="translate(-226.38,67.81)">' +
          '<rect x="-3.875" y="-2.438" width="7.75" height="4.875" rx="1" ry="1" fill="#3d3d3d"/>' +
        '</g>' +
        '<path d="M-224,72C-228,72-229.5,72.5-229.5,72.5C-229.5,72.5-236,75.5-236,80.5C-236,85.5-231.5,97-227.5,98.5C-223.5,100-218,85.5-217.5,82.5C-217,79.5-220,72-224,72Z" fill="#f8f50d"/>' +
      '</g>' +
    '</g>' +
    '<g>' +
      '<g transform="translate(231.43,-58)">' +
        '<g transform="translate(-226.38,67.81)">' +
          '<rect x="-3.875" y="-2.438" width="7.75" height="4.875" rx="1" ry="1" fill="#3d3d3d"/>' +
        '</g>' +
        '<path d="M-224,72C-228,72-229.5,72.5-229.5,72.5C-229.5,72.5-236,75.5-236,80.5C-236,85.5-231.5,97-227.5,98.5C-223.5,100-218,85.5-217.5,82.5C-217,79.5-220,72-224,72Z" fill="#0df84f"/>' +
      '</g>' +
    '</g>' +
    '<g>' +
      '<g transform="translate(224.18,-60)">' +
        '<g transform="translate(-226.38,67.81)">' +
          '<rect x="-3.875" y="-2.438" width="7.75" height="4.875" rx="1" ry="1" fill="#3d3d3d"/>' +
        '</g>' +
        '<path d="M-224,72C-228,72-229.5,72.5-229.5,72.5C-229.5,72.5-236,75.5-236,80.5C-236,85.5-231.5,97-227.5,98.5C-223.5,100-218,85.5-217.5,82.5C-217,79.5-220,72-224,72Z" fill="#f82c11"/>' +
      '</g>' +
    '</g>' +
    '<g/>' +
    '<g>' +
      '<g transform="translate(222.11,-59.24)">' +
        '<g transform="translate(-226.38,67.81)">' +
          '<rect x="-3.875" y="-2.438" width="7.75" height="4.875" rx="1" ry="1" fill="#3d3d3d"/>' +
        '</g>' +
        '<path d="M-224,72C-228,72-229.5,72.5-229.5,72.5C-229.5,72.5-236,75.5-236,80.5C-236,85.5-231.5,97-227.5,98.5C-223.5,100-218,85.5-217.5,82.5C-217,79.5-220,72-224,72Z" fill="#f88311"/>' +
      '</g>' +
    '</g>' +
  '</svg>';

const D = "0gskt10gsni90i200000g7si30000600gt7gt7gj70io6io6ki40io6io6k86tl2v25v2gp2v200jm100000km100086s3i10k6e2k1u202k1142k1942k1922k1922k192481s602004000ikv1000eiqf06002000iooj10002000ighn20002000ighn202004000iqru5000eiqf02004000ikko4000eiqf02004000iguu2000eiqf02004000ignn1000eiqf0600200k1i1000200k1e000200k1a02004000ioqh60000202004000igiu40000202004000iosi30000202004000imku100002026gi3ol2080sg220082uh2226gr5oi20mgi980o7om1sn1qh3oi20qh3qh30qh3qh30qh3oi2020484kj2626icoi2080sg2a82uh2a80sg2c82uh2c80sg2e82uh2e80sg2g182uh2g1i36luj1uvp20i36lkru6uruv10kdavnh1gq5tuh1qq5vmi1qk6lsh1ir7tvg1in6g50000j6v4t19s3v40000k6g5u1ar3i36usk2upp30i36ofuqp30i36hh9upp30i36vgk2quv20s1qk3c8a8ccccaeeeeos22mh2ii2uh2sao84qi2uh2oo26ul2uh2oco88mm2uh2os2agn2on2uh2qfos2cgo2oo2uh2mh1os2egp2op2uh2ij1os2g1gq2oq2uh2uk1og3i1sg2k6qm1sh3k18gr2qr2ks2sp1sh3m1akg3qr2ks2or1sh3o1cug3qr2ks2kt1sh3q1eoh3qr2ks2gv1sh1s10ii3qr2ks2";

const E = [
  function(value, thisLayer, thisProperty, frame, ctx) {
    const { div, pointOnPath } = ctx;
    var $bm_rt;
    var pathLayer = lyAt(thisLayer, 8);
    var progress = div(lyEffect(thisLayer, 0, 0, frame), 100);
    var pathToTrace = pathLayer;
    $bm_rt = toComp(pathLayer, pointOnPath(lyPath(pathToTrace, frame), progress), frame);
    return $bm_rt;
  },
  function(value, thisLayer, thisProperty, frame, ctx) {
    const { div, radiansToDegrees, tangentOnPath } = ctx;
    var $bm_rt;
    var pathToTrace = lyAt(thisLayer, 8);
    var progress = div(lyEffect(thisLayer, 0, 0, frame), 100);
    var pathTan = tangentOnPath(lyPath(pathToTrace, frame), progress);
    $bm_rt = radiansToDegrees(Math.atan2(pathTan[1], pathTan[0]));
    return $bm_rt;
  },
  function(value, thisLayer, thisProperty, frame, ctx) {
    const { sum, sub, mul, div } = ctx;
    const time = frame / ctx.frameRate;
    const frameDuration = 1 / ctx.frameRate;
    const numKeys = thisProperty?.numKeys ?? 0;
    const nearestKey = thisProperty?.nearestKey ? thisProperty.nearestKey.bind(thisProperty) : ((t) => ({ index: 1, time: 0 }));
    const key = thisProperty?.key ? thisProperty.key.bind(thisProperty) : ((n) => ({ time: 0, value: 0, index: n }));
    const velocityAtTime = thisProperty?.velocityAtTime ? thisProperty.velocityAtTime.bind(thisProperty) : ((t) => 0);
    var $bm_rt;
    var amp, freq, decay, n, t, v;
    try {
        amp = div(lyEffect(thisLayer, 0, 0, frame), 2.5), freq = div(lyEffect(thisLayer, 1, 0, frame), 20), decay = div(lyEffect(thisLayer, 2, 0, frame), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : time - key(n).time, $bm_rt = 0 < n ? (v = velocityAtTime(sub(key(n).time, div(frameDuration, 10))), sum(value, div(mul(mul(div(v, 100), amp), Math.sin(mul(mul(mul(freq, t), 2), Math.PI))), Math.exp(mul(decay, t))))) : value;
    } catch (e$$4) {
        $bm_rt = value = value;
    }
    return $bm_rt;
  },
  function(value, thisLayer, thisProperty, frame, ctx) {
    const { createPath } = ctx;
    var $bm_rt;
    var nullLayerNames = [lyAt(thisLayer, 3), lyAt(thisLayer, 2), lyAt(thisLayer, 1)];
    var origPath = thisProperty;
    var origPoints = origPath.points();
    var origInTang = origPath.inTangents();
    var origOutTang = origPath.outTangents();
    var getNullLayers = [];
    for (var i = 0; i < nullLayerNames.length; i++) {
        try {
            getNullLayers.push(nullLayerNames[i]);
        } catch (err) {
            getNullLayers.push(null);
        }
    }
    for (var i = 0; i < getNullLayers.length; i++) {
        if (getNullLayers[i] != null && getNullLayers[i].i != thisLayer.i) {
            origPoints[i] = fromCompToSurface(toComp(getNullLayers[i], lyAnchor(getNullLayers[i], frame), frame), thisLayer, frame);
        }
    }
    $bm_rt = createPath(origPoints, origInTang, origOutTang, origPath.isClosed());
    return $bm_rt;
  },
];

export const markup = M;
export const init = (c, o) => mount(M, D, B, c, o,{x:v=>makeExpr(E,v)});
