// Generated by ulottie — unminified for review; not what ships.
// Object keys are sorted here for stable diffs; emitted order differs.
// mode: extern, markup extracted
// caps: TRANSLATE | DISPLAY | SHAPE | KEYFRAMES | EASING | PATH_D | TRIM | EXTRACTED

import { mount } from './runtime/core.js';
import { fromSprite } from './runtime/sprite.js';
import { bTranslate, oTranslate } from './runtime/ops/txt.js';
import { bDisplay, oDisplay } from './runtime/ops/display.js';
import { bShape, oShape } from './runtime/ops/shape.js';
const P0=(x,B,e,l,q,a)=>[bTranslate(x,B[0],e,l,q,a),bDisplay(x,B[1],e,l,q,a),bShape(x,B[2],e,l,q,a)];
const A0=(x,S)=>{oTranslate(x,S[0]);oDisplay(x,S[1]);oShape(x,S[2])};

// The document lives in an external sprite as `<symbol id="lottie_logo_1">`; the
// module carries only the shell and clones the symbol's children into it.
const M =
  '<svg viewBox="0 0 500 500" width="100%" height="100%" preserveAspectRatio="xMidYMid meet" style="overflow:hidden">' +
  '</svg>';

const D = "0gskt10gpvi92q10k3ip30000600gt7gt7uk1uk1mj5gt7qp20mj5gt720qaql2msh5aqasdmegfkg1okrvbimul7muindimul7iqnqdivjs7iomtdirkq7imlgeivjs7244422i320roomehvjs7s320i3ghop2gpvi9kb4kvualpqk2jvuampqk200outl1lmt20000kbehgus1ihk3vjmp2tmm7thqv1losh1rklt1rssh1nnpfhhobigk4krk4gkmp2qksb000imp4rqu5sv4hrn1tehpm6lok500hkgi1gnh6lui9sq60hmp400grp2kq1qlo6uvl50000kf8ivsh1kc1lrth1hvsh1kc1mrth10ult9ult900vlt9tlt900vlt9tlt900ult9ult90kb8nog8pjrfnlkenrh2opo3ojrfolkesrhc000jrm5tlt90nqg3mrm2nht3uqk30slt9igj4000kbcpqro1qmtetght1smi2tsio1ruj9hsqbrlpesnr4rkr9ught1ujt1000snv4rpn3usk3huj4ml3pmv5jnh3hql5hmr1pks2nos30lnr3sgj3nng3gti5tg4ghcik600k34rgo1ggrl1sgo1vvql1k34mgjs7qtsl5mlhkbqtsl5k36ijm1nikp1u2vk3jjm1oikp1kb4urp8oh5rrp8lmr100qol8qsm30000k34kmdhiufjmdiiufk34qhsvboipl5ikuidoipl5k34quvqasjkp6unridsjkp6k34klpvbivjs7imrgdivjs700mg140i30oc42sh2gi2sh22mg160i3g500oc442sh2oj2sh22mg16o2g5o700k6442sh2ml2sh22mg14o2g50oc42sh2kn2sh22mg14g5u60oc42sh2so2sh222sh2so2sh22mg14u6s80oc42sh2uq2sh222sh2uq2sh22mg14u6s8oc040oc2gt2ut2sh22mg14s8qaoc042su2ut2sh22mg14qaoc0oc42sh2kg3sh222sh2kg3sh222sh2kg3sh222sh2kn2sh22s104484442444222m1g8s9kfoi1sl1oq1kr1gs1gt1su1ov1kg2gh2oi1ui2sk2qm2io2qp2kq2sr2ms2iu2qv2ih3sh3mi3gj36m6m7qj3";

export const markup = M;
// `markup` is only the shell in this mode. Server-rendering the
// animation means emitting the sprite's symbol body inside it —
// `compile_document()` returns that assembled document directly.
export const spriteSymbol = 'lottie_logo_1';
export const init = (c, o) => mount(M, D, P0, A0, c, o,{s:fromSprite('lottie_logo_1')});
