// Generated by ulottie — unminified for review; not what ships.
// Object keys are sorted here for stable diffs; emitted order differs.
// mode: extern, precomps instanced
// caps: ELLIPSE | FILL | STROKE | KEYFRAMES | GEOM_STAR | PATH_D | TIMELINE | TEMPLATES | INSTANCES

import { mount } from './runtime/core.js';
import { expand } from './runtime/tpl.js';
import { bEllipse, oEllipse } from './runtime/ops/ellipse.js';
import { bFill, oFill } from './runtime/ops/fill.js';
import { bStroke, oStroke } from './runtime/ops/stroke.js';
import { bShapeStar, oShapeStar } from './runtime/ops/shape.js';
const P0=()=>0,A0=()=>0;
const P1=(x,B,e,l,q,a)=>[bShapeStar(x,B[0],e,l,q,a)];
const A1=(x,S)=>{oShapeStar(x,S[0])};
const P2=()=>0,A2=()=>0;
const P3=(x,B,e,l,q,a)=>[bEllipse(x,B[0],e,l,q,a),bFill(x,B[1],e,l,q,a),bStroke(x,B[2],e,l,q,a)];
const A3=(x,S)=>{oEllipse(x,S[0]);oFill(x,S[1]);oStroke(x,S[2])};

const M =
  '<svg viewBox="0 0 512 512" width="100%" height="100%" preserveAspectRatio="xMidYMid meet" style="overflow:hidden">' +
    '<svg width="512" height="512">' +
      '<svg width="512" height="512">' +
        '<g data-t="2"/>' +
      '</svg>' +
      '<svg width="512" height="512">' +
        '<g data-t="1"/>' +
      '</svg>' +
    '</svg>' +
  '</svg>';

const D = "0gskt10gskt100q1000qh2kj20i2000gt70o700gt70o700gt70o700gt70o700gt70o700gt70o700gt70o700gt70o720gt70o740gt70o760gt70o780gt70o7a0gt70o7c0gt70o7e0gt70o7g10gt70o700gt70o70amgg540o7gg2gg200680s3m6o70gaga0680s3m6o70g5g500p50024222ocscsdgfkg1og1og1002sg12000gt70o7g1000gt70o700gt70o700gt70o700gt70o700gt70o700gt70o700gt70o700gt70o7mgg540o700kr5kr524gg2gg22422uo1up1i38oo1kn2km5gt764s3o7oc02422ir1ur1i38keqj1kj2gt70oc660s3o70c02422mt1iu1mu16mq1qs1mv12000gt70o760oi1si1020qj104kg2sg20k12a000m4g120g4i140o3k160g3m180o2o1a0g2q1c0o1s1e0g1u1g144g20";

const TPL = [
  '<g><path fill="#fffa48" stroke-linecap="round" stroke-linejoin="round" stroke="#ff5704" stroke-width="6"/></g>',
  '<g><g transform="matrix(-.70711,-.70711,.70711,-.70711,256,618.04)"><svg width="512" height="512"><g data-t="0"/></svg></g><g transform="matrix(0,-1,1,0,0,512)"><svg width="512" height="512"><g data-t="0"/></svg></g><g transform="matrix(.70711,-.70711,.70711,.70711,-106.04,256)"><svg width="512" height="512"><g data-t="0"/></svg></g><g transform="matrix(-1,0,0,-1,512,512)"><svg width="512" height="512"><g data-t="0"/></svg></g><g transform="matrix(-.70711,.70711,-.70711,-.70711,618.04,256)"><svg width="512" height="512"><g data-t="0"/></svg></g><g transform="matrix(0,1,-1,0,512,0)"><svg width="512" height="512"><g data-t="0"/></svg></g><g transform="matrix(.70711,.70711,-.70711,.70711,256,-106.04)"><svg width="512" height="512"><g data-t="0"/></svg></g><svg width="512" height="512"><g data-t="0"/></svg></g>',
  '<g><ellipse stroke-linecap="round" stroke-linejoin="round"/></g>',
];

export const markup = M;
export const init = (c, o) => mount(M, D, P0, A0, c, o,{a:[P1,P2,P3],b:[A1,A2,A3],t:s=>expand(s,TPL)});
