// Generated by ulottie — reanimated-aot target (react-native-svg + react-native-reanimated).
// Deliberately unminified: Metro's reanimated plugin reads the 'worklet' directives
// before its own minifier runs; a minifier here could strip them.
// caps: none

// Fully static after compilation: the tree descriptor is the whole picture.
// `init` returns an inert instance so consumers keep one code path.

export const tree =
{ type: 'Svg', staticProps: { viewBox: '0 0 512 512', width: '100%', height: '100%', preserveAspectRatio: 'xMidYMid meet' }, children: [
  { type: 'Defs', staticProps: {  }, children: [
    { type: 'ClipPath', staticProps: { id: 'vp0' }, children: [
      { type: 'Rect', staticProps: { width: '512', height: '512' } }
    ] }
  ] },
  { type: 'G', staticProps: { clipPath: 'url(#vp0)' }, children: [
    { type: 'Rect', staticProps: { x: '128', y: '128', width: '256', height: '256', fill: 'none', strokeLinecap: 'round', strokeLinejoin: 'round', stroke: '#fffa48', strokeWidth: '30' } }
  ] }
] };

export const meta = { fr: 60, ip: 0, op: 180, width: 512, height: 512 };
export const init = () => { 'worklet'; return { els: [], dirty: [], apply: function () { 'worklet'; }, fr: 60, ip: 0, op: 180 }; };
