// Generated by ulottie — unminified for review; not what ships.
// Object keys are sorted here for stable diffs; emitted order differs.
// mode: extern
// caps: TRANSLATE | SHAPE | FILL | KEYFRAMES | EASING | SPATIAL | PATH_KF | PATH_D

import { mount } from './runtime/core.js';
import { bTranslate, oTranslate } from './runtime/ops/txt.js';
import { bShape, oShape } from './runtime/ops/shape.js';
import { bFill, oFill } from './runtime/ops/fill.js';
const P0=(x,B,e,l,q,a)=>[bTranslate(x,B[0],e,l,q,a),bShape(x,B[1],e,l,q,a),bFill(x,B[2],e,l,q,a)];
const A0=(x,S)=>{oTranslate(x,S[0]);oShape(x,S[1]);oFill(x,S[2])};

const M =
  '<svg viewBox="0 0 174 149" width="100%" height="100%" preserveAspectRatio="xMidYMid meet" style="overflow:hidden">' +
    '<svg width="174" height="149">' +
      '<g transform="translate(75.75,74.5)">' +
        '<g>' +
          '<g transform="translate(73.72,19.27)">' +
            '<path fill="none" stroke-miterlimit="10" stroke="#9b2236" stroke-width="4"/>' +
          '</g>' +
        '</g>' +
        '<g>' +
          '<g transform="translate(80.6,19.02)">' +
            '<path fill="none" stroke-miterlimit="10" stroke="#9b2236" stroke-width="4"/>' +
          '</g>' +
        '</g>' +
        '<g>' +
          '<g transform="matrix(5,0,0,3.92157,-182.5,-72.68)">' +
            '<g transform="translate(59.75,19.27)">' +
              '<path paint-order="stroke" stroke-miterlimit="10" stroke="#9b2236" stroke-width="4"/>' +
            '</g>' +
          '</g>' +
          '<g>' +
            '<g transform="translate(16.52,14.51)">' +
              '<path d="M13.832-10.021L-13.436-14.031C-15.026-14.264-16.271-12.685-15.672-11.194L-6.19,12.438C-5.458,14.264-2.834,14.157-2.268,12.272C-.882,7.662,1.525,1.647,5.237-1.438C7.628-3.425,10.966-4.911,14.194-5.99C16.271-6.685,16-9.702,13.832-10.021Z" fill="#ca3149"/>' +
            '</g>' +
          '</g>' +
        '</g>' +
      '</g>' +
    '</svg>' +
  '</svg>';

const D = "0kiqe0gtmm50q100oh30000600gt7gt7qp200gt7id00gt7msq54saienmmj2huig1nmmj2hu820qqp20pqp2msq54iaienmmj2rn5nmmj2gmqf20kqq20jqq2msq54k8ubvlnm1gjifvlnm1rqng120vkk50glk5msq580o4og1gj1omjjj1gsrk2gjtj5ivsn1gjtj5ivsn1gvmkj1ktqha222rvrj4qqsg2nhfvn800qmnn2onjm100008046680024vhu4vhu40pllo2lom9lom90rqsr1k3u4o6i8kfcumpq1mmo4rmpq1mmo4jthv10rmpq1lmo4umpq1lmo4kthv10svn20000svn2rvn20000rvn200rvn200rvn200svn200svn2kfcipgi2kgp4rmpq1mmo4jthv10rmpq1lmo4ipgi2nsn4ovom2u9svn20000svn2rvn20000rvn200rvn200rvn200svn200svn2mgi64ug1oi1oekj14kfcgivt1mmo4vhvt1mmo4loni20vhvt1lmo4givt1lmo4moni20qvn20000svn2rvn20000rvn200rvn200rvn200qvn200svn2kfcohj9mnp4vhvt1mmo4loni20vhvt1lmo4ohj9lln4unrdgh1qvn20000svn2rvn20000rvn200rvn200rvn200qvn200svn2mgg64ug1oi1uo1qt1kfcmksj1mmo4lksj1mmo4rqko10lksj1lmo4mksj1lmo4sqko10qvn20000svn2rvn20000rvn200rvn200rvn200qvn200svn2kfcukgi2ojn4lksj1mmo4rqko10lksj1lmo4ukgi2jpp4krom2ti1qvn20000svn2rvn20000rvn200rvn200rvn200qvn200svn2mgi64ug1oi1ij2un2460868go1mi2qs2000i38sh300gt768o5q5geme0i4i4020m1uu2qv26sbot2ug3";

const SP = [
  'matrix(.2,0,0,.255,',
  'matrix(5,0,0,3.92157,',
];

export const markup = M;
export const init = (c, o) => mount(M, D, P0, A0, c, o,{p:SP});
